module StripeAPI.Types.AccountServiceResourcePlatformRestrictions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountServiceResourcePlatformRestrictions
instance Show AccountServiceResourcePlatformRestrictions
instance Eq AccountServiceResourcePlatformRestrictions
instance FromJSON AccountServiceResourcePlatformRestrictions
instance ToJSON AccountServiceResourcePlatformRestrictions
data AccountServiceResourcePlatformRestrictionsInboundFlows'NonNullable
instance Show AccountServiceResourcePlatformRestrictionsInboundFlows'NonNullable
instance Eq AccountServiceResourcePlatformRestrictionsInboundFlows'NonNullable
instance FromJSON AccountServiceResourcePlatformRestrictionsInboundFlows'NonNullable
instance ToJSON AccountServiceResourcePlatformRestrictionsInboundFlows'NonNullable
data AccountServiceResourcePlatformRestrictionsOutboundFlows'NonNullable
instance Show AccountServiceResourcePlatformRestrictionsOutboundFlows'NonNullable
instance Eq AccountServiceResourcePlatformRestrictionsOutboundFlows'NonNullable
instance FromJSON AccountServiceResourcePlatformRestrictionsOutboundFlows'NonNullable
instance ToJSON AccountServiceResourcePlatformRestrictionsOutboundFlows'NonNullable
