module StripeAPI.Types.AccountServiceResourceTreasuryStatusDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountServiceResourceTreasuryStatusDetails
instance Show AccountServiceResourceTreasuryStatusDetails
instance Eq AccountServiceResourceTreasuryStatusDetails
instance FromJSON AccountServiceResourceTreasuryStatusDetails
instance ToJSON AccountServiceResourceTreasuryStatusDetails
data AccountServiceResourceTreasuryStatusDetailsClosed'NonNullable
instance Show AccountServiceResourceTreasuryStatusDetailsClosed'NonNullable
instance Eq AccountServiceResourceTreasuryStatusDetailsClosed'NonNullable
instance FromJSON AccountServiceResourceTreasuryStatusDetailsClosed'NonNullable
instance ToJSON AccountServiceResourceTreasuryStatusDetailsClosed'NonNullable
data AccountServiceResourceTreasuryStatusDetailsClosed'NonNullableReasons'
instance Show AccountServiceResourceTreasuryStatusDetailsClosed'NonNullableReasons'
instance Eq AccountServiceResourceTreasuryStatusDetailsClosed'NonNullableReasons'
instance FromJSON AccountServiceResourceTreasuryStatusDetailsClosed'NonNullableReasons'
instance ToJSON AccountServiceResourceTreasuryStatusDetailsClosed'NonNullableReasons'
