module StripeAPI.Types.AccountServiceResourceToggleSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountServiceResourceToggleSettings
instance Show AccountServiceResourceToggleSettings
instance Eq AccountServiceResourceToggleSettings
instance FromJSON AccountServiceResourceToggleSettings
instance ToJSON AccountServiceResourceToggleSettings
data AccountServiceResourceToggleSettingsStatus'
instance Show AccountServiceResourceToggleSettingsStatus'
instance Eq AccountServiceResourceToggleSettingsStatus'
instance FromJSON AccountServiceResourceToggleSettingsStatus'
instance ToJSON AccountServiceResourceToggleSettingsStatus'
