module StripeAPI.Types.AccountDashboardSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountDashboardSettings
instance Show AccountDashboardSettings
instance Eq AccountDashboardSettings
instance FromJSON AccountDashboardSettings
instance ToJSON AccountDashboardSettings
