module StripeAPI.Types.AccountSepaDebitPaymentsSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data AccountSepaDebitPaymentsSettings
instance Show AccountSepaDebitPaymentsSettings
instance Eq AccountSepaDebitPaymentsSettings
instance FromJSON AccountSepaDebitPaymentsSettings
instance ToJSON AccountSepaDebitPaymentsSettings
