module StripeAPI.Types.AccountBacsDebitPaymentsSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountBacsDebitPaymentsSettings
instance Show AccountBacsDebitPaymentsSettings
instance Eq AccountBacsDebitPaymentsSettings
instance FromJSON AccountBacsDebitPaymentsSettings
instance ToJSON AccountBacsDebitPaymentsSettings
