module StripeAPI.Types.AccountCapabilityFutureRequirements where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountCapabilityFutureRequirements
instance Show AccountCapabilityFutureRequirements
instance Eq AccountCapabilityFutureRequirements
instance FromJSON AccountCapabilityFutureRequirements
instance ToJSON AccountCapabilityFutureRequirements
