module StripeAPI.Types.AccountServiceResourceTreasuryClosedStatusDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountServiceResourceTreasuryClosedStatusDetails
instance Show AccountServiceResourceTreasuryClosedStatusDetails
instance Eq AccountServiceResourceTreasuryClosedStatusDetails
instance FromJSON AccountServiceResourceTreasuryClosedStatusDetails
instance ToJSON AccountServiceResourceTreasuryClosedStatusDetails
data AccountServiceResourceTreasuryClosedStatusDetailsReasons'
instance Show AccountServiceResourceTreasuryClosedStatusDetailsReasons'
instance Eq AccountServiceResourceTreasuryClosedStatusDetailsReasons'
instance FromJSON AccountServiceResourceTreasuryClosedStatusDetailsReasons'
instance ToJSON AccountServiceResourceTreasuryClosedStatusDetailsReasons'
