module StripeAPI.Types.AccountServiceResourceFinancialAddress where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountServiceResourceFinancialAddress
instance Show AccountServiceResourceFinancialAddress
instance Eq AccountServiceResourceFinancialAddress
instance FromJSON AccountServiceResourceFinancialAddress
instance ToJSON AccountServiceResourceFinancialAddress
data AccountServiceResourceFinancialAddressSupportedNetworks'
instance Show AccountServiceResourceFinancialAddressSupportedNetworks'
instance Eq AccountServiceResourceFinancialAddressSupportedNetworks'
instance FromJSON AccountServiceResourceFinancialAddressSupportedNetworks'
instance ToJSON AccountServiceResourceFinancialAddressSupportedNetworks'
