{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema AccountMonthlyEstimatedRevenue
module StripeAPI.Types.AccountMonthlyEstimatedRevenue where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.account_monthly_estimated_revenue@ in the specification.
data AccountMonthlyEstimatedRevenue = AccountMonthlyEstimatedRevenue
  { -- | amount: A non-negative integer representing how much to charge in the [smallest currency unit](https:\/\/stripe.com\/docs\/currencies\#zero-decimal).
    accountMonthlyEstimatedRevenueAmount :: GHC.Types.Int,
    -- | currency: Three-letter [ISO currency code](https:\/\/www.iso.org\/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https:\/\/stripe.com\/docs\/currencies).
    accountMonthlyEstimatedRevenueCurrency :: Data.Text.Internal.Text
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON AccountMonthlyEstimatedRevenue where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["amount" Data.Aeson.Types.ToJSON..= accountMonthlyEstimatedRevenueAmount obj] : ["currency" Data.Aeson.Types.ToJSON..= accountMonthlyEstimatedRevenueCurrency obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["amount" Data.Aeson.Types.ToJSON..= accountMonthlyEstimatedRevenueAmount obj] : ["currency" Data.Aeson.Types.ToJSON..= accountMonthlyEstimatedRevenueCurrency obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON AccountMonthlyEstimatedRevenue where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "AccountMonthlyEstimatedRevenue" (\obj -> (GHC.Base.pure AccountMonthlyEstimatedRevenue GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "amount")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "currency"))

-- | Create a new 'AccountMonthlyEstimatedRevenue' with all required fields.
mkAccountMonthlyEstimatedRevenue ::
  -- | 'accountMonthlyEstimatedRevenueAmount'
  GHC.Types.Int ->
  -- | 'accountMonthlyEstimatedRevenueCurrency'
  Data.Text.Internal.Text ->
  AccountMonthlyEstimatedRevenue
mkAccountMonthlyEstimatedRevenue accountMonthlyEstimatedRevenueAmount accountMonthlyEstimatedRevenueCurrency =
  AccountMonthlyEstimatedRevenue
    { accountMonthlyEstimatedRevenueAmount = accountMonthlyEstimatedRevenueAmount,
      accountMonthlyEstimatedRevenueCurrency = accountMonthlyEstimatedRevenueCurrency
    }
