module StripeAPI.Types.AccountServiceResourceInboundTransfers where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountServiceResourceInboundTransfers
instance Show AccountServiceResourceInboundTransfers
instance Eq AccountServiceResourceInboundTransfers
instance FromJSON AccountServiceResourceInboundTransfers
instance ToJSON AccountServiceResourceInboundTransfers
