module StripeAPI.Types.AccountServiceResourceStatusDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountServiceResourceStatusDetails
instance Show AccountServiceResourceStatusDetails
instance Eq AccountServiceResourceStatusDetails
instance FromJSON AccountServiceResourceStatusDetails
instance ToJSON AccountServiceResourceStatusDetails
data AccountServiceResourceStatusDetailsCode'
instance Show AccountServiceResourceStatusDetailsCode'
instance Eq AccountServiceResourceStatusDetailsCode'
instance FromJSON AccountServiceResourceStatusDetailsCode'
instance ToJSON AccountServiceResourceStatusDetailsCode'
data AccountServiceResourceStatusDetailsResolution'NonNullable
instance Show AccountServiceResourceStatusDetailsResolution'NonNullable
instance Eq AccountServiceResourceStatusDetailsResolution'NonNullable
instance FromJSON AccountServiceResourceStatusDetailsResolution'NonNullable
instance ToJSON AccountServiceResourceStatusDetailsResolution'NonNullable
data AccountServiceResourceStatusDetailsRestriction'
instance Show AccountServiceResourceStatusDetailsRestriction'
instance Eq AccountServiceResourceStatusDetailsRestriction'
instance FromJSON AccountServiceResourceStatusDetailsRestriction'
instance ToJSON AccountServiceResourceStatusDetailsRestriction'
