module StripeAPI.Types.AccountMonthlyEstimatedRevenue where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountMonthlyEstimatedRevenue
instance Show AccountMonthlyEstimatedRevenue
instance Eq AccountMonthlyEstimatedRevenue
instance FromJSON AccountMonthlyEstimatedRevenue
instance ToJSON AccountMonthlyEstimatedRevenue
