module StripeAPI.Types.AccountCardIssuingSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountCardIssuingSettings
instance Show AccountCardIssuingSettings
instance Eq AccountCardIssuingSettings
instance FromJSON AccountCardIssuingSettings
instance ToJSON AccountCardIssuingSettings
