module StripeAPI.Types.AccountUnificationAccountController where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data AccountUnificationAccountController
instance Show AccountUnificationAccountController
instance Eq AccountUnificationAccountController
instance FromJSON AccountUnificationAccountController
instance ToJSON AccountUnificationAccountController
data AccountUnificationAccountControllerType'
instance Show AccountUnificationAccountControllerType'
instance Eq AccountUnificationAccountControllerType'
instance FromJSON AccountUnificationAccountControllerType'
instance ToJSON AccountUnificationAccountControllerType'
