module StripeAPI.Types.BalanceAmountBySourceType where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data BalanceAmountBySourceType
instance Show BalanceAmountBySourceType
instance Eq BalanceAmountBySourceType
instance FromJSON BalanceAmountBySourceType
instance ToJSON BalanceAmountBySourceType
