module StripeAPI.Types.BankConnectionsResourceOwnershipRefresh where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data BankConnectionsResourceOwnershipRefresh
instance Show BankConnectionsResourceOwnershipRefresh
instance Eq BankConnectionsResourceOwnershipRefresh
instance FromJSON BankConnectionsResourceOwnershipRefresh
instance ToJSON BankConnectionsResourceOwnershipRefresh
data BankConnectionsResourceOwnershipRefreshStatus'
instance Show BankConnectionsResourceOwnershipRefreshStatus'
instance Eq BankConnectionsResourceOwnershipRefreshStatus'
instance FromJSON BankConnectionsResourceOwnershipRefreshStatus'
instance ToJSON BankConnectionsResourceOwnershipRefreshStatus'
