module StripeAPI.Types.BankConnectionsResourceBalanceApiResourceCashBalance where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data BankConnectionsResourceBalanceApiResourceCashBalance
instance Show BankConnectionsResourceBalanceApiResourceCashBalance
instance Eq BankConnectionsResourceBalanceApiResourceCashBalance
instance FromJSON BankConnectionsResourceBalanceApiResourceCashBalance
instance ToJSON BankConnectionsResourceBalanceApiResourceCashBalance
