module StripeAPI.Types.BankConnectionsResourceAccountholder where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data BankConnectionsResourceAccountholder
instance Show BankConnectionsResourceAccountholder
instance Eq BankConnectionsResourceAccountholder
instance FromJSON BankConnectionsResourceAccountholder
instance ToJSON BankConnectionsResourceAccountholder
data BankConnectionsResourceAccountholderAccount'Variants
instance Show BankConnectionsResourceAccountholderAccount'Variants
instance Eq BankConnectionsResourceAccountholderAccount'Variants
instance FromJSON BankConnectionsResourceAccountholderAccount'Variants
instance ToJSON BankConnectionsResourceAccountholderAccount'Variants
data BankConnectionsResourceAccountholderCustomer'Variants
instance Show BankConnectionsResourceAccountholderCustomer'Variants
instance Eq BankConnectionsResourceAccountholderCustomer'Variants
instance FromJSON BankConnectionsResourceAccountholderCustomer'Variants
instance ToJSON BankConnectionsResourceAccountholderCustomer'Variants
data BankConnectionsResourceAccountholderType'
instance Show BankConnectionsResourceAccountholderType'
instance Eq BankConnectionsResourceAccountholderType'
instance FromJSON BankConnectionsResourceAccountholderType'
instance ToJSON BankConnectionsResourceAccountholderType'
