module StripeAPI.Types.BankConnectionsResourceBalanceApiResourceCreditBalance where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data BankConnectionsResourceBalanceApiResourceCreditBalance
instance Show BankConnectionsResourceBalanceApiResourceCreditBalance
instance Eq BankConnectionsResourceBalanceApiResourceCreditBalance
instance FromJSON BankConnectionsResourceBalanceApiResourceCreditBalance
instance ToJSON BankConnectionsResourceBalanceApiResourceCreditBalance
