module StripeAPI.Types.BankConnectionsResourceTransactionResourceStatusTransitions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data BankConnectionsResourceTransactionResourceStatusTransitions
instance Show BankConnectionsResourceTransactionResourceStatusTransitions
instance Eq BankConnectionsResourceTransactionResourceStatusTransitions
instance FromJSON BankConnectionsResourceTransactionResourceStatusTransitions
instance ToJSON BankConnectionsResourceTransactionResourceStatusTransitions
