module StripeAPI.Types.CheckoutAcssDebitMandateOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data CheckoutAcssDebitMandateOptions
instance Show CheckoutAcssDebitMandateOptions
instance Eq CheckoutAcssDebitMandateOptions
instance FromJSON CheckoutAcssDebitMandateOptions
instance ToJSON CheckoutAcssDebitMandateOptions
data CheckoutAcssDebitMandateOptionsPaymentSchedule'
instance Show CheckoutAcssDebitMandateOptionsPaymentSchedule'
instance Eq CheckoutAcssDebitMandateOptionsPaymentSchedule'
instance FromJSON CheckoutAcssDebitMandateOptionsPaymentSchedule'
instance ToJSON CheckoutAcssDebitMandateOptionsPaymentSchedule'
data CheckoutAcssDebitMandateOptionsTransactionType'
instance Show CheckoutAcssDebitMandateOptionsTransactionType'
instance Eq CheckoutAcssDebitMandateOptionsTransactionType'
instance FromJSON CheckoutAcssDebitMandateOptionsTransactionType'
instance ToJSON CheckoutAcssDebitMandateOptionsTransactionType'
