module StripeAPI.Types.CheckoutCustomerBalancePaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutCustomerBalancePaymentMethodOptions
instance Show CheckoutCustomerBalancePaymentMethodOptions
instance Eq CheckoutCustomerBalancePaymentMethodOptions
instance FromJSON CheckoutCustomerBalancePaymentMethodOptions
instance ToJSON CheckoutCustomerBalancePaymentMethodOptions
data CheckoutCustomerBalancePaymentMethodOptionsFundingType'NonNullable
instance Show CheckoutCustomerBalancePaymentMethodOptionsFundingType'NonNullable
instance Eq CheckoutCustomerBalancePaymentMethodOptionsFundingType'NonNullable
instance FromJSON CheckoutCustomerBalancePaymentMethodOptionsFundingType'NonNullable
instance ToJSON CheckoutCustomerBalancePaymentMethodOptionsFundingType'NonNullable
data CheckoutCustomerBalancePaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutCustomerBalancePaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutCustomerBalancePaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutCustomerBalancePaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutCustomerBalancePaymentMethodOptionsSetupFutureUsage'
