module StripeAPI.Types.CheckoutBacsDebitPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutBacsDebitPaymentMethodOptions
instance Show CheckoutBacsDebitPaymentMethodOptions
instance Eq CheckoutBacsDebitPaymentMethodOptions
instance FromJSON CheckoutBacsDebitPaymentMethodOptions
instance ToJSON CheckoutBacsDebitPaymentMethodOptions
data CheckoutBacsDebitPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutBacsDebitPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutBacsDebitPaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutBacsDebitPaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutBacsDebitPaymentMethodOptionsSetupFutureUsage'
