module StripeAPI.Types.CheckoutAfterpayClearpayPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutAfterpayClearpayPaymentMethodOptions
instance Show CheckoutAfterpayClearpayPaymentMethodOptions
instance Eq CheckoutAfterpayClearpayPaymentMethodOptions
instance FromJSON CheckoutAfterpayClearpayPaymentMethodOptions
instance ToJSON CheckoutAfterpayClearpayPaymentMethodOptions
data CheckoutAfterpayClearpayPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutAfterpayClearpayPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutAfterpayClearpayPaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutAfterpayClearpayPaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutAfterpayClearpayPaymentMethodOptionsSetupFutureUsage'
