module StripeAPI.Types.CheckoutAcssDebitMandateOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutAcssDebitMandateOptions
instance Show CheckoutAcssDebitMandateOptions
instance Eq CheckoutAcssDebitMandateOptions
instance FromJSON CheckoutAcssDebitMandateOptions
instance ToJSON CheckoutAcssDebitMandateOptions
data CheckoutAcssDebitMandateOptionsDefaultFor'
instance Show CheckoutAcssDebitMandateOptionsDefaultFor'
instance Eq CheckoutAcssDebitMandateOptionsDefaultFor'
instance FromJSON CheckoutAcssDebitMandateOptionsDefaultFor'
instance ToJSON CheckoutAcssDebitMandateOptionsDefaultFor'
data CheckoutAcssDebitMandateOptionsPaymentSchedule'NonNullable
instance Show CheckoutAcssDebitMandateOptionsPaymentSchedule'NonNullable
instance Eq CheckoutAcssDebitMandateOptionsPaymentSchedule'NonNullable
instance FromJSON CheckoutAcssDebitMandateOptionsPaymentSchedule'NonNullable
instance ToJSON CheckoutAcssDebitMandateOptionsPaymentSchedule'NonNullable
data CheckoutAcssDebitMandateOptionsTransactionType'NonNullable
instance Show CheckoutAcssDebitMandateOptionsTransactionType'NonNullable
instance Eq CheckoutAcssDebitMandateOptionsTransactionType'NonNullable
instance FromJSON CheckoutAcssDebitMandateOptionsTransactionType'NonNullable
instance ToJSON CheckoutAcssDebitMandateOptionsTransactionType'NonNullable
