module StripeAPI.Types.CheckoutAuBecsDebitPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutAuBecsDebitPaymentMethodOptions
instance Show CheckoutAuBecsDebitPaymentMethodOptions
instance Eq CheckoutAuBecsDebitPaymentMethodOptions
instance FromJSON CheckoutAuBecsDebitPaymentMethodOptions
instance ToJSON CheckoutAuBecsDebitPaymentMethodOptions
data CheckoutAuBecsDebitPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutAuBecsDebitPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutAuBecsDebitPaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutAuBecsDebitPaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutAuBecsDebitPaymentMethodOptionsSetupFutureUsage'
