module StripeAPI.Types.CheckoutBancontactPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutBancontactPaymentMethodOptions
instance Show CheckoutBancontactPaymentMethodOptions
instance Eq CheckoutBancontactPaymentMethodOptions
instance FromJSON CheckoutBancontactPaymentMethodOptions
instance ToJSON CheckoutBancontactPaymentMethodOptions
data CheckoutBancontactPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutBancontactPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutBancontactPaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutBancontactPaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutBancontactPaymentMethodOptionsSetupFutureUsage'
