module StripeAPI.Types.CheckoutCardInstallmentsOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutCardInstallmentsOptions
instance Show CheckoutCardInstallmentsOptions
instance Eq CheckoutCardInstallmentsOptions
instance FromJSON CheckoutCardInstallmentsOptions
instance ToJSON CheckoutCardInstallmentsOptions
