module StripeAPI.Types.CheckoutSessionPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutSessionPaymentMethodOptions
instance Show CheckoutSessionPaymentMethodOptions
instance Eq CheckoutSessionPaymentMethodOptions
instance FromJSON CheckoutSessionPaymentMethodOptions
instance ToJSON CheckoutSessionPaymentMethodOptions
