module StripeAPI.Types.CheckoutPaynowPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutPaynowPaymentMethodOptions
instance Show CheckoutPaynowPaymentMethodOptions
instance Eq CheckoutPaynowPaymentMethodOptions
instance FromJSON CheckoutPaynowPaymentMethodOptions
instance ToJSON CheckoutPaynowPaymentMethodOptions
data CheckoutPaynowPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutPaynowPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutPaynowPaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutPaynowPaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutPaynowPaymentMethodOptionsSetupFutureUsage'
