module StripeAPI.Types.CheckoutAcssDebitPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data CheckoutAcssDebitPaymentMethodOptions
instance Show CheckoutAcssDebitPaymentMethodOptions
instance Eq CheckoutAcssDebitPaymentMethodOptions
instance FromJSON CheckoutAcssDebitPaymentMethodOptions
instance ToJSON CheckoutAcssDebitPaymentMethodOptions
data CheckoutAcssDebitPaymentMethodOptionsCurrency'
instance Show CheckoutAcssDebitPaymentMethodOptionsCurrency'
instance Eq CheckoutAcssDebitPaymentMethodOptionsCurrency'
instance FromJSON CheckoutAcssDebitPaymentMethodOptionsCurrency'
instance ToJSON CheckoutAcssDebitPaymentMethodOptionsCurrency'
data CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
instance Show CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
instance Eq CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
instance FromJSON CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
instance ToJSON CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
