module StripeAPI.Types.CheckoutSepaDebitPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutSepaDebitPaymentMethodOptions
instance Show CheckoutSepaDebitPaymentMethodOptions
instance Eq CheckoutSepaDebitPaymentMethodOptions
instance FromJSON CheckoutSepaDebitPaymentMethodOptions
instance ToJSON CheckoutSepaDebitPaymentMethodOptions
data CheckoutSepaDebitPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutSepaDebitPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutSepaDebitPaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutSepaDebitPaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutSepaDebitPaymentMethodOptionsSetupFutureUsage'
