module StripeAPI.Types.CheckoutPaypalPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutPaypalPaymentMethodOptions
instance Show CheckoutPaypalPaymentMethodOptions
instance Eq CheckoutPaypalPaymentMethodOptions
instance FromJSON CheckoutPaypalPaymentMethodOptions
instance ToJSON CheckoutPaypalPaymentMethodOptions
data CheckoutPaypalPaymentMethodOptionsCaptureMethod'
instance Show CheckoutPaypalPaymentMethodOptionsCaptureMethod'
instance Eq CheckoutPaypalPaymentMethodOptionsCaptureMethod'
instance FromJSON CheckoutPaypalPaymentMethodOptionsCaptureMethod'
instance ToJSON CheckoutPaypalPaymentMethodOptionsCaptureMethod'
data CheckoutPaypalPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutPaypalPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutPaypalPaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutPaypalPaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutPaypalPaymentMethodOptionsSetupFutureUsage'
