module StripeAPI.Types.CheckoutCustomerBalanceBankTransferPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutCustomerBalanceBankTransferPaymentMethodOptions
instance Show CheckoutCustomerBalanceBankTransferPaymentMethodOptions
instance Eq CheckoutCustomerBalanceBankTransferPaymentMethodOptions
instance FromJSON CheckoutCustomerBalanceBankTransferPaymentMethodOptions
instance ToJSON CheckoutCustomerBalanceBankTransferPaymentMethodOptions
data CheckoutCustomerBalanceBankTransferPaymentMethodOptionsRequestedAddressTypes'
instance Show CheckoutCustomerBalanceBankTransferPaymentMethodOptionsRequestedAddressTypes'
instance Eq CheckoutCustomerBalanceBankTransferPaymentMethodOptionsRequestedAddressTypes'
instance FromJSON CheckoutCustomerBalanceBankTransferPaymentMethodOptionsRequestedAddressTypes'
instance ToJSON CheckoutCustomerBalanceBankTransferPaymentMethodOptionsRequestedAddressTypes'
data CheckoutCustomerBalanceBankTransferPaymentMethodOptionsType'NonNullable
instance Show CheckoutCustomerBalanceBankTransferPaymentMethodOptionsType'NonNullable
instance Eq CheckoutCustomerBalanceBankTransferPaymentMethodOptionsType'NonNullable
instance FromJSON CheckoutCustomerBalanceBankTransferPaymentMethodOptionsType'NonNullable
instance ToJSON CheckoutCustomerBalanceBankTransferPaymentMethodOptionsType'NonNullable
