module StripeAPI.Types.CheckoutBoletoPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutBoletoPaymentMethodOptions
instance Show CheckoutBoletoPaymentMethodOptions
instance Eq CheckoutBoletoPaymentMethodOptions
instance FromJSON CheckoutBoletoPaymentMethodOptions
instance ToJSON CheckoutBoletoPaymentMethodOptions
data CheckoutBoletoPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutBoletoPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutBoletoPaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutBoletoPaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutBoletoPaymentMethodOptionsSetupFutureUsage'
