module StripeAPI.Types.CheckoutAcssDebitPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutAcssDebitPaymentMethodOptions
instance Show CheckoutAcssDebitPaymentMethodOptions
instance Eq CheckoutAcssDebitPaymentMethodOptions
instance FromJSON CheckoutAcssDebitPaymentMethodOptions
instance ToJSON CheckoutAcssDebitPaymentMethodOptions
data CheckoutAcssDebitPaymentMethodOptionsCurrency'
instance Show CheckoutAcssDebitPaymentMethodOptionsCurrency'
instance Eq CheckoutAcssDebitPaymentMethodOptionsCurrency'
instance FromJSON CheckoutAcssDebitPaymentMethodOptionsCurrency'
instance ToJSON CheckoutAcssDebitPaymentMethodOptionsCurrency'
data CheckoutAcssDebitPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutAcssDebitPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutAcssDebitPaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutAcssDebitPaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutAcssDebitPaymentMethodOptionsSetupFutureUsage'
data CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
instance Show CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
instance Eq CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
instance FromJSON CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
instance ToJSON CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
