module StripeAPI.Types.CheckoutUsBankAccountPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutUsBankAccountPaymentMethodOptions
instance Show CheckoutUsBankAccountPaymentMethodOptions
instance Eq CheckoutUsBankAccountPaymentMethodOptions
instance FromJSON CheckoutUsBankAccountPaymentMethodOptions
instance ToJSON CheckoutUsBankAccountPaymentMethodOptions
data CheckoutUsBankAccountPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutUsBankAccountPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutUsBankAccountPaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutUsBankAccountPaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutUsBankAccountPaymentMethodOptionsSetupFutureUsage'
data CheckoutUsBankAccountPaymentMethodOptionsVerificationMethod'
instance Show CheckoutUsBankAccountPaymentMethodOptionsVerificationMethod'
instance Eq CheckoutUsBankAccountPaymentMethodOptionsVerificationMethod'
instance FromJSON CheckoutUsBankAccountPaymentMethodOptionsVerificationMethod'
instance ToJSON CheckoutUsBankAccountPaymentMethodOptionsVerificationMethod'
