module StripeAPI.Types.CheckoutCardPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutCardPaymentMethodOptions
instance Show CheckoutCardPaymentMethodOptions
instance Eq CheckoutCardPaymentMethodOptions
instance FromJSON CheckoutCardPaymentMethodOptions
instance ToJSON CheckoutCardPaymentMethodOptions
data CheckoutCardPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutCardPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutCardPaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutCardPaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutCardPaymentMethodOptionsSetupFutureUsage'
