module StripeAPI.Types.CheckoutLinkPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CheckoutLinkPaymentMethodOptions
instance Show CheckoutLinkPaymentMethodOptions
instance Eq CheckoutLinkPaymentMethodOptions
instance FromJSON CheckoutLinkPaymentMethodOptions
instance ToJSON CheckoutLinkPaymentMethodOptions
data CheckoutLinkPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutLinkPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutLinkPaymentMethodOptionsSetupFutureUsage'
instance FromJSON CheckoutLinkPaymentMethodOptionsSetupFutureUsage'
instance ToJSON CheckoutLinkPaymentMethodOptionsSetupFutureUsage'
