module StripeAPI.Types.ClimateRemovalsBeneficiary where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data ClimateRemovalsBeneficiary
instance Show ClimateRemovalsBeneficiary
instance Eq ClimateRemovalsBeneficiary
instance FromJSON ClimateRemovalsBeneficiary
instance ToJSON ClimateRemovalsBeneficiary
