module StripeAPI.Types.ConnectEmbeddedPaymentsFeatures where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data ConnectEmbeddedPaymentsFeatures
instance Show ConnectEmbeddedPaymentsFeatures
instance Eq ConnectEmbeddedPaymentsFeatures
instance FromJSON ConnectEmbeddedPaymentsFeatures
instance ToJSON ConnectEmbeddedPaymentsFeatures
