module StripeAPI.Types.ConnectEmbeddedPayoutsConfig where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data ConnectEmbeddedPayoutsConfig
instance Show ConnectEmbeddedPayoutsConfig
instance Eq ConnectEmbeddedPayoutsConfig
instance FromJSON ConnectEmbeddedPayoutsConfig
instance ToJSON ConnectEmbeddedPayoutsConfig
