module StripeAPI.Types.ConnectEmbeddedBaseConfigClaim where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data ConnectEmbeddedBaseConfigClaim
instance Show ConnectEmbeddedBaseConfigClaim
instance Eq ConnectEmbeddedBaseConfigClaim
instance FromJSON ConnectEmbeddedBaseConfigClaim
instance ToJSON ConnectEmbeddedBaseConfigClaim
