module StripeAPI.Types.CountrySpecVerificationFields where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data CountrySpecVerificationFields
instance Show CountrySpecVerificationFields
instance Eq CountrySpecVerificationFields
instance FromJSON CountrySpecVerificationFields
instance ToJSON CountrySpecVerificationFields
