module StripeAPI.Types.CountrySpecVerificationFieldDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data CountrySpecVerificationFieldDetails
instance Show CountrySpecVerificationFieldDetails
instance Eq CountrySpecVerificationFieldDetails
instance FromJSON CountrySpecVerificationFieldDetails
instance ToJSON CountrySpecVerificationFieldDetails
