module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction
instance Show CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction
data CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionPaymentIntent'Variants
instance Show CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionPaymentIntent'Variants
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionPaymentIntent'Variants
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionPaymentIntent'Variants
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionPaymentIntent'Variants
