module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction
instance Show CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction
