module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransfer where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransfer
instance Show CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransfer
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransfer
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransfer
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransfer
data CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferType'
instance Show CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferType'
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferType'
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferType'
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferType'
