module StripeAPI.Types.CustomerBalanceTransaction where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data CustomerBalanceTransaction 
instance Show CustomerBalanceTransaction 
instance Eq CustomerBalanceTransaction 
instance FromJSON CustomerBalanceTransaction 
instance ToJSON CustomerBalanceTransaction 
data CustomerBalanceTransactionCreditNote'Variants
instance Show CustomerBalanceTransactionCreditNote'Variants
instance Eq CustomerBalanceTransactionCreditNote'Variants
instance FromJSON CustomerBalanceTransactionCreditNote'Variants
instance ToJSON CustomerBalanceTransactionCreditNote'Variants
data CustomerBalanceTransactionCustomer'Variants
instance Show CustomerBalanceTransactionCustomer'Variants
instance Eq CustomerBalanceTransactionCustomer'Variants
instance FromJSON CustomerBalanceTransactionCustomer'Variants
instance ToJSON CustomerBalanceTransactionCustomer'Variants
data CustomerBalanceTransactionInvoice'Variants
instance Show CustomerBalanceTransactionInvoice'Variants
instance Eq CustomerBalanceTransactionInvoice'Variants
instance FromJSON CustomerBalanceTransactionInvoice'Variants
instance ToJSON CustomerBalanceTransactionInvoice'Variants
data CustomerBalanceTransactionObject'
instance Show CustomerBalanceTransactionObject'
instance Eq CustomerBalanceTransactionObject'
instance FromJSON CustomerBalanceTransactionObject'
instance ToJSON CustomerBalanceTransactionObject'
data CustomerBalanceTransactionType'
instance Show CustomerBalanceTransactionType'
instance Eq CustomerBalanceTransactionType'
instance FromJSON CustomerBalanceTransactionType'
instance ToJSON CustomerBalanceTransactionType'
