module StripeAPI.Types.CustomerBalanceTransaction where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CustomerBalanceTransaction
instance Show CustomerBalanceTransaction
instance Eq CustomerBalanceTransaction
instance FromJSON CustomerBalanceTransaction
instance ToJSON CustomerBalanceTransaction
data CustomerBalanceTransactionCreditNote'NonNullableVariants
instance Show CustomerBalanceTransactionCreditNote'NonNullableVariants
instance Eq CustomerBalanceTransactionCreditNote'NonNullableVariants
instance FromJSON CustomerBalanceTransactionCreditNote'NonNullableVariants
instance ToJSON CustomerBalanceTransactionCreditNote'NonNullableVariants
data CustomerBalanceTransactionCustomer'Variants
instance Show CustomerBalanceTransactionCustomer'Variants
instance Eq CustomerBalanceTransactionCustomer'Variants
instance FromJSON CustomerBalanceTransactionCustomer'Variants
instance ToJSON CustomerBalanceTransactionCustomer'Variants
data CustomerBalanceTransactionInvoice'NonNullableVariants
instance Show CustomerBalanceTransactionInvoice'NonNullableVariants
instance Eq CustomerBalanceTransactionInvoice'NonNullableVariants
instance FromJSON CustomerBalanceTransactionInvoice'NonNullableVariants
instance ToJSON CustomerBalanceTransactionInvoice'NonNullableVariants
data CustomerBalanceTransactionType'
instance Show CustomerBalanceTransactionType'
instance Eq CustomerBalanceTransactionType'
instance FromJSON CustomerBalanceTransactionType'
instance ToJSON CustomerBalanceTransactionType'
