module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
instance Show CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
data CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftBalanceTransaction'Variants
instance Show CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftBalanceTransaction'Variants
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftBalanceTransaction'Variants
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftBalanceTransaction'Variants
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftBalanceTransaction'Variants
data CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftLinkedTransaction'Variants
instance Show CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftLinkedTransaction'Variants
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftLinkedTransaction'Variants
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftLinkedTransaction'Variants
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftLinkedTransaction'Variants
