module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction
instance Show CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction
data CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionRefund'Variants
instance Show CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionRefund'Variants
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionRefund'Variants
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionRefund'Variants
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionRefund'Variants
