module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance
instance Show CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance
data CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceBalanceTransaction'Variants
instance Show CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceBalanceTransaction'Variants
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceBalanceTransaction'Variants
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceBalanceTransaction'Variants
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceBalanceTransaction'Variants
