module StripeAPI.Types.CustomerBalanceCustomerBalanceSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CustomerBalanceCustomerBalanceSettings
instance Show CustomerBalanceCustomerBalanceSettings
instance Eq CustomerBalanceCustomerBalanceSettings
instance FromJSON CustomerBalanceCustomerBalanceSettings
instance ToJSON CustomerBalanceCustomerBalanceSettings
data CustomerBalanceCustomerBalanceSettingsReconciliationMode'
instance Show CustomerBalanceCustomerBalanceSettingsReconciliationMode'
instance Eq CustomerBalanceCustomerBalanceSettingsReconciliationMode'
instance FromJSON CustomerBalanceCustomerBalanceSettingsReconciliationMode'
instance ToJSON CustomerBalanceCustomerBalanceSettingsReconciliationMode'
