module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction
instance Show CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction
data CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionPaymentIntent'Variants
instance Show CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionPaymentIntent'Variants
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionPaymentIntent'Variants
instance FromJSON CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionPaymentIntent'Variants
instance ToJSON CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionPaymentIntent'Variants
