module StripeAPI.Types.DisputeEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data DisputeEvidence
instance Show DisputeEvidence
instance Eq DisputeEvidence
instance FromJSON DisputeEvidence
instance ToJSON DisputeEvidence
data DisputeEvidenceCancellationPolicy'NonNullableVariants
instance Show DisputeEvidenceCancellationPolicy'NonNullableVariants
instance Eq DisputeEvidenceCancellationPolicy'NonNullableVariants
instance FromJSON DisputeEvidenceCancellationPolicy'NonNullableVariants
instance ToJSON DisputeEvidenceCancellationPolicy'NonNullableVariants
data DisputeEvidenceCustomerCommunication'NonNullableVariants
instance Show DisputeEvidenceCustomerCommunication'NonNullableVariants
instance Eq DisputeEvidenceCustomerCommunication'NonNullableVariants
instance FromJSON DisputeEvidenceCustomerCommunication'NonNullableVariants
instance ToJSON DisputeEvidenceCustomerCommunication'NonNullableVariants
data DisputeEvidenceCustomerSignature'NonNullableVariants
instance Show DisputeEvidenceCustomerSignature'NonNullableVariants
instance Eq DisputeEvidenceCustomerSignature'NonNullableVariants
instance FromJSON DisputeEvidenceCustomerSignature'NonNullableVariants
instance ToJSON DisputeEvidenceCustomerSignature'NonNullableVariants
data DisputeEvidenceDuplicateChargeDocumentation'NonNullableVariants
instance Show DisputeEvidenceDuplicateChargeDocumentation'NonNullableVariants
instance Eq DisputeEvidenceDuplicateChargeDocumentation'NonNullableVariants
instance FromJSON DisputeEvidenceDuplicateChargeDocumentation'NonNullableVariants
instance ToJSON DisputeEvidenceDuplicateChargeDocumentation'NonNullableVariants
data DisputeEvidenceReceipt'NonNullableVariants
instance Show DisputeEvidenceReceipt'NonNullableVariants
instance Eq DisputeEvidenceReceipt'NonNullableVariants
instance FromJSON DisputeEvidenceReceipt'NonNullableVariants
instance ToJSON DisputeEvidenceReceipt'NonNullableVariants
data DisputeEvidenceRefundPolicy'NonNullableVariants
instance Show DisputeEvidenceRefundPolicy'NonNullableVariants
instance Eq DisputeEvidenceRefundPolicy'NonNullableVariants
instance FromJSON DisputeEvidenceRefundPolicy'NonNullableVariants
instance ToJSON DisputeEvidenceRefundPolicy'NonNullableVariants
data DisputeEvidenceServiceDocumentation'NonNullableVariants
instance Show DisputeEvidenceServiceDocumentation'NonNullableVariants
instance Eq DisputeEvidenceServiceDocumentation'NonNullableVariants
instance FromJSON DisputeEvidenceServiceDocumentation'NonNullableVariants
instance ToJSON DisputeEvidenceServiceDocumentation'NonNullableVariants
data DisputeEvidenceShippingDocumentation'NonNullableVariants
instance Show DisputeEvidenceShippingDocumentation'NonNullableVariants
instance Eq DisputeEvidenceShippingDocumentation'NonNullableVariants
instance FromJSON DisputeEvidenceShippingDocumentation'NonNullableVariants
instance ToJSON DisputeEvidenceShippingDocumentation'NonNullableVariants
data DisputeEvidenceUncategorizedFile'NonNullableVariants
instance Show DisputeEvidenceUncategorizedFile'NonNullableVariants
instance Eq DisputeEvidenceUncategorizedFile'NonNullableVariants
instance FromJSON DisputeEvidenceUncategorizedFile'NonNullableVariants
instance ToJSON DisputeEvidenceUncategorizedFile'NonNullableVariants
