module StripeAPI.Types.DisputeEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data DisputeEvidence
instance Show DisputeEvidence
instance Eq DisputeEvidence
instance FromJSON DisputeEvidence
instance ToJSON DisputeEvidence
data DisputeEvidenceCancellationPolicy'Variants
instance Show DisputeEvidenceCancellationPolicy'Variants
instance Eq DisputeEvidenceCancellationPolicy'Variants
instance FromJSON DisputeEvidenceCancellationPolicy'Variants
instance ToJSON DisputeEvidenceCancellationPolicy'Variants
data DisputeEvidenceCustomerCommunication'Variants
instance Show DisputeEvidenceCustomerCommunication'Variants
instance Eq DisputeEvidenceCustomerCommunication'Variants
instance FromJSON DisputeEvidenceCustomerCommunication'Variants
instance ToJSON DisputeEvidenceCustomerCommunication'Variants
data DisputeEvidenceCustomerSignature'Variants
instance Show DisputeEvidenceCustomerSignature'Variants
instance Eq DisputeEvidenceCustomerSignature'Variants
instance FromJSON DisputeEvidenceCustomerSignature'Variants
instance ToJSON DisputeEvidenceCustomerSignature'Variants
data DisputeEvidenceDuplicateChargeDocumentation'Variants
instance Show DisputeEvidenceDuplicateChargeDocumentation'Variants
instance Eq DisputeEvidenceDuplicateChargeDocumentation'Variants
instance FromJSON DisputeEvidenceDuplicateChargeDocumentation'Variants
instance ToJSON DisputeEvidenceDuplicateChargeDocumentation'Variants
data DisputeEvidenceReceipt'Variants
instance Show DisputeEvidenceReceipt'Variants
instance Eq DisputeEvidenceReceipt'Variants
instance FromJSON DisputeEvidenceReceipt'Variants
instance ToJSON DisputeEvidenceReceipt'Variants
data DisputeEvidenceRefundPolicy'Variants
instance Show DisputeEvidenceRefundPolicy'Variants
instance Eq DisputeEvidenceRefundPolicy'Variants
instance FromJSON DisputeEvidenceRefundPolicy'Variants
instance ToJSON DisputeEvidenceRefundPolicy'Variants
data DisputeEvidenceServiceDocumentation'Variants
instance Show DisputeEvidenceServiceDocumentation'Variants
instance Eq DisputeEvidenceServiceDocumentation'Variants
instance FromJSON DisputeEvidenceServiceDocumentation'Variants
instance ToJSON DisputeEvidenceServiceDocumentation'Variants
data DisputeEvidenceShippingDocumentation'Variants
instance Show DisputeEvidenceShippingDocumentation'Variants
instance Eq DisputeEvidenceShippingDocumentation'Variants
instance FromJSON DisputeEvidenceShippingDocumentation'Variants
instance ToJSON DisputeEvidenceShippingDocumentation'Variants
data DisputeEvidenceUncategorizedFile'Variants
instance Show DisputeEvidenceUncategorizedFile'Variants
instance Eq DisputeEvidenceUncategorizedFile'Variants
instance FromJSON DisputeEvidenceUncategorizedFile'Variants
instance ToJSON DisputeEvidenceUncategorizedFile'Variants
