module StripeAPI.Types.FinancialConnections_AccountOwner where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data FinancialConnections'accountOwner
instance Show FinancialConnections'accountOwner
instance Eq FinancialConnections'accountOwner
instance FromJSON FinancialConnections'accountOwner
instance ToJSON FinancialConnections'accountOwner
