module StripeAPI.Types.FinancialReportingFinanceReportRunRunParameters where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data FinancialReportingFinanceReportRunRunParameters
instance Show FinancialReportingFinanceReportRunRunParameters
instance Eq FinancialReportingFinanceReportRunRunParameters
instance FromJSON FinancialReportingFinanceReportRunRunParameters
instance ToJSON FinancialReportingFinanceReportRunRunParameters
