module StripeAPI.Types.FundingInstructionsBankTransferFinancialAddress where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data FundingInstructionsBankTransferFinancialAddress
instance Show FundingInstructionsBankTransferFinancialAddress
instance Eq FundingInstructionsBankTransferFinancialAddress
instance FromJSON FundingInstructionsBankTransferFinancialAddress
instance ToJSON FundingInstructionsBankTransferFinancialAddress
data FundingInstructionsBankTransferFinancialAddressSupportedNetworks'
instance Show FundingInstructionsBankTransferFinancialAddressSupportedNetworks'
instance Eq FundingInstructionsBankTransferFinancialAddressSupportedNetworks'
instance FromJSON FundingInstructionsBankTransferFinancialAddressSupportedNetworks'
instance ToJSON FundingInstructionsBankTransferFinancialAddressSupportedNetworks'
data FundingInstructionsBankTransferFinancialAddressType'
instance Show FundingInstructionsBankTransferFinancialAddressType'
instance Eq FundingInstructionsBankTransferFinancialAddressType'
instance FromJSON FundingInstructionsBankTransferFinancialAddressType'
instance ToJSON FundingInstructionsBankTransferFinancialAddressType'
