module StripeAPI.Types.FundingInstructionsBankTransferSpeiRecord where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data FundingInstructionsBankTransferSpeiRecord
instance Show FundingInstructionsBankTransferSpeiRecord
instance Eq FundingInstructionsBankTransferSpeiRecord
instance FromJSON FundingInstructionsBankTransferSpeiRecord
instance ToJSON FundingInstructionsBankTransferSpeiRecord
