module StripeAPI.Types.GelatoVerificationSessionOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data GelatoVerificationSessionOptions
instance Show GelatoVerificationSessionOptions
instance Eq GelatoVerificationSessionOptions
instance FromJSON GelatoVerificationSessionOptions
instance ToJSON GelatoVerificationSessionOptions
