module StripeAPI.Types.GelatoDataDocumentReportDateOfBirth where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data GelatoDataDocumentReportDateOfBirth
instance Show GelatoDataDocumentReportDateOfBirth
instance Eq GelatoDataDocumentReportDateOfBirth
instance FromJSON GelatoDataDocumentReportDateOfBirth
instance ToJSON GelatoDataDocumentReportDateOfBirth
