module StripeAPI.Types.GelatoDataIdNumberReportDate where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data GelatoDataIdNumberReportDate
instance Show GelatoDataIdNumberReportDate
instance Eq GelatoDataIdNumberReportDate
instance FromJSON GelatoDataIdNumberReportDate
instance ToJSON GelatoDataIdNumberReportDate
