module StripeAPI.Types.GelatoDataDocumentReportExpirationDate where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data GelatoDataDocumentReportExpirationDate
instance Show GelatoDataDocumentReportExpirationDate
instance Eq GelatoDataDocumentReportExpirationDate
instance FromJSON GelatoDataDocumentReportExpirationDate
instance ToJSON GelatoDataDocumentReportExpirationDate
