module StripeAPI.Types.GelatoDataDocumentReportIssuedDate where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data GelatoDataDocumentReportIssuedDate
instance Show GelatoDataDocumentReportIssuedDate
instance Eq GelatoDataDocumentReportIssuedDate
instance FromJSON GelatoDataDocumentReportIssuedDate
instance ToJSON GelatoDataDocumentReportIssuedDate
