module StripeAPI.Types.InboundTransfersPaymentMethodDetailsUsBankAccount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InboundTransfersPaymentMethodDetailsUsBankAccount
instance Show InboundTransfersPaymentMethodDetailsUsBankAccount
instance Eq InboundTransfersPaymentMethodDetailsUsBankAccount
instance FromJSON InboundTransfersPaymentMethodDetailsUsBankAccount
instance ToJSON InboundTransfersPaymentMethodDetailsUsBankAccount
data InboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Show InboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Eq InboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance FromJSON InboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance ToJSON InboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
data InboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Show InboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Eq InboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance FromJSON InboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance ToJSON InboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
