module StripeAPI.Types.InvoicesStatusTransitions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicesStatusTransitions
instance Show InvoicesStatusTransitions
instance Eq InvoicesStatusTransitions
instance FromJSON InvoicesStatusTransitions
instance ToJSON InvoicesStatusTransitions
