module StripeAPI.Types.InvoicesLineItemsCreditedItems where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicesLineItemsCreditedItems
instance Show InvoicesLineItemsCreditedItems
instance Eq InvoicesLineItemsCreditedItems
instance FromJSON InvoicesLineItemsCreditedItems
instance ToJSON InvoicesLineItemsCreditedItems
