module StripeAPI.Types.InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer
instance Show InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer
instance Eq InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer
instance FromJSON InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer
instance ToJSON InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer
data InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransferCountry'
instance Show InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransferCountry'
instance Eq InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransferCountry'
instance FromJSON InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransferCountry'
instance ToJSON InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransferCountry'
