module StripeAPI.Types.InvoicesPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicesPaymentMethodOptions
instance Show InvoicesPaymentMethodOptions
instance Eq InvoicesPaymentMethodOptions
instance FromJSON InvoicesPaymentMethodOptions
instance ToJSON InvoicesPaymentMethodOptions
data InvoicesPaymentMethodOptionsAcssDebit'NonNullable
instance Show InvoicesPaymentMethodOptionsAcssDebit'NonNullable
instance Eq InvoicesPaymentMethodOptionsAcssDebit'NonNullable
instance FromJSON InvoicesPaymentMethodOptionsAcssDebit'NonNullable
instance ToJSON InvoicesPaymentMethodOptionsAcssDebit'NonNullable
data InvoicesPaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance Show InvoicesPaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance Eq InvoicesPaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance FromJSON InvoicesPaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance ToJSON InvoicesPaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
data InvoicesPaymentMethodOptionsBancontact'NonNullable
instance Show InvoicesPaymentMethodOptionsBancontact'NonNullable
instance Eq InvoicesPaymentMethodOptionsBancontact'NonNullable
instance FromJSON InvoicesPaymentMethodOptionsBancontact'NonNullable
instance ToJSON InvoicesPaymentMethodOptionsBancontact'NonNullable
data InvoicesPaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance Show InvoicesPaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance Eq InvoicesPaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance FromJSON InvoicesPaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance ToJSON InvoicesPaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
data InvoicesPaymentMethodOptionsCard'NonNullable
instance Show InvoicesPaymentMethodOptionsCard'NonNullable
instance Eq InvoicesPaymentMethodOptionsCard'NonNullable
instance FromJSON InvoicesPaymentMethodOptionsCard'NonNullable
instance ToJSON InvoicesPaymentMethodOptionsCard'NonNullable
data InvoicesPaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance Show InvoicesPaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance Eq InvoicesPaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance FromJSON InvoicesPaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance ToJSON InvoicesPaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
data InvoicesPaymentMethodOptionsCustomerBalance'NonNullable
instance Show InvoicesPaymentMethodOptionsCustomerBalance'NonNullable
instance Eq InvoicesPaymentMethodOptionsCustomerBalance'NonNullable
instance FromJSON InvoicesPaymentMethodOptionsCustomerBalance'NonNullable
instance ToJSON InvoicesPaymentMethodOptionsCustomerBalance'NonNullable
data InvoicesPaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance Show InvoicesPaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance Eq InvoicesPaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance FromJSON InvoicesPaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance ToJSON InvoicesPaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
data InvoicesPaymentMethodOptionsUsBankAccount'NonNullable
instance Show InvoicesPaymentMethodOptionsUsBankAccount'NonNullable
instance Eq InvoicesPaymentMethodOptionsUsBankAccount'NonNullable
instance FromJSON InvoicesPaymentMethodOptionsUsBankAccount'NonNullable
instance ToJSON InvoicesPaymentMethodOptionsUsBankAccount'NonNullable
data InvoicesPaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance Show InvoicesPaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance Eq InvoicesPaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance FromJSON InvoicesPaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance ToJSON InvoicesPaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
