module StripeAPI.Types.InvoicesPaymentSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicesPaymentSettings
instance Show InvoicesPaymentSettings
instance Eq InvoicesPaymentSettings
instance FromJSON InvoicesPaymentSettings
instance ToJSON InvoicesPaymentSettings
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullable
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullable
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
data InvoicesPaymentSettingsPaymentMethodTypes'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodTypes'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodTypes'NonNullable
instance FromJSON InvoicesPaymentSettingsPaymentMethodTypes'NonNullable
instance ToJSON InvoicesPaymentSettingsPaymentMethodTypes'NonNullable
