module StripeAPI.Types.InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions
instance Show InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions
instance Eq InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions
instance FromJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions
instance ToJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions
data InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPermissions'
instance Show InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPermissions'
instance Eq InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPermissions'
instance FromJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPermissions'
instance ToJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPermissions'
data InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPrefetch'NonNullable
instance Show InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPrefetch'NonNullable
instance Eq InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPrefetch'NonNullable
instance FromJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPrefetch'NonNullable
instance ToJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPrefetch'NonNullable
