module StripeAPI.Types.InvoicePaymentMethodOptionsUsBankAccount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsUsBankAccount
instance Show InvoicePaymentMethodOptionsUsBankAccount
instance Eq InvoicePaymentMethodOptionsUsBankAccount
instance FromJSON InvoicePaymentMethodOptionsUsBankAccount
instance ToJSON InvoicePaymentMethodOptionsUsBankAccount
data InvoicePaymentMethodOptionsUsBankAccountVerificationMethod'
instance Show InvoicePaymentMethodOptionsUsBankAccountVerificationMethod'
instance Eq InvoicePaymentMethodOptionsUsBankAccountVerificationMethod'
instance FromJSON InvoicePaymentMethodOptionsUsBankAccountVerificationMethod'
instance ToJSON InvoicePaymentMethodOptionsUsBankAccountVerificationMethod'
