module StripeAPI.Types.InvoicePaymentMethodOptionsCustomerBalance where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsCustomerBalance
instance Show InvoicePaymentMethodOptionsCustomerBalance
instance Eq InvoicePaymentMethodOptionsCustomerBalance
instance FromJSON InvoicePaymentMethodOptionsCustomerBalance
instance ToJSON InvoicePaymentMethodOptionsCustomerBalance
data InvoicePaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance Show InvoicePaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance Eq InvoicePaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance FromJSON InvoicePaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance ToJSON InvoicePaymentMethodOptionsCustomerBalanceFundingType'NonNullable
