module StripeAPI.Types.InvoicePaymentMethodOptionsCard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsCard
instance Show InvoicePaymentMethodOptionsCard
instance Eq InvoicePaymentMethodOptionsCard
instance FromJSON InvoicePaymentMethodOptionsCard
instance ToJSON InvoicePaymentMethodOptionsCard
data InvoicePaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Show InvoicePaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Eq InvoicePaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance FromJSON InvoicePaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance ToJSON InvoicePaymentMethodOptionsCardRequestThreeDSecure'NonNullable
