module StripeAPI.Types.InvoicePaymentMethodOptionsAcssDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsAcssDebit
instance Show InvoicePaymentMethodOptionsAcssDebit
instance Eq InvoicePaymentMethodOptionsAcssDebit
instance FromJSON InvoicePaymentMethodOptionsAcssDebit
instance ToJSON InvoicePaymentMethodOptionsAcssDebit
data InvoicePaymentMethodOptionsAcssDebitVerificationMethod'
instance Show InvoicePaymentMethodOptionsAcssDebitVerificationMethod'
instance Eq InvoicePaymentMethodOptionsAcssDebitVerificationMethod'
instance FromJSON InvoicePaymentMethodOptionsAcssDebitVerificationMethod'
instance ToJSON InvoicePaymentMethodOptionsAcssDebitVerificationMethod'
