module StripeAPI.Types.InvoiceSettingCustomerSetting where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoiceSettingCustomerSetting
instance Show InvoiceSettingCustomerSetting
instance Eq InvoiceSettingCustomerSetting
instance FromJSON InvoiceSettingCustomerSetting
instance ToJSON InvoiceSettingCustomerSetting
data InvoiceSettingCustomerSettingDefaultPaymentMethod'NonNullableVariants
instance Show InvoiceSettingCustomerSettingDefaultPaymentMethod'NonNullableVariants
instance Eq InvoiceSettingCustomerSettingDefaultPaymentMethod'NonNullableVariants
instance FromJSON InvoiceSettingCustomerSettingDefaultPaymentMethod'NonNullableVariants
instance ToJSON InvoiceSettingCustomerSettingDefaultPaymentMethod'NonNullableVariants
data InvoiceSettingCustomerSettingRenderingOptions'NonNullable
instance Show InvoiceSettingCustomerSettingRenderingOptions'NonNullable
instance Eq InvoiceSettingCustomerSettingRenderingOptions'NonNullable
instance FromJSON InvoiceSettingCustomerSettingRenderingOptions'NonNullable
instance ToJSON InvoiceSettingCustomerSettingRenderingOptions'NonNullable
