module StripeAPI.Types.InvoicePaymentMethodOptionsCustomerBalanceBankTransfer where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsCustomerBalanceBankTransfer
instance Show InvoicePaymentMethodOptionsCustomerBalanceBankTransfer
instance Eq InvoicePaymentMethodOptionsCustomerBalanceBankTransfer
instance FromJSON InvoicePaymentMethodOptionsCustomerBalanceBankTransfer
instance ToJSON InvoicePaymentMethodOptionsCustomerBalanceBankTransfer
