module StripeAPI.Types.InvoiceSettingQuoteSetting where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoiceSettingQuoteSetting
instance Show InvoiceSettingQuoteSetting
instance Eq InvoiceSettingQuoteSetting
instance FromJSON InvoiceSettingQuoteSetting
instance ToJSON InvoiceSettingQuoteSetting
