module StripeAPI.Types.InvoicesResourceLineItemsProrationDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicesResourceLineItemsProrationDetails
instance Show InvoicesResourceLineItemsProrationDetails
instance Eq InvoicesResourceLineItemsProrationDetails
instance FromJSON InvoicesResourceLineItemsProrationDetails
instance ToJSON InvoicesResourceLineItemsProrationDetails
data InvoicesResourceLineItemsProrationDetailsCreditedItems'NonNullable
instance Show InvoicesResourceLineItemsProrationDetailsCreditedItems'NonNullable
instance Eq InvoicesResourceLineItemsProrationDetailsCreditedItems'NonNullable
instance FromJSON InvoicesResourceLineItemsProrationDetailsCreditedItems'NonNullable
instance ToJSON InvoicesResourceLineItemsProrationDetailsCreditedItems'NonNullable
