module StripeAPI.Types.InvoicePaymentMethodOptionsBancontact where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsBancontact
instance Show InvoicePaymentMethodOptionsBancontact
instance Eq InvoicePaymentMethodOptionsBancontact
instance FromJSON InvoicePaymentMethodOptionsBancontact
instance ToJSON InvoicePaymentMethodOptionsBancontact
data InvoicePaymentMethodOptionsBancontactPreferredLanguage'
instance Show InvoicePaymentMethodOptionsBancontactPreferredLanguage'
instance Eq InvoicePaymentMethodOptionsBancontactPreferredLanguage'
instance FromJSON InvoicePaymentMethodOptionsBancontactPreferredLanguage'
instance ToJSON InvoicePaymentMethodOptionsBancontactPreferredLanguage'
