module StripeAPI.Types.InvoicesLineItemsProrationDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicesLineItemsProrationDetails
instance Show InvoicesLineItemsProrationDetails
instance Eq InvoicesLineItemsProrationDetails
instance FromJSON InvoicesLineItemsProrationDetails
instance ToJSON InvoicesLineItemsProrationDetails
data InvoicesLineItemsProrationDetailsCreditedItems'NonNullable
instance Show InvoicesLineItemsProrationDetailsCreditedItems'NonNullable
instance Eq InvoicesLineItemsProrationDetailsCreditedItems'NonNullable
instance FromJSON InvoicesLineItemsProrationDetailsCreditedItems'NonNullable
instance ToJSON InvoicesLineItemsProrationDetailsCreditedItems'NonNullable
