module StripeAPI.Types.InvoicePaymentMethodOptionsAcssDebitMandateOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsAcssDebitMandateOptions
instance Show InvoicePaymentMethodOptionsAcssDebitMandateOptions
instance Eq InvoicePaymentMethodOptionsAcssDebitMandateOptions
instance FromJSON InvoicePaymentMethodOptionsAcssDebitMandateOptions
instance ToJSON InvoicePaymentMethodOptionsAcssDebitMandateOptions
data InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'NonNullable
instance Show InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'NonNullable
instance Eq InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'NonNullable
instance FromJSON InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'NonNullable
instance ToJSON InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'NonNullable
