module StripeAPI.Types.InvoicesResourceLineItemsCreditedItems where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data InvoicesResourceLineItemsCreditedItems
instance Show InvoicesResourceLineItemsCreditedItems
instance Eq InvoicesResourceLineItemsCreditedItems
instance FromJSON InvoicesResourceLineItemsCreditedItems
instance ToJSON InvoicesResourceLineItemsCreditedItems
