module StripeAPI.Types.InvoicesPaymentSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data InvoicesPaymentSettings
instance Show InvoicesPaymentSettings
instance Eq InvoicesPaymentSettings
instance FromJSON InvoicesPaymentSettings
instance ToJSON InvoicesPaymentSettings
data InvoicesPaymentSettingsPaymentMethodOptions'
instance Show InvoicesPaymentSettingsPaymentMethodOptions'
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'
data InvoicesPaymentSettingsPaymentMethodOptions'Bancontact'
instance Show InvoicesPaymentSettingsPaymentMethodOptions'Bancontact'
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'Bancontact'
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'Bancontact'
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'Bancontact'
data InvoicesPaymentSettingsPaymentMethodOptions'Bancontact'PreferredLanguage'
instance Show InvoicesPaymentSettingsPaymentMethodOptions'Bancontact'PreferredLanguage'
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'Bancontact'PreferredLanguage'
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'Bancontact'PreferredLanguage'
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'Bancontact'PreferredLanguage'
data InvoicesPaymentSettingsPaymentMethodOptions'Card'
instance Show InvoicesPaymentSettingsPaymentMethodOptions'Card'
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'Card'
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'Card'
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'Card'
data InvoicesPaymentSettingsPaymentMethodOptions'Card'RequestThreeDSecure'
instance Show InvoicesPaymentSettingsPaymentMethodOptions'Card'RequestThreeDSecure'
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'Card'RequestThreeDSecure'
instance FromJSON InvoicesPaymentSettingsPaymentMethodOptions'Card'RequestThreeDSecure'
instance ToJSON InvoicesPaymentSettingsPaymentMethodOptions'Card'RequestThreeDSecure'
data InvoicesPaymentSettingsPaymentMethodTypes'
instance Show InvoicesPaymentSettingsPaymentMethodTypes'
instance Eq InvoicesPaymentSettingsPaymentMethodTypes'
instance FromJSON InvoicesPaymentSettingsPaymentMethodTypes'
instance ToJSON InvoicesPaymentSettingsPaymentMethodTypes'
