module StripeAPI.Types.IssuingAuthorizationVerificationData where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingAuthorizationVerificationData
instance Show IssuingAuthorizationVerificationData
instance Eq IssuingAuthorizationVerificationData
instance FromJSON IssuingAuthorizationVerificationData
instance ToJSON IssuingAuthorizationVerificationData
data IssuingAuthorizationVerificationDataAddressLine1Check'
instance Show IssuingAuthorizationVerificationDataAddressLine1Check'
instance Eq IssuingAuthorizationVerificationDataAddressLine1Check'
instance FromJSON IssuingAuthorizationVerificationDataAddressLine1Check'
instance ToJSON IssuingAuthorizationVerificationDataAddressLine1Check'
data IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
instance Show IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
instance Eq IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
instance FromJSON IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
instance ToJSON IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
data IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullable
instance Show IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullable
instance Eq IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullable
instance FromJSON IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullable
instance ToJSON IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullable
data IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableClaimedBy'
instance Show IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableClaimedBy'
instance Eq IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableClaimedBy'
instance FromJSON IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableClaimedBy'
instance ToJSON IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableClaimedBy'
data IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableType'
instance Show IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableType'
instance Eq IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableType'
instance FromJSON IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableType'
instance ToJSON IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableType'
data IssuingAuthorizationVerificationDataCvcCheck'
instance Show IssuingAuthorizationVerificationDataCvcCheck'
instance Eq IssuingAuthorizationVerificationDataCvcCheck'
instance FromJSON IssuingAuthorizationVerificationDataCvcCheck'
instance ToJSON IssuingAuthorizationVerificationDataCvcCheck'
data IssuingAuthorizationVerificationDataExpiryCheck'
instance Show IssuingAuthorizationVerificationDataExpiryCheck'
instance Eq IssuingAuthorizationVerificationDataExpiryCheck'
instance FromJSON IssuingAuthorizationVerificationDataExpiryCheck'
instance ToJSON IssuingAuthorizationVerificationDataExpiryCheck'
data IssuingAuthorizationVerificationDataThreeDSecure'NonNullable
instance Show IssuingAuthorizationVerificationDataThreeDSecure'NonNullable
instance Eq IssuingAuthorizationVerificationDataThreeDSecure'NonNullable
instance FromJSON IssuingAuthorizationVerificationDataThreeDSecure'NonNullable
instance ToJSON IssuingAuthorizationVerificationDataThreeDSecure'NonNullable
data IssuingAuthorizationVerificationDataThreeDSecure'NonNullableResult'
instance Show IssuingAuthorizationVerificationDataThreeDSecure'NonNullableResult'
instance Eq IssuingAuthorizationVerificationDataThreeDSecure'NonNullableResult'
instance FromJSON IssuingAuthorizationVerificationDataThreeDSecure'NonNullableResult'
instance ToJSON IssuingAuthorizationVerificationDataThreeDSecure'NonNullableResult'
