module StripeAPI.Types.IssuingCardholderRequirements where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingCardholderRequirements
instance Show IssuingCardholderRequirements
instance Eq IssuingCardholderRequirements
instance FromJSON IssuingCardholderRequirements
instance ToJSON IssuingCardholderRequirements
data IssuingCardholderRequirementsDisabledReason'NonNullable
instance Show IssuingCardholderRequirementsDisabledReason'NonNullable
instance Eq IssuingCardholderRequirementsDisabledReason'NonNullable
instance FromJSON IssuingCardholderRequirementsDisabledReason'NonNullable
instance ToJSON IssuingCardholderRequirementsDisabledReason'NonNullable
data IssuingCardholderRequirementsPastDue'NonNullable
instance Show IssuingCardholderRequirementsPastDue'NonNullable
instance Eq IssuingCardholderRequirementsPastDue'NonNullable
instance FromJSON IssuingCardholderRequirementsPastDue'NonNullable
instance ToJSON IssuingCardholderRequirementsPastDue'NonNullable
