module StripeAPI.Types.IssuingTransactionPurchaseDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingTransactionPurchaseDetails
instance Show IssuingTransactionPurchaseDetails
instance Eq IssuingTransactionPurchaseDetails
instance FromJSON IssuingTransactionPurchaseDetails
instance ToJSON IssuingTransactionPurchaseDetails
data IssuingTransactionPurchaseDetailsFlight'NonNullable
instance Show IssuingTransactionPurchaseDetailsFlight'NonNullable
instance Eq IssuingTransactionPurchaseDetailsFlight'NonNullable
instance FromJSON IssuingTransactionPurchaseDetailsFlight'NonNullable
instance ToJSON IssuingTransactionPurchaseDetailsFlight'NonNullable
data IssuingTransactionPurchaseDetailsFuel'NonNullable
instance Show IssuingTransactionPurchaseDetailsFuel'NonNullable
instance Eq IssuingTransactionPurchaseDetailsFuel'NonNullable
instance FromJSON IssuingTransactionPurchaseDetailsFuel'NonNullable
instance ToJSON IssuingTransactionPurchaseDetailsFuel'NonNullable
data IssuingTransactionPurchaseDetailsLodging'NonNullable
instance Show IssuingTransactionPurchaseDetailsLodging'NonNullable
instance Eq IssuingTransactionPurchaseDetailsLodging'NonNullable
instance FromJSON IssuingTransactionPurchaseDetailsLodging'NonNullable
instance ToJSON IssuingTransactionPurchaseDetailsLodging'NonNullable
