module StripeAPI.Types.IssuingCardholderAuthorizationControls where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingCardholderAuthorizationControls
instance Show IssuingCardholderAuthorizationControls
instance Eq IssuingCardholderAuthorizationControls
instance FromJSON IssuingCardholderAuthorizationControls
instance ToJSON IssuingCardholderAuthorizationControls
data IssuingCardholderAuthorizationControlsAllowedCategories'NonNullable
instance Show IssuingCardholderAuthorizationControlsAllowedCategories'NonNullable
instance Eq IssuingCardholderAuthorizationControlsAllowedCategories'NonNullable
instance FromJSON IssuingCardholderAuthorizationControlsAllowedCategories'NonNullable
instance ToJSON IssuingCardholderAuthorizationControlsAllowedCategories'NonNullable
data IssuingCardholderAuthorizationControlsBlockedCategories'NonNullable
instance Show IssuingCardholderAuthorizationControlsBlockedCategories'NonNullable
instance Eq IssuingCardholderAuthorizationControlsBlockedCategories'NonNullable
instance FromJSON IssuingCardholderAuthorizationControlsBlockedCategories'NonNullable
instance ToJSON IssuingCardholderAuthorizationControlsBlockedCategories'NonNullable
