module StripeAPI.Types.IssuingTransactionNetworkData where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingTransactionNetworkData
instance Show IssuingTransactionNetworkData
instance Eq IssuingTransactionNetworkData
instance FromJSON IssuingTransactionNetworkData
instance ToJSON IssuingTransactionNetworkData
