module StripeAPI.Types.IssuingDisputeDuplicateEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingDisputeDuplicateEvidence
instance Show IssuingDisputeDuplicateEvidence
instance Eq IssuingDisputeDuplicateEvidence
instance FromJSON IssuingDisputeDuplicateEvidence
instance ToJSON IssuingDisputeDuplicateEvidence
data IssuingDisputeDuplicateEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeDuplicateEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeDuplicateEvidenceAdditionalDocumentation'NonNullableVariants
instance FromJSON IssuingDisputeDuplicateEvidenceAdditionalDocumentation'NonNullableVariants
instance ToJSON IssuingDisputeDuplicateEvidenceAdditionalDocumentation'NonNullableVariants
data IssuingDisputeDuplicateEvidenceCardStatement'NonNullableVariants
instance Show IssuingDisputeDuplicateEvidenceCardStatement'NonNullableVariants
instance Eq IssuingDisputeDuplicateEvidenceCardStatement'NonNullableVariants
instance FromJSON IssuingDisputeDuplicateEvidenceCardStatement'NonNullableVariants
instance ToJSON IssuingDisputeDuplicateEvidenceCardStatement'NonNullableVariants
data IssuingDisputeDuplicateEvidenceCashReceipt'NonNullableVariants
instance Show IssuingDisputeDuplicateEvidenceCashReceipt'NonNullableVariants
instance Eq IssuingDisputeDuplicateEvidenceCashReceipt'NonNullableVariants
instance FromJSON IssuingDisputeDuplicateEvidenceCashReceipt'NonNullableVariants
instance ToJSON IssuingDisputeDuplicateEvidenceCashReceipt'NonNullableVariants
data IssuingDisputeDuplicateEvidenceCheckImage'NonNullableVariants
instance Show IssuingDisputeDuplicateEvidenceCheckImage'NonNullableVariants
instance Eq IssuingDisputeDuplicateEvidenceCheckImage'NonNullableVariants
instance FromJSON IssuingDisputeDuplicateEvidenceCheckImage'NonNullableVariants
instance ToJSON IssuingDisputeDuplicateEvidenceCheckImage'NonNullableVariants
