module StripeAPI.Types.IssuingAuthorizationRequest where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingAuthorizationRequest
instance Show IssuingAuthorizationRequest
instance Eq IssuingAuthorizationRequest
instance FromJSON IssuingAuthorizationRequest
instance ToJSON IssuingAuthorizationRequest
data IssuingAuthorizationRequestAmountDetails'
instance Show IssuingAuthorizationRequestAmountDetails'
instance Eq IssuingAuthorizationRequestAmountDetails'
instance FromJSON IssuingAuthorizationRequestAmountDetails'
instance ToJSON IssuingAuthorizationRequestAmountDetails'
data IssuingAuthorizationRequestReason'
instance Show IssuingAuthorizationRequestReason'
instance Eq IssuingAuthorizationRequestReason'
instance FromJSON IssuingAuthorizationRequestReason'
instance ToJSON IssuingAuthorizationRequestReason'
