module StripeAPI.Types.IssuingTransactionFlightData where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingTransactionFlightData
instance Show IssuingTransactionFlightData
instance Eq IssuingTransactionFlightData
instance FromJSON IssuingTransactionFlightData
instance ToJSON IssuingTransactionFlightData
