module StripeAPI.Types.IssuingDisputeServiceNotAsDescribedEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingDisputeServiceNotAsDescribedEvidence
instance Show IssuingDisputeServiceNotAsDescribedEvidence
instance Eq IssuingDisputeServiceNotAsDescribedEvidence
instance FromJSON IssuingDisputeServiceNotAsDescribedEvidence
instance ToJSON IssuingDisputeServiceNotAsDescribedEvidence
data IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance FromJSON IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance ToJSON IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
