module StripeAPI.Types.IssuingDisputeNotReceivedEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingDisputeNotReceivedEvidence
instance Show IssuingDisputeNotReceivedEvidence
instance Eq IssuingDisputeNotReceivedEvidence
instance FromJSON IssuingDisputeNotReceivedEvidence
instance ToJSON IssuingDisputeNotReceivedEvidence
data IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'NonNullableVariants
instance FromJSON IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'NonNullableVariants
instance ToJSON IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'NonNullableVariants
data IssuingDisputeNotReceivedEvidenceProductType'NonNullable
instance Show IssuingDisputeNotReceivedEvidenceProductType'NonNullable
instance Eq IssuingDisputeNotReceivedEvidenceProductType'NonNullable
instance FromJSON IssuingDisputeNotReceivedEvidenceProductType'NonNullable
instance ToJSON IssuingDisputeNotReceivedEvidenceProductType'NonNullable
