module StripeAPI.Types.IssuingCardholderAuthorizationControls where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingCardholderAuthorizationControls
instance Show IssuingCardholderAuthorizationControls
instance Eq IssuingCardholderAuthorizationControls
instance FromJSON IssuingCardholderAuthorizationControls
instance ToJSON IssuingCardholderAuthorizationControls
data IssuingCardholderAuthorizationControlsAllowedCategories'
instance Show IssuingCardholderAuthorizationControlsAllowedCategories'
instance Eq IssuingCardholderAuthorizationControlsAllowedCategories'
instance FromJSON IssuingCardholderAuthorizationControlsAllowedCategories'
instance ToJSON IssuingCardholderAuthorizationControlsAllowedCategories'
data IssuingCardholderAuthorizationControlsBlockedCategories'
instance Show IssuingCardholderAuthorizationControlsBlockedCategories'
instance Eq IssuingCardholderAuthorizationControlsBlockedCategories'
instance FromJSON IssuingCardholderAuthorizationControlsBlockedCategories'
instance ToJSON IssuingCardholderAuthorizationControlsBlockedCategories'
