module StripeAPI.Types.IssuingCardholderSpendingLimit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingCardholderSpendingLimit
instance Show IssuingCardholderSpendingLimit
instance Eq IssuingCardholderSpendingLimit
instance FromJSON IssuingCardholderSpendingLimit
instance ToJSON IssuingCardholderSpendingLimit
data IssuingCardholderSpendingLimitCategories'NonNullable
instance Show IssuingCardholderSpendingLimitCategories'NonNullable
instance Eq IssuingCardholderSpendingLimitCategories'NonNullable
instance FromJSON IssuingCardholderSpendingLimitCategories'NonNullable
instance ToJSON IssuingCardholderSpendingLimitCategories'NonNullable
data IssuingCardholderSpendingLimitInterval'
instance Show IssuingCardholderSpendingLimitInterval'
instance Eq IssuingCardholderSpendingLimitInterval'
instance FromJSON IssuingCardholderSpendingLimitInterval'
instance ToJSON IssuingCardholderSpendingLimitInterval'
