module StripeAPI.Types.IssuingAuthorizationViolatedAuthControl where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingAuthorizationViolatedAuthControl
instance Show IssuingAuthorizationViolatedAuthControl
instance Eq IssuingAuthorizationViolatedAuthControl
instance FromJSON IssuingAuthorizationViolatedAuthControl
instance ToJSON IssuingAuthorizationViolatedAuthControl
data IssuingAuthorizationViolatedAuthControlEntity'
instance Show IssuingAuthorizationViolatedAuthControlEntity'
instance Eq IssuingAuthorizationViolatedAuthControlEntity'
instance FromJSON IssuingAuthorizationViolatedAuthControlEntity'
instance ToJSON IssuingAuthorizationViolatedAuthControlEntity'
data IssuingAuthorizationViolatedAuthControlName'
instance Show IssuingAuthorizationViolatedAuthControlName'
instance Eq IssuingAuthorizationViolatedAuthControlName'
instance FromJSON IssuingAuthorizationViolatedAuthControlName'
instance ToJSON IssuingAuthorizationViolatedAuthControlName'
