module StripeAPI.Types.IssuingDisputeOtherEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingDisputeOtherEvidence
instance Show IssuingDisputeOtherEvidence
instance Eq IssuingDisputeOtherEvidence
instance FromJSON IssuingDisputeOtherEvidence
instance ToJSON IssuingDisputeOtherEvidence
data IssuingDisputeOtherEvidenceAdditionalDocumentation'Variants
instance Show IssuingDisputeOtherEvidenceAdditionalDocumentation'Variants
instance Eq IssuingDisputeOtherEvidenceAdditionalDocumentation'Variants
instance FromJSON IssuingDisputeOtherEvidenceAdditionalDocumentation'Variants
instance ToJSON IssuingDisputeOtherEvidenceAdditionalDocumentation'Variants
data IssuingDisputeOtherEvidenceProductType'
instance Show IssuingDisputeOtherEvidenceProductType'
instance Eq IssuingDisputeOtherEvidenceProductType'
instance FromJSON IssuingDisputeOtherEvidenceProductType'
instance ToJSON IssuingDisputeOtherEvidenceProductType'
