module StripeAPI.Types.IssuingCardAuthorizationControls where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingCardAuthorizationControls
instance Show IssuingCardAuthorizationControls
instance Eq IssuingCardAuthorizationControls
instance FromJSON IssuingCardAuthorizationControls
instance ToJSON IssuingCardAuthorizationControls
data IssuingCardAuthorizationControlsAllowedCategories'NonNullable
instance Show IssuingCardAuthorizationControlsAllowedCategories'NonNullable
instance Eq IssuingCardAuthorizationControlsAllowedCategories'NonNullable
instance FromJSON IssuingCardAuthorizationControlsAllowedCategories'NonNullable
instance ToJSON IssuingCardAuthorizationControlsAllowedCategories'NonNullable
data IssuingCardAuthorizationControlsBlockedCategories'NonNullable
instance Show IssuingCardAuthorizationControlsBlockedCategories'NonNullable
instance Eq IssuingCardAuthorizationControlsBlockedCategories'NonNullable
instance FromJSON IssuingCardAuthorizationControlsBlockedCategories'NonNullable
instance ToJSON IssuingCardAuthorizationControlsBlockedCategories'NonNullable
