module StripeAPI.Types.IssuingDisputeCanceledEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingDisputeCanceledEvidence
instance Show IssuingDisputeCanceledEvidence
instance Eq IssuingDisputeCanceledEvidence
instance FromJSON IssuingDisputeCanceledEvidence
instance ToJSON IssuingDisputeCanceledEvidence
data IssuingDisputeCanceledEvidenceAdditionalDocumentation'Variants
instance Show IssuingDisputeCanceledEvidenceAdditionalDocumentation'Variants
instance Eq IssuingDisputeCanceledEvidenceAdditionalDocumentation'Variants
instance FromJSON IssuingDisputeCanceledEvidenceAdditionalDocumentation'Variants
instance ToJSON IssuingDisputeCanceledEvidenceAdditionalDocumentation'Variants
data IssuingDisputeCanceledEvidenceProductType'
instance Show IssuingDisputeCanceledEvidenceProductType'
instance Eq IssuingDisputeCanceledEvidenceProductType'
instance FromJSON IssuingDisputeCanceledEvidenceProductType'
instance ToJSON IssuingDisputeCanceledEvidenceProductType'
data IssuingDisputeCanceledEvidenceReturnStatus'
instance Show IssuingDisputeCanceledEvidenceReturnStatus'
instance Eq IssuingDisputeCanceledEvidenceReturnStatus'
instance FromJSON IssuingDisputeCanceledEvidenceReturnStatus'
instance ToJSON IssuingDisputeCanceledEvidenceReturnStatus'
