module StripeAPI.Types.IssuingAuthorizationVerificationData where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingAuthorizationVerificationData 
instance Show IssuingAuthorizationVerificationData 
instance Eq IssuingAuthorizationVerificationData 
instance FromJSON IssuingAuthorizationVerificationData 
instance ToJSON IssuingAuthorizationVerificationData 
data IssuingAuthorizationVerificationDataAddressLine1Check'
instance Show IssuingAuthorizationVerificationDataAddressLine1Check'
instance Eq IssuingAuthorizationVerificationDataAddressLine1Check'
instance FromJSON IssuingAuthorizationVerificationDataAddressLine1Check'
instance ToJSON IssuingAuthorizationVerificationDataAddressLine1Check'
data IssuingAuthorizationVerificationDataAddressZipCheck'
instance Show IssuingAuthorizationVerificationDataAddressZipCheck'
instance Eq IssuingAuthorizationVerificationDataAddressZipCheck'
instance FromJSON IssuingAuthorizationVerificationDataAddressZipCheck'
instance ToJSON IssuingAuthorizationVerificationDataAddressZipCheck'
data IssuingAuthorizationVerificationDataAuthentication'
instance Show IssuingAuthorizationVerificationDataAuthentication'
instance Eq IssuingAuthorizationVerificationDataAuthentication'
instance FromJSON IssuingAuthorizationVerificationDataAuthentication'
instance ToJSON IssuingAuthorizationVerificationDataAuthentication'
data IssuingAuthorizationVerificationDataCvcCheck'
instance Show IssuingAuthorizationVerificationDataCvcCheck'
instance Eq IssuingAuthorizationVerificationDataCvcCheck'
instance FromJSON IssuingAuthorizationVerificationDataCvcCheck'
instance ToJSON IssuingAuthorizationVerificationDataCvcCheck'
