module StripeAPI.Types.IssuingAuthorizationVerificationData where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingAuthorizationVerificationData
instance Show IssuingAuthorizationVerificationData
instance Eq IssuingAuthorizationVerificationData
instance FromJSON IssuingAuthorizationVerificationData
instance ToJSON IssuingAuthorizationVerificationData
data IssuingAuthorizationVerificationDataAddressLine1Check'
instance Show IssuingAuthorizationVerificationDataAddressLine1Check'
instance Eq IssuingAuthorizationVerificationDataAddressLine1Check'
instance FromJSON IssuingAuthorizationVerificationDataAddressLine1Check'
instance ToJSON IssuingAuthorizationVerificationDataAddressLine1Check'
data IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
instance Show IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
instance Eq IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
instance FromJSON IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
instance ToJSON IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
data IssuingAuthorizationVerificationDataCvcCheck'
instance Show IssuingAuthorizationVerificationDataCvcCheck'
instance Eq IssuingAuthorizationVerificationDataCvcCheck'
instance FromJSON IssuingAuthorizationVerificationDataCvcCheck'
instance ToJSON IssuingAuthorizationVerificationDataCvcCheck'
data IssuingAuthorizationVerificationDataExpiryCheck'
instance Show IssuingAuthorizationVerificationDataExpiryCheck'
instance Eq IssuingAuthorizationVerificationDataExpiryCheck'
instance FromJSON IssuingAuthorizationVerificationDataExpiryCheck'
instance ToJSON IssuingAuthorizationVerificationDataExpiryCheck'
