module StripeAPI.Types.IssuingCardholderIndividual where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingCardholderIndividual 
instance Show IssuingCardholderIndividual 
instance Eq IssuingCardholderIndividual 
instance FromJSON IssuingCardholderIndividual 
instance ToJSON IssuingCardholderIndividual 
data IssuingCardholderIndividualDob' 
instance Show IssuingCardholderIndividualDob' 
instance Eq IssuingCardholderIndividualDob' 
instance FromJSON IssuingCardholderIndividualDob' 
instance ToJSON IssuingCardholderIndividualDob' 
data IssuingCardholderIndividualVerification' 
instance Show IssuingCardholderIndividualVerification' 
instance Eq IssuingCardholderIndividualVerification' 
instance FromJSON IssuingCardholderIndividualVerification' 
instance ToJSON IssuingCardholderIndividualVerification' 
data IssuingCardholderIndividualVerification'Document' 
instance Show IssuingCardholderIndividualVerification'Document' 
instance Eq IssuingCardholderIndividualVerification'Document' 
instance FromJSON IssuingCardholderIndividualVerification'Document' 
instance ToJSON IssuingCardholderIndividualVerification'Document' 
data IssuingCardholderIndividualVerification'Document'Back'Variants
instance Show IssuingCardholderIndividualVerification'Document'Back'Variants
instance Eq IssuingCardholderIndividualVerification'Document'Back'Variants
instance FromJSON IssuingCardholderIndividualVerification'Document'Back'Variants
instance ToJSON IssuingCardholderIndividualVerification'Document'Back'Variants
data IssuingCardholderIndividualVerification'Document'Front'Variants
instance Show IssuingCardholderIndividualVerification'Document'Front'Variants
instance Eq IssuingCardholderIndividualVerification'Document'Front'Variants
instance FromJSON IssuingCardholderIndividualVerification'Document'Front'Variants
instance ToJSON IssuingCardholderIndividualVerification'Document'Front'Variants
