module StripeAPI.Types.IssuingTransactionTreasury where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingTransactionTreasury
instance Show IssuingTransactionTreasury
instance Eq IssuingTransactionTreasury
instance FromJSON IssuingTransactionTreasury
instance ToJSON IssuingTransactionTreasury
