module StripeAPI.Types.IssuingDisputeServiceNotAsDescribedEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingDisputeServiceNotAsDescribedEvidence
instance Show IssuingDisputeServiceNotAsDescribedEvidence
instance Eq IssuingDisputeServiceNotAsDescribedEvidence
instance FromJSON IssuingDisputeServiceNotAsDescribedEvidence
instance ToJSON IssuingDisputeServiceNotAsDescribedEvidence
data IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'Variants
instance Show IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'Variants
instance Eq IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'Variants
instance FromJSON IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'Variants
instance ToJSON IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'Variants
