module StripeAPI.Types.IssuingDisputeFraudulentEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingDisputeFraudulentEvidence
instance Show IssuingDisputeFraudulentEvidence
instance Eq IssuingDisputeFraudulentEvidence
instance FromJSON IssuingDisputeFraudulentEvidence
instance ToJSON IssuingDisputeFraudulentEvidence
data IssuingDisputeFraudulentEvidenceAdditionalDocumentation'Variants
instance Show IssuingDisputeFraudulentEvidenceAdditionalDocumentation'Variants
instance Eq IssuingDisputeFraudulentEvidenceAdditionalDocumentation'Variants
instance FromJSON IssuingDisputeFraudulentEvidenceAdditionalDocumentation'Variants
instance ToJSON IssuingDisputeFraudulentEvidenceAdditionalDocumentation'Variants
