module StripeAPI.Types.IssuingDisputeCanceledEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingDisputeCanceledEvidence
instance Show IssuingDisputeCanceledEvidence
instance Eq IssuingDisputeCanceledEvidence
instance FromJSON IssuingDisputeCanceledEvidence
instance ToJSON IssuingDisputeCanceledEvidence
data IssuingDisputeCanceledEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeCanceledEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeCanceledEvidenceAdditionalDocumentation'NonNullableVariants
instance FromJSON IssuingDisputeCanceledEvidenceAdditionalDocumentation'NonNullableVariants
instance ToJSON IssuingDisputeCanceledEvidenceAdditionalDocumentation'NonNullableVariants
data IssuingDisputeCanceledEvidenceProductType'NonNullable
instance Show IssuingDisputeCanceledEvidenceProductType'NonNullable
instance Eq IssuingDisputeCanceledEvidenceProductType'NonNullable
instance FromJSON IssuingDisputeCanceledEvidenceProductType'NonNullable
instance ToJSON IssuingDisputeCanceledEvidenceProductType'NonNullable
data IssuingDisputeCanceledEvidenceReturnStatus'NonNullable
instance Show IssuingDisputeCanceledEvidenceReturnStatus'NonNullable
instance Eq IssuingDisputeCanceledEvidenceReturnStatus'NonNullable
instance FromJSON IssuingDisputeCanceledEvidenceReturnStatus'NonNullable
instance ToJSON IssuingDisputeCanceledEvidenceReturnStatus'NonNullable
