module StripeAPI.Types.IssuingDisputeProductNotReceivedEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingDisputeProductNotReceivedEvidence 
instance Show IssuingDisputeProductNotReceivedEvidence 
instance Eq IssuingDisputeProductNotReceivedEvidence 
instance FromJSON IssuingDisputeProductNotReceivedEvidence 
instance ToJSON IssuingDisputeProductNotReceivedEvidence 
data IssuingDisputeProductNotReceivedEvidenceUncategorizedFile'Variants
instance Show IssuingDisputeProductNotReceivedEvidenceUncategorizedFile'Variants
instance Eq IssuingDisputeProductNotReceivedEvidenceUncategorizedFile'Variants
instance FromJSON IssuingDisputeProductNotReceivedEvidenceUncategorizedFile'Variants
instance ToJSON IssuingDisputeProductNotReceivedEvidenceUncategorizedFile'Variants
