module StripeAPI.Types.IssuingCardShippingCustoms where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingCardShippingCustoms
instance Show IssuingCardShippingCustoms
instance Eq IssuingCardShippingCustoms
instance FromJSON IssuingCardShippingCustoms
instance ToJSON IssuingCardShippingCustoms
