module StripeAPI.Types.IssuingCardholderIndividualDob where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingCardholderIndividualDob
instance Show IssuingCardholderIndividualDob
instance Eq IssuingCardholderIndividualDob
instance FromJSON IssuingCardholderIndividualDob
instance ToJSON IssuingCardholderIndividualDob
