module StripeAPI.Types.IssuingDisputeFraudulentEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingDisputeFraudulentEvidence
instance Show IssuingDisputeFraudulentEvidence
instance Eq IssuingDisputeFraudulentEvidence
instance FromJSON IssuingDisputeFraudulentEvidence
instance ToJSON IssuingDisputeFraudulentEvidence
data IssuingDisputeFraudulentEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeFraudulentEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeFraudulentEvidenceAdditionalDocumentation'NonNullableVariants
instance FromJSON IssuingDisputeFraudulentEvidenceAdditionalDocumentation'NonNullableVariants
instance ToJSON IssuingDisputeFraudulentEvidenceAdditionalDocumentation'NonNullableVariants
