module StripeAPI.Types.IssuingCardSpendingLimit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingCardSpendingLimit
instance Show IssuingCardSpendingLimit
instance Eq IssuingCardSpendingLimit
instance FromJSON IssuingCardSpendingLimit
instance ToJSON IssuingCardSpendingLimit
data IssuingCardSpendingLimitCategories'NonNullable
instance Show IssuingCardSpendingLimitCategories'NonNullable
instance Eq IssuingCardSpendingLimitCategories'NonNullable
instance FromJSON IssuingCardSpendingLimitCategories'NonNullable
instance ToJSON IssuingCardSpendingLimitCategories'NonNullable
data IssuingCardSpendingLimitInterval'
instance Show IssuingCardSpendingLimitInterval'
instance Eq IssuingCardSpendingLimitInterval'
instance FromJSON IssuingCardSpendingLimitInterval'
instance ToJSON IssuingCardSpendingLimitInterval'
