module StripeAPI.Types.IssuingCardholderVerification where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingCardholderVerification
instance Show IssuingCardholderVerification
instance Eq IssuingCardholderVerification
instance FromJSON IssuingCardholderVerification
instance ToJSON IssuingCardholderVerification
data IssuingCardholderVerificationDocument'NonNullable
instance Show IssuingCardholderVerificationDocument'NonNullable
instance Eq IssuingCardholderVerificationDocument'NonNullable
instance FromJSON IssuingCardholderVerificationDocument'NonNullable
instance ToJSON IssuingCardholderVerificationDocument'NonNullable
data IssuingCardholderVerificationDocument'NonNullableBack'NonNullableVariants
instance Show IssuingCardholderVerificationDocument'NonNullableBack'NonNullableVariants
instance Eq IssuingCardholderVerificationDocument'NonNullableBack'NonNullableVariants
instance FromJSON IssuingCardholderVerificationDocument'NonNullableBack'NonNullableVariants
instance ToJSON IssuingCardholderVerificationDocument'NonNullableBack'NonNullableVariants
data IssuingCardholderVerificationDocument'NonNullableFront'NonNullableVariants
instance Show IssuingCardholderVerificationDocument'NonNullableFront'NonNullableVariants
instance Eq IssuingCardholderVerificationDocument'NonNullableFront'NonNullableVariants
instance FromJSON IssuingCardholderVerificationDocument'NonNullableFront'NonNullableVariants
instance ToJSON IssuingCardholderVerificationDocument'NonNullableFront'NonNullableVariants
