module StripeAPI.Types.IssuingDisputeMerchandiseNotAsDescribedEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingDisputeMerchandiseNotAsDescribedEvidence
instance Show IssuingDisputeMerchandiseNotAsDescribedEvidence
instance Eq IssuingDisputeMerchandiseNotAsDescribedEvidence
instance FromJSON IssuingDisputeMerchandiseNotAsDescribedEvidence
instance ToJSON IssuingDisputeMerchandiseNotAsDescribedEvidence
data IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance FromJSON IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance ToJSON IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
data IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'NonNullable
instance Show IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'NonNullable
instance Eq IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'NonNullable
instance FromJSON IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'NonNullable
instance ToJSON IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'NonNullable
