module StripeAPI.Types.IssuingDisputeMerchandiseNotAsDescribedEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingDisputeMerchandiseNotAsDescribedEvidence
instance Show IssuingDisputeMerchandiseNotAsDescribedEvidence
instance Eq IssuingDisputeMerchandiseNotAsDescribedEvidence
instance FromJSON IssuingDisputeMerchandiseNotAsDescribedEvidence
instance ToJSON IssuingDisputeMerchandiseNotAsDescribedEvidence
data IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'Variants
instance Show IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'Variants
instance Eq IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'Variants
instance FromJSON IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'Variants
instance ToJSON IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'Variants
data IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'
instance Show IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'
instance Eq IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'
instance FromJSON IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'
instance ToJSON IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'
