module StripeAPI.Types.IssuingNetworkTokenWalletProvider where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingNetworkTokenWalletProvider
instance Show IssuingNetworkTokenWalletProvider
instance Eq IssuingNetworkTokenWalletProvider
instance FromJSON IssuingNetworkTokenWalletProvider
instance ToJSON IssuingNetworkTokenWalletProvider
data IssuingNetworkTokenWalletProviderCardNumberSource'
instance Show IssuingNetworkTokenWalletProviderCardNumberSource'
instance Eq IssuingNetworkTokenWalletProviderCardNumberSource'
instance FromJSON IssuingNetworkTokenWalletProviderCardNumberSource'
instance ToJSON IssuingNetworkTokenWalletProviderCardNumberSource'
data IssuingNetworkTokenWalletProviderReasonCodes'
instance Show IssuingNetworkTokenWalletProviderReasonCodes'
instance Eq IssuingNetworkTokenWalletProviderReasonCodes'
instance FromJSON IssuingNetworkTokenWalletProviderReasonCodes'
instance ToJSON IssuingNetworkTokenWalletProviderReasonCodes'
data IssuingNetworkTokenWalletProviderSuggestedDecision'
instance Show IssuingNetworkTokenWalletProviderSuggestedDecision'
instance Eq IssuingNetworkTokenWalletProviderSuggestedDecision'
instance FromJSON IssuingNetworkTokenWalletProviderSuggestedDecision'
instance ToJSON IssuingNetworkTokenWalletProviderSuggestedDecision'
