module StripeAPI.Types.IssuingAuthorizationAuthenticationExemption where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingAuthorizationAuthenticationExemption
instance Show IssuingAuthorizationAuthenticationExemption
instance Eq IssuingAuthorizationAuthenticationExemption
instance FromJSON IssuingAuthorizationAuthenticationExemption
instance ToJSON IssuingAuthorizationAuthenticationExemption
data IssuingAuthorizationAuthenticationExemptionClaimedBy'
instance Show IssuingAuthorizationAuthenticationExemptionClaimedBy'
instance Eq IssuingAuthorizationAuthenticationExemptionClaimedBy'
instance FromJSON IssuingAuthorizationAuthenticationExemptionClaimedBy'
instance ToJSON IssuingAuthorizationAuthenticationExemptionClaimedBy'
data IssuingAuthorizationAuthenticationExemptionType'
instance Show IssuingAuthorizationAuthenticationExemptionType'
instance Eq IssuingAuthorizationAuthenticationExemptionType'
instance FromJSON IssuingAuthorizationAuthenticationExemptionType'
instance ToJSON IssuingAuthorizationAuthenticationExemptionType'
