module StripeAPI.Types.IssuingCardAuthorizationControls where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingCardAuthorizationControls
instance Show IssuingCardAuthorizationControls
instance Eq IssuingCardAuthorizationControls
instance FromJSON IssuingCardAuthorizationControls
instance ToJSON IssuingCardAuthorizationControls
data IssuingCardAuthorizationControlsAllowedCategories'
instance Show IssuingCardAuthorizationControlsAllowedCategories'
instance Eq IssuingCardAuthorizationControlsAllowedCategories'
instance FromJSON IssuingCardAuthorizationControlsAllowedCategories'
instance ToJSON IssuingCardAuthorizationControlsAllowedCategories'
data IssuingCardAuthorizationControlsBlockedCategories'
instance Show IssuingCardAuthorizationControlsBlockedCategories'
instance Eq IssuingCardAuthorizationControlsBlockedCategories'
instance FromJSON IssuingCardAuthorizationControlsBlockedCategories'
instance ToJSON IssuingCardAuthorizationControlsBlockedCategories'
