module StripeAPI.Types.IssuingAuthorizationPendingRequest where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingAuthorizationPendingRequest
instance Show IssuingAuthorizationPendingRequest
instance Eq IssuingAuthorizationPendingRequest
instance FromJSON IssuingAuthorizationPendingRequest
instance ToJSON IssuingAuthorizationPendingRequest
data IssuingAuthorizationPendingRequestAmountDetails'NonNullable
instance Show IssuingAuthorizationPendingRequestAmountDetails'NonNullable
instance Eq IssuingAuthorizationPendingRequestAmountDetails'NonNullable
instance FromJSON IssuingAuthorizationPendingRequestAmountDetails'NonNullable
instance ToJSON IssuingAuthorizationPendingRequestAmountDetails'NonNullable
