module StripeAPI.Types.IssuingCardholderIndividual where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingCardholderIndividual
instance Show IssuingCardholderIndividual
instance Eq IssuingCardholderIndividual
instance FromJSON IssuingCardholderIndividual
instance ToJSON IssuingCardholderIndividual
data IssuingCardholderIndividualCardIssuing'NonNullable
instance Show IssuingCardholderIndividualCardIssuing'NonNullable
instance Eq IssuingCardholderIndividualCardIssuing'NonNullable
instance FromJSON IssuingCardholderIndividualCardIssuing'NonNullable
instance ToJSON IssuingCardholderIndividualCardIssuing'NonNullable
data IssuingCardholderIndividualCardIssuing'NonNullableUserTermsAcceptance'NonNullable
instance Show IssuingCardholderIndividualCardIssuing'NonNullableUserTermsAcceptance'NonNullable
instance Eq IssuingCardholderIndividualCardIssuing'NonNullableUserTermsAcceptance'NonNullable
instance FromJSON IssuingCardholderIndividualCardIssuing'NonNullableUserTermsAcceptance'NonNullable
instance ToJSON IssuingCardholderIndividualCardIssuing'NonNullableUserTermsAcceptance'NonNullable
data IssuingCardholderIndividualDob'NonNullable
instance Show IssuingCardholderIndividualDob'NonNullable
instance Eq IssuingCardholderIndividualDob'NonNullable
instance FromJSON IssuingCardholderIndividualDob'NonNullable
instance ToJSON IssuingCardholderIndividualDob'NonNullable
data IssuingCardholderIndividualVerification'NonNullable
instance Show IssuingCardholderIndividualVerification'NonNullable
instance Eq IssuingCardholderIndividualVerification'NonNullable
instance FromJSON IssuingCardholderIndividualVerification'NonNullable
instance ToJSON IssuingCardholderIndividualVerification'NonNullable
data IssuingCardholderIndividualVerification'NonNullableDocument'NonNullable
instance Show IssuingCardholderIndividualVerification'NonNullableDocument'NonNullable
instance Eq IssuingCardholderIndividualVerification'NonNullableDocument'NonNullable
instance FromJSON IssuingCardholderIndividualVerification'NonNullableDocument'NonNullable
instance ToJSON IssuingCardholderIndividualVerification'NonNullableDocument'NonNullable
data IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableBack'NonNullableVariants
instance Show IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableBack'NonNullableVariants
instance Eq IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableBack'NonNullableVariants
instance FromJSON IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableBack'NonNullableVariants
instance ToJSON IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableBack'NonNullableVariants
data IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableFront'NonNullableVariants
instance Show IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableFront'NonNullableVariants
instance Eq IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableFront'NonNullableVariants
instance FromJSON IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableFront'NonNullableVariants
instance ToJSON IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableFront'NonNullableVariants
