module StripeAPI.Types.IssuingDisputeOtherEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data IssuingDisputeOtherEvidence
instance Show IssuingDisputeOtherEvidence
instance Eq IssuingDisputeOtherEvidence
instance FromJSON IssuingDisputeOtherEvidence
instance ToJSON IssuingDisputeOtherEvidence
data IssuingDisputeOtherEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeOtherEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeOtherEvidenceAdditionalDocumentation'NonNullableVariants
instance FromJSON IssuingDisputeOtherEvidenceAdditionalDocumentation'NonNullableVariants
instance ToJSON IssuingDisputeOtherEvidenceAdditionalDocumentation'NonNullableVariants
data IssuingDisputeOtherEvidenceProductType'NonNullable
instance Show IssuingDisputeOtherEvidenceProductType'NonNullable
instance Eq IssuingDisputeOtherEvidenceProductType'NonNullable
instance FromJSON IssuingDisputeOtherEvidenceProductType'NonNullable
instance ToJSON IssuingDisputeOtherEvidenceProductType'NonNullable
