module StripeAPI.Types.IssuingDisputeDuplicateEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingDisputeDuplicateEvidence
instance Show IssuingDisputeDuplicateEvidence
instance Eq IssuingDisputeDuplicateEvidence
instance FromJSON IssuingDisputeDuplicateEvidence
instance ToJSON IssuingDisputeDuplicateEvidence
data IssuingDisputeDuplicateEvidenceAdditionalDocumentation'Variants
instance Show IssuingDisputeDuplicateEvidenceAdditionalDocumentation'Variants
instance Eq IssuingDisputeDuplicateEvidenceAdditionalDocumentation'Variants
instance FromJSON IssuingDisputeDuplicateEvidenceAdditionalDocumentation'Variants
instance ToJSON IssuingDisputeDuplicateEvidenceAdditionalDocumentation'Variants
data IssuingDisputeDuplicateEvidenceCardStatement'Variants
instance Show IssuingDisputeDuplicateEvidenceCardStatement'Variants
instance Eq IssuingDisputeDuplicateEvidenceCardStatement'Variants
instance FromJSON IssuingDisputeDuplicateEvidenceCardStatement'Variants
instance ToJSON IssuingDisputeDuplicateEvidenceCardStatement'Variants
data IssuingDisputeDuplicateEvidenceCashReceipt'Variants
instance Show IssuingDisputeDuplicateEvidenceCashReceipt'Variants
instance Eq IssuingDisputeDuplicateEvidenceCashReceipt'Variants
instance FromJSON IssuingDisputeDuplicateEvidenceCashReceipt'Variants
instance ToJSON IssuingDisputeDuplicateEvidenceCashReceipt'Variants
data IssuingDisputeDuplicateEvidenceCheckImage'Variants
instance Show IssuingDisputeDuplicateEvidenceCheckImage'Variants
instance Eq IssuingDisputeDuplicateEvidenceCheckImage'Variants
instance FromJSON IssuingDisputeDuplicateEvidenceCheckImage'Variants
instance ToJSON IssuingDisputeDuplicateEvidenceCheckImage'Variants
