module StripeAPI.Types.IssuingDisputeNotReceivedEvidence where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data IssuingDisputeNotReceivedEvidence
instance Show IssuingDisputeNotReceivedEvidence
instance Eq IssuingDisputeNotReceivedEvidence
instance FromJSON IssuingDisputeNotReceivedEvidence
instance ToJSON IssuingDisputeNotReceivedEvidence
data IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'Variants
instance Show IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'Variants
instance Eq IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'Variants
instance FromJSON IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'Variants
instance ToJSON IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'Variants
data IssuingDisputeNotReceivedEvidenceProductType'
instance Show IssuingDisputeNotReceivedEvidenceProductType'
instance Eq IssuingDisputeNotReceivedEvidenceProductType'
instance FromJSON IssuingDisputeNotReceivedEvidenceProductType'
instance ToJSON IssuingDisputeNotReceivedEvidenceProductType'
