module StripeAPI.Types.LegalEntityPersonVerificationDocument where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data LegalEntityPersonVerificationDocument 
instance Show LegalEntityPersonVerificationDocument 
instance Eq LegalEntityPersonVerificationDocument 
instance FromJSON LegalEntityPersonVerificationDocument 
instance ToJSON LegalEntityPersonVerificationDocument 
data LegalEntityPersonVerificationDocumentBack'Variants
instance Show LegalEntityPersonVerificationDocumentBack'Variants
instance Eq LegalEntityPersonVerificationDocumentBack'Variants
instance FromJSON LegalEntityPersonVerificationDocumentBack'Variants
instance ToJSON LegalEntityPersonVerificationDocumentBack'Variants
data LegalEntityPersonVerificationDocumentFront'Variants
instance Show LegalEntityPersonVerificationDocumentFront'Variants
instance Eq LegalEntityPersonVerificationDocumentFront'Variants
instance FromJSON LegalEntityPersonVerificationDocumentFront'Variants
instance ToJSON LegalEntityPersonVerificationDocumentFront'Variants
