module StripeAPI.Types.LegalEntityPersonVerification where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data LegalEntityPersonVerification
instance Show LegalEntityPersonVerification
instance Eq LegalEntityPersonVerification
instance FromJSON LegalEntityPersonVerification
instance ToJSON LegalEntityPersonVerification
data LegalEntityPersonVerificationAdditionalDocument'NonNullable
instance Show LegalEntityPersonVerificationAdditionalDocument'NonNullable
instance Eq LegalEntityPersonVerificationAdditionalDocument'NonNullable
instance FromJSON LegalEntityPersonVerificationAdditionalDocument'NonNullable
instance ToJSON LegalEntityPersonVerificationAdditionalDocument'NonNullable
data LegalEntityPersonVerificationAdditionalDocument'NonNullableBack'NonNullableVariants
instance Show LegalEntityPersonVerificationAdditionalDocument'NonNullableBack'NonNullableVariants
instance Eq LegalEntityPersonVerificationAdditionalDocument'NonNullableBack'NonNullableVariants
instance FromJSON LegalEntityPersonVerificationAdditionalDocument'NonNullableBack'NonNullableVariants
instance ToJSON LegalEntityPersonVerificationAdditionalDocument'NonNullableBack'NonNullableVariants
data LegalEntityPersonVerificationAdditionalDocument'NonNullableFront'NonNullableVariants
instance Show LegalEntityPersonVerificationAdditionalDocument'NonNullableFront'NonNullableVariants
instance Eq LegalEntityPersonVerificationAdditionalDocument'NonNullableFront'NonNullableVariants
instance FromJSON LegalEntityPersonVerificationAdditionalDocument'NonNullableFront'NonNullableVariants
instance ToJSON LegalEntityPersonVerificationAdditionalDocument'NonNullableFront'NonNullableVariants
