module StripeAPI.Types.LegalEntityCompanyVerification where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data LegalEntityCompanyVerification 
instance Show LegalEntityCompanyVerification 
instance Eq LegalEntityCompanyVerification 
instance FromJSON LegalEntityCompanyVerification 
instance ToJSON LegalEntityCompanyVerification 
