module StripeAPI.Types.LegalEntityPersonVerificationDocument where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data LegalEntityPersonVerificationDocument
instance Show LegalEntityPersonVerificationDocument
instance Eq LegalEntityPersonVerificationDocument
instance FromJSON LegalEntityPersonVerificationDocument
instance ToJSON LegalEntityPersonVerificationDocument
data LegalEntityPersonVerificationDocumentBack'NonNullableVariants
instance Show LegalEntityPersonVerificationDocumentBack'NonNullableVariants
instance Eq LegalEntityPersonVerificationDocumentBack'NonNullableVariants
instance FromJSON LegalEntityPersonVerificationDocumentBack'NonNullableVariants
instance ToJSON LegalEntityPersonVerificationDocumentBack'NonNullableVariants
data LegalEntityPersonVerificationDocumentFront'NonNullableVariants
instance Show LegalEntityPersonVerificationDocumentFront'NonNullableVariants
instance Eq LegalEntityPersonVerificationDocumentFront'NonNullableVariants
instance FromJSON LegalEntityPersonVerificationDocumentFront'NonNullableVariants
instance ToJSON LegalEntityPersonVerificationDocumentFront'NonNullableVariants
