module StripeAPI.Types.LegalEntityPersonVerification where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data LegalEntityPersonVerification 
instance Show LegalEntityPersonVerification 
instance Eq LegalEntityPersonVerification 
instance FromJSON LegalEntityPersonVerification 
instance ToJSON LegalEntityPersonVerification 
data LegalEntityPersonVerificationAdditionalDocument' 
instance Show LegalEntityPersonVerificationAdditionalDocument' 
instance Eq LegalEntityPersonVerificationAdditionalDocument' 
instance FromJSON LegalEntityPersonVerificationAdditionalDocument' 
instance ToJSON LegalEntityPersonVerificationAdditionalDocument' 
data LegalEntityPersonVerificationAdditionalDocument'Back'Variants
instance Show LegalEntityPersonVerificationAdditionalDocument'Back'Variants
instance Eq LegalEntityPersonVerificationAdditionalDocument'Back'Variants
instance FromJSON LegalEntityPersonVerificationAdditionalDocument'Back'Variants
instance ToJSON LegalEntityPersonVerificationAdditionalDocument'Back'Variants
data LegalEntityPersonVerificationAdditionalDocument'Front'Variants
instance Show LegalEntityPersonVerificationAdditionalDocument'Front'Variants
instance Eq LegalEntityPersonVerificationAdditionalDocument'Front'Variants
instance FromJSON LegalEntityPersonVerificationAdditionalDocument'Front'Variants
instance ToJSON LegalEntityPersonVerificationAdditionalDocument'Front'Variants
