module StripeAPI.Types.LegalEntityCompanyVerificationDocument where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data LegalEntityCompanyVerificationDocument
instance Show LegalEntityCompanyVerificationDocument
instance Eq LegalEntityCompanyVerificationDocument
instance FromJSON LegalEntityCompanyVerificationDocument
instance ToJSON LegalEntityCompanyVerificationDocument
data LegalEntityCompanyVerificationDocumentBack'NonNullableVariants
instance Show LegalEntityCompanyVerificationDocumentBack'NonNullableVariants
instance Eq LegalEntityCompanyVerificationDocumentBack'NonNullableVariants
instance FromJSON LegalEntityCompanyVerificationDocumentBack'NonNullableVariants
instance ToJSON LegalEntityCompanyVerificationDocumentBack'NonNullableVariants
data LegalEntityCompanyVerificationDocumentFront'NonNullableVariants
instance Show LegalEntityCompanyVerificationDocumentFront'NonNullableVariants
instance Eq LegalEntityCompanyVerificationDocumentFront'NonNullableVariants
instance FromJSON LegalEntityCompanyVerificationDocumentFront'NonNullableVariants
instance ToJSON LegalEntityCompanyVerificationDocumentFront'NonNullableVariants
