module StripeAPI.Types.LegalEntityCompanyVerificationDocument where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data LegalEntityCompanyVerificationDocument
instance Show LegalEntityCompanyVerificationDocument
instance Eq LegalEntityCompanyVerificationDocument
instance FromJSON LegalEntityCompanyVerificationDocument
instance ToJSON LegalEntityCompanyVerificationDocument
data LegalEntityCompanyVerificationDocumentBack'Variants
instance Show LegalEntityCompanyVerificationDocumentBack'Variants
instance Eq LegalEntityCompanyVerificationDocumentBack'Variants
instance FromJSON LegalEntityCompanyVerificationDocumentBack'Variants
instance ToJSON LegalEntityCompanyVerificationDocumentBack'Variants
data LegalEntityCompanyVerificationDocumentFront'Variants
instance Show LegalEntityCompanyVerificationDocumentFront'Variants
instance Eq LegalEntityCompanyVerificationDocumentFront'Variants
instance FromJSON LegalEntityCompanyVerificationDocumentFront'Variants
instance ToJSON LegalEntityCompanyVerificationDocumentFront'Variants
