module StripeAPI.Types.LineItemsDiscountAmount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data LineItemsDiscountAmount
instance Show LineItemsDiscountAmount
instance Eq LineItemsDiscountAmount
instance FromJSON LineItemsDiscountAmount
instance ToJSON LineItemsDiscountAmount
