{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema MandateSepaDebit
module StripeAPI.Types.MandateSepaDebit where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.mandate_sepa_debit@ in the specification.
data MandateSepaDebit = MandateSepaDebit
  { -- | reference: The unique reference of the mandate.
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    mandateSepaDebitReference :: Data.Text.Internal.Text,
    -- | url: The URL of the mandate. This URL generally contains sensitive information about the customer and should be shared with them exclusively.
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    mandateSepaDebitUrl :: Data.Text.Internal.Text
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON MandateSepaDebit where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["reference" Data.Aeson.Types.ToJSON..= mandateSepaDebitReference obj] : ["url" Data.Aeson.Types.ToJSON..= mandateSepaDebitUrl obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["reference" Data.Aeson.Types.ToJSON..= mandateSepaDebitReference obj] : ["url" Data.Aeson.Types.ToJSON..= mandateSepaDebitUrl obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON MandateSepaDebit where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "MandateSepaDebit" (\obj -> (GHC.Base.pure MandateSepaDebit GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "reference")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "url"))

-- | Create a new 'MandateSepaDebit' with all required fields.
mkMandateSepaDebit ::
  -- | 'mandateSepaDebitReference'
  Data.Text.Internal.Text ->
  -- | 'mandateSepaDebitUrl'
  Data.Text.Internal.Text ->
  MandateSepaDebit
mkMandateSepaDebit mandateSepaDebitReference mandateSepaDebitUrl =
  MandateSepaDebit
    { mandateSepaDebitReference = mandateSepaDebitReference,
      mandateSepaDebitUrl = mandateSepaDebitUrl
    }
