module StripeAPI.Types.OrdersV2ResourcePaymentSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data OrdersV2ResourcePaymentSettings
instance Show OrdersV2ResourcePaymentSettings
instance Eq OrdersV2ResourcePaymentSettings
instance FromJSON OrdersV2ResourcePaymentSettings
instance ToJSON OrdersV2ResourcePaymentSettings
data OrdersV2ResourcePaymentSettingsAutomaticPaymentMethods'NonNullable
instance Show OrdersV2ResourcePaymentSettingsAutomaticPaymentMethods'NonNullable
instance Eq OrdersV2ResourcePaymentSettingsAutomaticPaymentMethods'NonNullable
instance FromJSON OrdersV2ResourcePaymentSettingsAutomaticPaymentMethods'NonNullable
instance ToJSON OrdersV2ResourcePaymentSettingsAutomaticPaymentMethods'NonNullable
data OrdersV2ResourcePaymentSettingsPaymentMethodOptions'NonNullable
instance Show OrdersV2ResourcePaymentSettingsPaymentMethodOptions'NonNullable
instance Eq OrdersV2ResourcePaymentSettingsPaymentMethodOptions'NonNullable
instance FromJSON OrdersV2ResourcePaymentSettingsPaymentMethodOptions'NonNullable
instance ToJSON OrdersV2ResourcePaymentSettingsPaymentMethodOptions'NonNullable
data OrdersV2ResourcePaymentSettingsPaymentMethodTypes'NonNullable
instance Show OrdersV2ResourcePaymentSettingsPaymentMethodTypes'NonNullable
instance Eq OrdersV2ResourcePaymentSettingsPaymentMethodTypes'NonNullable
instance FromJSON OrdersV2ResourcePaymentSettingsPaymentMethodTypes'NonNullable
instance ToJSON OrdersV2ResourcePaymentSettingsPaymentMethodTypes'NonNullable
data OrdersV2ResourcePaymentSettingsTransferData'NonNullable
instance Show OrdersV2ResourcePaymentSettingsTransferData'NonNullable
instance Eq OrdersV2ResourcePaymentSettingsTransferData'NonNullable
instance FromJSON OrdersV2ResourcePaymentSettingsTransferData'NonNullable
instance ToJSON OrdersV2ResourcePaymentSettingsTransferData'NonNullable
data OrdersV2ResourcePaymentSettingsTransferData'NonNullableDestination'Variants
instance Show OrdersV2ResourcePaymentSettingsTransferData'NonNullableDestination'Variants
instance Eq OrdersV2ResourcePaymentSettingsTransferData'NonNullableDestination'Variants
instance FromJSON OrdersV2ResourcePaymentSettingsTransferData'NonNullableDestination'Variants
instance ToJSON OrdersV2ResourcePaymentSettingsTransferData'NonNullableDestination'Variants
