module StripeAPI.Types.OrdersPaymentMethodOptionsAfterpayClearpay where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data OrdersPaymentMethodOptionsAfterpayClearpay
instance Show OrdersPaymentMethodOptionsAfterpayClearpay
instance Eq OrdersPaymentMethodOptionsAfterpayClearpay
instance FromJSON OrdersPaymentMethodOptionsAfterpayClearpay
instance ToJSON OrdersPaymentMethodOptionsAfterpayClearpay
data OrdersPaymentMethodOptionsAfterpayClearpayCaptureMethod'
instance Show OrdersPaymentMethodOptionsAfterpayClearpayCaptureMethod'
instance Eq OrdersPaymentMethodOptionsAfterpayClearpayCaptureMethod'
instance FromJSON OrdersPaymentMethodOptionsAfterpayClearpayCaptureMethod'
instance ToJSON OrdersPaymentMethodOptionsAfterpayClearpayCaptureMethod'
data OrdersPaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
instance Show OrdersPaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
instance Eq OrdersPaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
instance FromJSON OrdersPaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
instance ToJSON OrdersPaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
