module StripeAPI.Types.OrdersV2ResourcePaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data OrdersV2ResourcePaymentMethodOptions
instance Show OrdersV2ResourcePaymentMethodOptions
instance Eq OrdersV2ResourcePaymentMethodOptions
instance FromJSON OrdersV2ResourcePaymentMethodOptions
instance ToJSON OrdersV2ResourcePaymentMethodOptions
