module StripeAPI.Types.OrdersV2ResourceAutomaticPaymentMethods where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data OrdersV2ResourceAutomaticPaymentMethods
instance Show OrdersV2ResourceAutomaticPaymentMethods
instance Eq OrdersV2ResourceAutomaticPaymentMethods
instance FromJSON OrdersV2ResourceAutomaticPaymentMethods
instance ToJSON OrdersV2ResourceAutomaticPaymentMethods
