module StripeAPI.Types.OrdersV2ResourceTaxDetailsResourceTaxId where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data OrdersV2ResourceTaxDetailsResourceTaxId
instance Show OrdersV2ResourceTaxDetailsResourceTaxId
instance Eq OrdersV2ResourceTaxDetailsResourceTaxId
instance FromJSON OrdersV2ResourceTaxDetailsResourceTaxId
instance ToJSON OrdersV2ResourceTaxDetailsResourceTaxId
data OrdersV2ResourceTaxDetailsResourceTaxIdType'
instance Show OrdersV2ResourceTaxDetailsResourceTaxIdType'
instance Eq OrdersV2ResourceTaxDetailsResourceTaxIdType'
instance FromJSON OrdersV2ResourceTaxDetailsResourceTaxIdType'
instance ToJSON OrdersV2ResourceTaxDetailsResourceTaxIdType'
