module StripeAPI.Types.OrdersV2ResourceCardPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data OrdersV2ResourceCardPaymentMethodOptions
instance Show OrdersV2ResourceCardPaymentMethodOptions
instance Eq OrdersV2ResourceCardPaymentMethodOptions
instance FromJSON OrdersV2ResourceCardPaymentMethodOptions
instance ToJSON OrdersV2ResourceCardPaymentMethodOptions
data OrdersV2ResourceCardPaymentMethodOptionsCaptureMethod'
instance Show OrdersV2ResourceCardPaymentMethodOptionsCaptureMethod'
instance Eq OrdersV2ResourceCardPaymentMethodOptionsCaptureMethod'
instance FromJSON OrdersV2ResourceCardPaymentMethodOptionsCaptureMethod'
instance ToJSON OrdersV2ResourceCardPaymentMethodOptionsCaptureMethod'
data OrdersV2ResourceCardPaymentMethodOptionsSetupFutureUsage'
instance Show OrdersV2ResourceCardPaymentMethodOptionsSetupFutureUsage'
instance Eq OrdersV2ResourceCardPaymentMethodOptionsSetupFutureUsage'
instance FromJSON OrdersV2ResourceCardPaymentMethodOptionsSetupFutureUsage'
instance ToJSON OrdersV2ResourceCardPaymentMethodOptionsSetupFutureUsage'
