module StripeAPI.Types.OutboundTransfersPaymentMethodDetailsUsBankAccount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data OutboundTransfersPaymentMethodDetailsUsBankAccount
instance Show OutboundTransfersPaymentMethodDetailsUsBankAccount
instance Eq OutboundTransfersPaymentMethodDetailsUsBankAccount
instance FromJSON OutboundTransfersPaymentMethodDetailsUsBankAccount
instance ToJSON OutboundTransfersPaymentMethodDetailsUsBankAccount
data OutboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Show OutboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Eq OutboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance FromJSON OutboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance ToJSON OutboundTransfersPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
data OutboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Show OutboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Eq OutboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance FromJSON OutboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance ToJSON OutboundTransfersPaymentMethodDetailsUsBankAccountAccountType'NonNullable
data OutboundTransfersPaymentMethodDetailsUsBankAccountNetwork'
instance Show OutboundTransfersPaymentMethodDetailsUsBankAccountNetwork'
instance Eq OutboundTransfersPaymentMethodDetailsUsBankAccountNetwork'
instance FromJSON OutboundTransfersPaymentMethodDetailsUsBankAccountNetwork'
instance ToJSON OutboundTransfersPaymentMethodDetailsUsBankAccountNetwork'
