module StripeAPI.Types.OutboundPaymentsResourceTreasuryOutboundPaymentResourceEndUserDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data OutboundPaymentsResourceTreasuryOutboundPaymentResourceEndUserDetails
instance Show OutboundPaymentsResourceTreasuryOutboundPaymentResourceEndUserDetails
instance Eq OutboundPaymentsResourceTreasuryOutboundPaymentResourceEndUserDetails
instance FromJSON OutboundPaymentsResourceTreasuryOutboundPaymentResourceEndUserDetails
instance ToJSON OutboundPaymentsResourceTreasuryOutboundPaymentResourceEndUserDetails
