module StripeAPI.Types.OutboundPaymentsPaymentMethodDetailsUsBankAccount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data OutboundPaymentsPaymentMethodDetailsUsBankAccount
instance Show OutboundPaymentsPaymentMethodDetailsUsBankAccount
instance Eq OutboundPaymentsPaymentMethodDetailsUsBankAccount
instance FromJSON OutboundPaymentsPaymentMethodDetailsUsBankAccount
instance ToJSON OutboundPaymentsPaymentMethodDetailsUsBankAccount
data OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Show OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Eq OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance FromJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance ToJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
data OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Show OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Eq OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance FromJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance ToJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountAccountType'NonNullable
data OutboundPaymentsPaymentMethodDetailsUsBankAccountNetwork'
instance Show OutboundPaymentsPaymentMethodDetailsUsBankAccountNetwork'
instance Eq OutboundPaymentsPaymentMethodDetailsUsBankAccountNetwork'
instance FromJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountNetwork'
instance ToJSON OutboundPaymentsPaymentMethodDetailsUsBankAccountNetwork'
