module StripeAPI.Types.OutboundPaymentsResourceTreasuryReturnedStatus where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data OutboundPaymentsResourceTreasuryReturnedStatus
instance Show OutboundPaymentsResourceTreasuryReturnedStatus
instance Eq OutboundPaymentsResourceTreasuryReturnedStatus
instance FromJSON OutboundPaymentsResourceTreasuryReturnedStatus
instance ToJSON OutboundPaymentsResourceTreasuryReturnedStatus
data OutboundPaymentsResourceTreasuryReturnedStatusCode'
instance Show OutboundPaymentsResourceTreasuryReturnedStatusCode'
instance Eq OutboundPaymentsResourceTreasuryReturnedStatusCode'
instance FromJSON OutboundPaymentsResourceTreasuryReturnedStatusCode'
instance ToJSON OutboundPaymentsResourceTreasuryReturnedStatusCode'
data OutboundPaymentsResourceTreasuryReturnedStatusTransaction'Variants
instance Show OutboundPaymentsResourceTreasuryReturnedStatusTransaction'Variants
instance Eq OutboundPaymentsResourceTreasuryReturnedStatusTransaction'Variants
instance FromJSON OutboundPaymentsResourceTreasuryReturnedStatusTransaction'Variants
instance ToJSON OutboundPaymentsResourceTreasuryReturnedStatusTransaction'Variants
