module StripeAPI.Types.OutboundPaymentsResourceTreasuryOutboundPaymentResourceStatusTransitions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data OutboundPaymentsResourceTreasuryOutboundPaymentResourceStatusTransitions
instance Show OutboundPaymentsResourceTreasuryOutboundPaymentResourceStatusTransitions
instance Eq OutboundPaymentsResourceTreasuryOutboundPaymentResourceStatusTransitions
instance FromJSON OutboundPaymentsResourceTreasuryOutboundPaymentResourceStatusTransitions
instance ToJSON OutboundPaymentsResourceTreasuryOutboundPaymentResourceStatusTransitions
