module StripeAPI.Types.OutboundTransfersPaymentMethodDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data OutboundTransfersPaymentMethodDetails
instance Show OutboundTransfersPaymentMethodDetails
instance Eq OutboundTransfersPaymentMethodDetails
instance FromJSON OutboundTransfersPaymentMethodDetails
instance ToJSON OutboundTransfersPaymentMethodDetails
