module StripeAPI.Types.PaymentFlowsAutomaticPaymentMethodsPaymentIntent where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentFlowsAutomaticPaymentMethodsPaymentIntent
instance Show PaymentFlowsAutomaticPaymentMethodsPaymentIntent
instance Eq PaymentFlowsAutomaticPaymentMethodsPaymentIntent
instance FromJSON PaymentFlowsAutomaticPaymentMethodsPaymentIntent
instance ToJSON PaymentFlowsAutomaticPaymentMethodsPaymentIntent
data PaymentFlowsAutomaticPaymentMethodsPaymentIntentAllowRedirects'
instance Show PaymentFlowsAutomaticPaymentMethodsPaymentIntentAllowRedirects'
instance Eq PaymentFlowsAutomaticPaymentMethodsPaymentIntentAllowRedirects'
instance FromJSON PaymentFlowsAutomaticPaymentMethodsPaymentIntentAllowRedirects'
instance ToJSON PaymentFlowsAutomaticPaymentMethodsPaymentIntentAllowRedirects'
