module StripeAPI.Types.PaymentPagesPaymentPageResourcesShippingAddressCollection where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentPagesPaymentPageResourcesShippingAddressCollection
instance Show PaymentPagesPaymentPageResourcesShippingAddressCollection
instance Eq PaymentPagesPaymentPageResourcesShippingAddressCollection
instance FromJSON PaymentPagesPaymentPageResourcesShippingAddressCollection
instance ToJSON PaymentPagesPaymentPageResourcesShippingAddressCollection
data PaymentPagesPaymentPageResourcesShippingAddressCollectionAllowedCountries'
instance Show PaymentPagesPaymentPageResourcesShippingAddressCollectionAllowedCountries'
instance Eq PaymentPagesPaymentPageResourcesShippingAddressCollectionAllowedCountries'
instance FromJSON PaymentPagesPaymentPageResourcesShippingAddressCollectionAllowedCountries'
instance ToJSON PaymentPagesPaymentPageResourcesShippingAddressCollectionAllowedCountries'
