module StripeAPI.Types.PaymentIntentNextActionCashappQrCode where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionCashappQrCode
instance Show PaymentIntentNextActionCashappQrCode
instance Eq PaymentIntentNextActionCashappQrCode
instance FromJSON PaymentIntentNextActionCashappQrCode
instance ToJSON PaymentIntentNextActionCashappQrCode
