module StripeAPI.Types.PaymentMethodDetailsCardPresentReceipt where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsCardPresentReceipt
instance Show PaymentMethodDetailsCardPresentReceipt
instance Eq PaymentMethodDetailsCardPresentReceipt
instance FromJSON PaymentMethodDetailsCardPresentReceipt
instance ToJSON PaymentMethodDetailsCardPresentReceipt
data PaymentMethodDetailsCardPresentReceiptAccountType'
instance Show PaymentMethodDetailsCardPresentReceiptAccountType'
instance Eq PaymentMethodDetailsCardPresentReceiptAccountType'
instance FromJSON PaymentMethodDetailsCardPresentReceiptAccountType'
instance ToJSON PaymentMethodDetailsCardPresentReceiptAccountType'
