module StripeAPI.Types.PaymentMethodDetailsCardPresent where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsCardPresent
instance Show PaymentMethodDetailsCardPresent
instance Eq PaymentMethodDetailsCardPresent
instance FromJSON PaymentMethodDetailsCardPresent
instance ToJSON PaymentMethodDetailsCardPresent
data PaymentMethodDetailsCardPresentOffline'NonNullable
instance Show PaymentMethodDetailsCardPresentOffline'NonNullable
instance Eq PaymentMethodDetailsCardPresentOffline'NonNullable
instance FromJSON PaymentMethodDetailsCardPresentOffline'NonNullable
instance ToJSON PaymentMethodDetailsCardPresentOffline'NonNullable
data PaymentMethodDetailsCardPresentReadMethod'NonNullable
instance Show PaymentMethodDetailsCardPresentReadMethod'NonNullable
instance Eq PaymentMethodDetailsCardPresentReadMethod'NonNullable
instance FromJSON PaymentMethodDetailsCardPresentReadMethod'NonNullable
instance ToJSON PaymentMethodDetailsCardPresentReadMethod'NonNullable
data PaymentMethodDetailsCardPresentReceipt'NonNullable
instance Show PaymentMethodDetailsCardPresentReceipt'NonNullable
instance Eq PaymentMethodDetailsCardPresentReceipt'NonNullable
instance FromJSON PaymentMethodDetailsCardPresentReceipt'NonNullable
instance ToJSON PaymentMethodDetailsCardPresentReceipt'NonNullable
data PaymentMethodDetailsCardPresentReceipt'NonNullableAccountType'
instance Show PaymentMethodDetailsCardPresentReceipt'NonNullableAccountType'
instance Eq PaymentMethodDetailsCardPresentReceipt'NonNullableAccountType'
instance FromJSON PaymentMethodDetailsCardPresentReceipt'NonNullableAccountType'
instance ToJSON PaymentMethodDetailsCardPresentReceipt'NonNullableAccountType'
