module StripeAPI.Types.PaymentMethodDetailsInteracPresent where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodDetailsInteracPresent
instance Show PaymentMethodDetailsInteracPresent
instance Eq PaymentMethodDetailsInteracPresent
instance FromJSON PaymentMethodDetailsInteracPresent
instance ToJSON PaymentMethodDetailsInteracPresent
data PaymentMethodDetailsInteracPresentReadMethod'
instance Show PaymentMethodDetailsInteracPresentReadMethod'
instance Eq PaymentMethodDetailsInteracPresentReadMethod'
instance FromJSON PaymentMethodDetailsInteracPresentReadMethod'
instance ToJSON PaymentMethodDetailsInteracPresentReadMethod'
data PaymentMethodDetailsInteracPresentReceipt'
instance Show PaymentMethodDetailsInteracPresentReceipt'
instance Eq PaymentMethodDetailsInteracPresentReceipt'
instance FromJSON PaymentMethodDetailsInteracPresentReceipt'
instance ToJSON PaymentMethodDetailsInteracPresentReceipt'
data PaymentMethodDetailsInteracPresentReceipt'AccountType'
instance Show PaymentMethodDetailsInteracPresentReceipt'AccountType'
instance Eq PaymentMethodDetailsInteracPresentReceipt'AccountType'
instance FromJSON PaymentMethodDetailsInteracPresentReceipt'AccountType'
instance ToJSON PaymentMethodDetailsInteracPresentReceipt'AccountType'
