module StripeAPI.Types.PaymentMethodDetailsInteracPresent where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsInteracPresent
instance Show PaymentMethodDetailsInteracPresent
instance Eq PaymentMethodDetailsInteracPresent
instance FromJSON PaymentMethodDetailsInteracPresent
instance ToJSON PaymentMethodDetailsInteracPresent
data PaymentMethodDetailsInteracPresentReadMethod'NonNullable
instance Show PaymentMethodDetailsInteracPresentReadMethod'NonNullable
instance Eq PaymentMethodDetailsInteracPresentReadMethod'NonNullable
instance FromJSON PaymentMethodDetailsInteracPresentReadMethod'NonNullable
instance ToJSON PaymentMethodDetailsInteracPresentReadMethod'NonNullable
data PaymentMethodDetailsInteracPresentReceipt'NonNullable
instance Show PaymentMethodDetailsInteracPresentReceipt'NonNullable
instance Eq PaymentMethodDetailsInteracPresentReceipt'NonNullable
instance FromJSON PaymentMethodDetailsInteracPresentReceipt'NonNullable
instance ToJSON PaymentMethodDetailsInteracPresentReceipt'NonNullable
data PaymentMethodDetailsInteracPresentReceipt'NonNullableAccountType'
instance Show PaymentMethodDetailsInteracPresentReceipt'NonNullableAccountType'
instance Eq PaymentMethodDetailsInteracPresentReceipt'NonNullableAccountType'
instance FromJSON PaymentMethodDetailsInteracPresentReceipt'NonNullableAccountType'
instance ToJSON PaymentMethodDetailsInteracPresentReceipt'NonNullableAccountType'
