module StripeAPI.Types.PaymentMethodDetailsPaynow where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsPaynow
instance Show PaymentMethodDetailsPaynow
instance Eq PaymentMethodDetailsPaynow
instance FromJSON PaymentMethodDetailsPaynow
instance ToJSON PaymentMethodDetailsPaynow
