module StripeAPI.Types.PaymentIntentNextActionVerifyWithMicrodeposits where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionVerifyWithMicrodeposits
instance Show PaymentIntentNextActionVerifyWithMicrodeposits
instance Eq PaymentIntentNextActionVerifyWithMicrodeposits
instance FromJSON PaymentIntentNextActionVerifyWithMicrodeposits
instance ToJSON PaymentIntentNextActionVerifyWithMicrodeposits
data PaymentIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance Show PaymentIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance Eq PaymentIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance FromJSON PaymentIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance ToJSON PaymentIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
