module StripeAPI.Types.PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Show PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Eq PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance FromJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance ToJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
data PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'
instance Show PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'
instance Eq PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'
instance FromJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'
instance ToJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'
data PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'
instance Show PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'
instance Eq PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'
instance FromJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'
instance ToJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'
