module StripeAPI.Types.PaymentIntentPaymentMethodOptionsAuBecsDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsAuBecsDebit
instance Show PaymentIntentPaymentMethodOptionsAuBecsDebit
instance Eq PaymentIntentPaymentMethodOptionsAuBecsDebit
instance FromJSON PaymentIntentPaymentMethodOptionsAuBecsDebit
instance ToJSON PaymentIntentPaymentMethodOptionsAuBecsDebit
data PaymentIntentPaymentMethodOptionsAuBecsDebitSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsAuBecsDebitSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsAuBecsDebitSetupFutureUsage'
instance FromJSON PaymentIntentPaymentMethodOptionsAuBecsDebitSetupFutureUsage'
instance ToJSON PaymentIntentPaymentMethodOptionsAuBecsDebitSetupFutureUsage'
