module StripeAPI.Types.PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode
instance Show PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode
instance Eq PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode
instance FromJSON PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode
instance ToJSON PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode
