module StripeAPI.Types.PaymentMethodDetailsCardPresentOffline where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsCardPresentOffline
instance Show PaymentMethodDetailsCardPresentOffline
instance Eq PaymentMethodDetailsCardPresentOffline
instance FromJSON PaymentMethodDetailsCardPresentOffline
instance ToJSON PaymentMethodDetailsCardPresentOffline
