module StripeAPI.Types.PaymentIntentNextActionDisplayBankTransferInstructions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionDisplayBankTransferInstructions
instance Show PaymentIntentNextActionDisplayBankTransferInstructions
instance Eq PaymentIntentNextActionDisplayBankTransferInstructions
instance FromJSON PaymentIntentNextActionDisplayBankTransferInstructions
instance ToJSON PaymentIntentNextActionDisplayBankTransferInstructions
data PaymentIntentNextActionDisplayBankTransferInstructionsType'
instance Show PaymentIntentNextActionDisplayBankTransferInstructionsType'
instance Eq PaymentIntentNextActionDisplayBankTransferInstructionsType'
instance FromJSON PaymentIntentNextActionDisplayBankTransferInstructionsType'
instance ToJSON PaymentIntentNextActionDisplayBankTransferInstructionsType'
