module StripeAPI.Types.PaymentMethodOptionsAfterpayClearpay where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsAfterpayClearpay
instance Show PaymentMethodOptionsAfterpayClearpay
instance Eq PaymentMethodOptionsAfterpayClearpay
instance FromJSON PaymentMethodOptionsAfterpayClearpay
instance ToJSON PaymentMethodOptionsAfterpayClearpay
data PaymentMethodOptionsAfterpayClearpayCaptureMethod'
instance Show PaymentMethodOptionsAfterpayClearpayCaptureMethod'
instance Eq PaymentMethodOptionsAfterpayClearpayCaptureMethod'
instance FromJSON PaymentMethodOptionsAfterpayClearpayCaptureMethod'
instance ToJSON PaymentMethodOptionsAfterpayClearpayCaptureMethod'
data PaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
instance Show PaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
instance Eq PaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
instance FromJSON PaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
instance ToJSON PaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
