module StripeAPI.Types.PaymentMethodOptionsGiropay where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsGiropay
instance Show PaymentMethodOptionsGiropay
instance Eq PaymentMethodOptionsGiropay
instance FromJSON PaymentMethodOptionsGiropay
instance ToJSON PaymentMethodOptionsGiropay
data PaymentMethodOptionsGiropaySetupFutureUsage'
instance Show PaymentMethodOptionsGiropaySetupFutureUsage'
instance Eq PaymentMethodOptionsGiropaySetupFutureUsage'
instance FromJSON PaymentMethodOptionsGiropaySetupFutureUsage'
instance ToJSON PaymentMethodOptionsGiropaySetupFutureUsage'
