module StripeAPI.Types.PaymentIntentNextActionKonbiniLawson where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionKonbiniLawson
instance Show PaymentIntentNextActionKonbiniLawson
instance Eq PaymentIntentNextActionKonbiniLawson
instance FromJSON PaymentIntentNextActionKonbiniLawson
instance ToJSON PaymentIntentNextActionKonbiniLawson
