module StripeAPI.Types.PaymentMethodOptionsOxxo where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsOxxo
instance Show PaymentMethodOptionsOxxo
instance Eq PaymentMethodOptionsOxxo
instance FromJSON PaymentMethodOptionsOxxo
instance ToJSON PaymentMethodOptionsOxxo
data PaymentMethodOptionsOxxoSetupFutureUsage'
instance Show PaymentMethodOptionsOxxoSetupFutureUsage'
instance Eq PaymentMethodOptionsOxxoSetupFutureUsage'
instance FromJSON PaymentMethodOptionsOxxoSetupFutureUsage'
instance ToJSON PaymentMethodOptionsOxxoSetupFutureUsage'
