module StripeAPI.Types.PaymentPagesCheckoutSessionCurrencyConversion where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionCurrencyConversion
instance Show PaymentPagesCheckoutSessionCurrencyConversion
instance Eq PaymentPagesCheckoutSessionCurrencyConversion
instance FromJSON PaymentPagesCheckoutSessionCurrencyConversion
instance ToJSON PaymentPagesCheckoutSessionCurrencyConversion
