module StripeAPI.Types.PaymentMethodDetailsCardWalletMasterpass where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsCardWalletMasterpass
instance Show PaymentMethodDetailsCardWalletMasterpass
instance Eq PaymentMethodDetailsCardWalletMasterpass
instance FromJSON PaymentMethodDetailsCardWalletMasterpass
instance ToJSON PaymentMethodDetailsCardWalletMasterpass
data PaymentMethodDetailsCardWalletMasterpassBillingAddress'NonNullable
instance Show PaymentMethodDetailsCardWalletMasterpassBillingAddress'NonNullable
instance Eq PaymentMethodDetailsCardWalletMasterpassBillingAddress'NonNullable
instance FromJSON PaymentMethodDetailsCardWalletMasterpassBillingAddress'NonNullable
instance ToJSON PaymentMethodDetailsCardWalletMasterpassBillingAddress'NonNullable
data PaymentMethodDetailsCardWalletMasterpassShippingAddress'NonNullable
instance Show PaymentMethodDetailsCardWalletMasterpassShippingAddress'NonNullable
instance Eq PaymentMethodDetailsCardWalletMasterpassShippingAddress'NonNullable
instance FromJSON PaymentMethodDetailsCardWalletMasterpassShippingAddress'NonNullable
instance ToJSON PaymentMethodDetailsCardWalletMasterpassShippingAddress'NonNullable
