module StripeAPI.Types.PaymentMethodOptionsBancontact where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsBancontact
instance Show PaymentMethodOptionsBancontact
instance Eq PaymentMethodOptionsBancontact
instance FromJSON PaymentMethodOptionsBancontact
instance ToJSON PaymentMethodOptionsBancontact
data PaymentMethodOptionsBancontactPreferredLanguage'
instance Show PaymentMethodOptionsBancontactPreferredLanguage'
instance Eq PaymentMethodOptionsBancontactPreferredLanguage'
instance FromJSON PaymentMethodOptionsBancontactPreferredLanguage'
instance ToJSON PaymentMethodOptionsBancontactPreferredLanguage'
data PaymentMethodOptionsBancontactSetupFutureUsage'
instance Show PaymentMethodOptionsBancontactSetupFutureUsage'
instance Eq PaymentMethodOptionsBancontactSetupFutureUsage'
instance FromJSON PaymentMethodOptionsBancontactSetupFutureUsage'
instance ToJSON PaymentMethodOptionsBancontactSetupFutureUsage'
