module StripeAPI.Types.PaymentMethodDetailsCardInstallmentsPlan where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsCardInstallmentsPlan
instance Show PaymentMethodDetailsCardInstallmentsPlan
instance Eq PaymentMethodDetailsCardInstallmentsPlan
instance FromJSON PaymentMethodDetailsCardInstallmentsPlan
instance ToJSON PaymentMethodDetailsCardInstallmentsPlan
data PaymentMethodDetailsCardInstallmentsPlanInterval'NonNullable
instance Show PaymentMethodDetailsCardInstallmentsPlanInterval'NonNullable
instance Eq PaymentMethodDetailsCardInstallmentsPlanInterval'NonNullable
instance FromJSON PaymentMethodDetailsCardInstallmentsPlanInterval'NonNullable
instance ToJSON PaymentMethodDetailsCardInstallmentsPlanInterval'NonNullable
