module StripeAPI.Types.PaymentIntentNextActionWechatPayDisplayQrCode where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionWechatPayDisplayQrCode
instance Show PaymentIntentNextActionWechatPayDisplayQrCode
instance Eq PaymentIntentNextActionWechatPayDisplayQrCode
instance FromJSON PaymentIntentNextActionWechatPayDisplayQrCode
instance ToJSON PaymentIntentNextActionWechatPayDisplayQrCode
