module StripeAPI.Types.PaymentMethodDetailsAfterpayClearpay where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsAfterpayClearpay
instance Show PaymentMethodDetailsAfterpayClearpay
instance Eq PaymentMethodDetailsAfterpayClearpay
instance FromJSON PaymentMethodDetailsAfterpayClearpay
instance ToJSON PaymentMethodDetailsAfterpayClearpay
