module StripeAPI.Types.PaymentLinksResourceTaxIdCollection where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceTaxIdCollection
instance Show PaymentLinksResourceTaxIdCollection
instance Eq PaymentLinksResourceTaxIdCollection
instance FromJSON PaymentLinksResourceTaxIdCollection
instance ToJSON PaymentLinksResourceTaxIdCollection
