module StripeAPI.Types.PaymentPagesCheckoutSessionCustomText where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionCustomText
instance Show PaymentPagesCheckoutSessionCustomText
instance Eq PaymentPagesCheckoutSessionCustomText
instance FromJSON PaymentPagesCheckoutSessionCustomText
instance ToJSON PaymentPagesCheckoutSessionCustomText
data PaymentPagesCheckoutSessionCustomTextAfterSubmit'NonNullable
instance Show PaymentPagesCheckoutSessionCustomTextAfterSubmit'NonNullable
instance Eq PaymentPagesCheckoutSessionCustomTextAfterSubmit'NonNullable
instance FromJSON PaymentPagesCheckoutSessionCustomTextAfterSubmit'NonNullable
instance ToJSON PaymentPagesCheckoutSessionCustomTextAfterSubmit'NonNullable
data PaymentPagesCheckoutSessionCustomTextShippingAddress'NonNullable
instance Show PaymentPagesCheckoutSessionCustomTextShippingAddress'NonNullable
instance Eq PaymentPagesCheckoutSessionCustomTextShippingAddress'NonNullable
instance FromJSON PaymentPagesCheckoutSessionCustomTextShippingAddress'NonNullable
instance ToJSON PaymentPagesCheckoutSessionCustomTextShippingAddress'NonNullable
data PaymentPagesCheckoutSessionCustomTextSubmit'NonNullable
instance Show PaymentPagesCheckoutSessionCustomTextSubmit'NonNullable
instance Eq PaymentPagesCheckoutSessionCustomTextSubmit'NonNullable
instance FromJSON PaymentPagesCheckoutSessionCustomTextSubmit'NonNullable
instance ToJSON PaymentPagesCheckoutSessionCustomTextSubmit'NonNullable
data PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance'NonNullable
instance Show PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance'NonNullable
instance Eq PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance'NonNullable
instance FromJSON PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance'NonNullable
instance ToJSON PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance'NonNullable
