module StripeAPI.Types.PaymentMethodDetailsCashapp where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsCashapp
instance Show PaymentMethodDetailsCashapp
instance Eq PaymentMethodDetailsCashapp
instance FromJSON PaymentMethodDetailsCashapp
instance ToJSON PaymentMethodDetailsCashapp
