module StripeAPI.Types.PaymentMethodOptionsAlipay where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsAlipay
instance Show PaymentMethodOptionsAlipay
instance Eq PaymentMethodOptionsAlipay
instance FromJSON PaymentMethodOptionsAlipay
instance ToJSON PaymentMethodOptionsAlipay
data PaymentMethodOptionsAlipaySetupFutureUsage'
instance Show PaymentMethodOptionsAlipaySetupFutureUsage'
instance Eq PaymentMethodOptionsAlipaySetupFutureUsage'
instance FromJSON PaymentMethodOptionsAlipaySetupFutureUsage'
instance ToJSON PaymentMethodOptionsAlipaySetupFutureUsage'
