module StripeAPI.Types.PaymentIntentNextActionWechatPayRedirectToIosApp where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionWechatPayRedirectToIosApp
instance Show PaymentIntentNextActionWechatPayRedirectToIosApp
instance Eq PaymentIntentNextActionWechatPayRedirectToIosApp
instance FromJSON PaymentIntentNextActionWechatPayRedirectToIosApp
instance ToJSON PaymentIntentNextActionWechatPayRedirectToIosApp
