module StripeAPI.Types.PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture
instance Show PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture
instance Eq PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture
instance FromJSON PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture
instance ToJSON PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture
data PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticaptureStatus'
instance Show PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticaptureStatus'
instance Eq PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticaptureStatus'
instance FromJSON PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticaptureStatus'
instance ToJSON PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticaptureStatus'
