module StripeAPI.Types.PaymentMethodConfigBizPaymentMethodConfigurationDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodConfigBizPaymentMethodConfigurationDetails
instance Show PaymentMethodConfigBizPaymentMethodConfigurationDetails
instance Eq PaymentMethodConfigBizPaymentMethodConfigurationDetails
instance FromJSON PaymentMethodConfigBizPaymentMethodConfigurationDetails
instance ToJSON PaymentMethodConfigBizPaymentMethodConfigurationDetails
