module StripeAPI.Types.PaymentMethodUsBankAccountBlocked where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodUsBankAccountBlocked
instance Show PaymentMethodUsBankAccountBlocked
instance Eq PaymentMethodUsBankAccountBlocked
instance FromJSON PaymentMethodUsBankAccountBlocked
instance ToJSON PaymentMethodUsBankAccountBlocked
data PaymentMethodUsBankAccountBlockedNetworkCode'NonNullable
instance Show PaymentMethodUsBankAccountBlockedNetworkCode'NonNullable
instance Eq PaymentMethodUsBankAccountBlockedNetworkCode'NonNullable
instance FromJSON PaymentMethodUsBankAccountBlockedNetworkCode'NonNullable
instance ToJSON PaymentMethodUsBankAccountBlockedNetworkCode'NonNullable
data PaymentMethodUsBankAccountBlockedReason'NonNullable
instance Show PaymentMethodUsBankAccountBlockedReason'NonNullable
instance Eq PaymentMethodUsBankAccountBlockedReason'NonNullable
instance FromJSON PaymentMethodUsBankAccountBlockedReason'NonNullable
instance ToJSON PaymentMethodUsBankAccountBlockedReason'NonNullable
