module StripeAPI.Types.PaymentLinksResourceInvoiceSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceInvoiceSettings
instance Show PaymentLinksResourceInvoiceSettings
instance Eq PaymentLinksResourceInvoiceSettings
instance FromJSON PaymentLinksResourceInvoiceSettings
instance ToJSON PaymentLinksResourceInvoiceSettings
data PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Show PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Eq PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
instance FromJSON PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
instance ToJSON PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
data PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
instance Show PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
instance Eq PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
instance FromJSON PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
instance ToJSON PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
