module StripeAPI.Types.PaymentMethodDetailsAchDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsAchDebit
instance Show PaymentMethodDetailsAchDebit
instance Eq PaymentMethodDetailsAchDebit
instance FromJSON PaymentMethodDetailsAchDebit
instance ToJSON PaymentMethodDetailsAchDebit
data PaymentMethodDetailsAchDebitAccountHolderType'NonNullable
instance Show PaymentMethodDetailsAchDebitAccountHolderType'NonNullable
instance Eq PaymentMethodDetailsAchDebitAccountHolderType'NonNullable
instance FromJSON PaymentMethodDetailsAchDebitAccountHolderType'NonNullable
instance ToJSON PaymentMethodDetailsAchDebitAccountHolderType'NonNullable
