module StripeAPI.Types.PaymentMethodCardWalletVisaCheckout where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodCardWalletVisaCheckout
instance Show PaymentMethodCardWalletVisaCheckout
instance Eq PaymentMethodCardWalletVisaCheckout
instance FromJSON PaymentMethodCardWalletVisaCheckout
instance ToJSON PaymentMethodCardWalletVisaCheckout
data PaymentMethodCardWalletVisaCheckoutBillingAddress'NonNullable
instance Show PaymentMethodCardWalletVisaCheckoutBillingAddress'NonNullable
instance Eq PaymentMethodCardWalletVisaCheckoutBillingAddress'NonNullable
instance FromJSON PaymentMethodCardWalletVisaCheckoutBillingAddress'NonNullable
instance ToJSON PaymentMethodCardWalletVisaCheckoutBillingAddress'NonNullable
data PaymentMethodCardWalletVisaCheckoutShippingAddress'NonNullable
instance Show PaymentMethodCardWalletVisaCheckoutShippingAddress'NonNullable
instance Eq PaymentMethodCardWalletVisaCheckoutShippingAddress'NonNullable
instance FromJSON PaymentMethodCardWalletVisaCheckoutShippingAddress'NonNullable
instance ToJSON PaymentMethodCardWalletVisaCheckoutShippingAddress'NonNullable
