module StripeAPI.Types.PaymentMethodDetailsOxxo where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodDetailsOxxo
instance Show PaymentMethodDetailsOxxo
instance Eq PaymentMethodDetailsOxxo
instance FromJSON PaymentMethodDetailsOxxo
instance ToJSON PaymentMethodDetailsOxxo
