module StripeAPI.Types.PaymentMethodDetailsSofort where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsSofort
instance Show PaymentMethodDetailsSofort
instance Eq PaymentMethodDetailsSofort
instance FromJSON PaymentMethodDetailsSofort
instance ToJSON PaymentMethodDetailsSofort
data PaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance Show PaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance Eq PaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance FromJSON PaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance ToJSON PaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
data PaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance Show PaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance Eq PaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance FromJSON PaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance ToJSON PaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
data PaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance Show PaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance Eq PaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance FromJSON PaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance ToJSON PaymentMethodDetailsSofortPreferredLanguage'NonNullable
