module StripeAPI.Types.PaymentPagesCheckoutSessionConsentCollection where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionConsentCollection
instance Show PaymentPagesCheckoutSessionConsentCollection
instance Eq PaymentPagesCheckoutSessionConsentCollection
instance FromJSON PaymentPagesCheckoutSessionConsentCollection
instance ToJSON PaymentPagesCheckoutSessionConsentCollection
data PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
instance Show PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
instance Eq PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
instance FromJSON PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
instance ToJSON PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
