module StripeAPI.Types.PaymentMethodSepaDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodSepaDebit
instance Show PaymentMethodSepaDebit
instance Eq PaymentMethodSepaDebit
instance FromJSON PaymentMethodSepaDebit
instance ToJSON PaymentMethodSepaDebit
data PaymentMethodSepaDebitGeneratedFrom'
instance Show PaymentMethodSepaDebitGeneratedFrom'
instance Eq PaymentMethodSepaDebitGeneratedFrom'
instance FromJSON PaymentMethodSepaDebitGeneratedFrom'
instance ToJSON PaymentMethodSepaDebitGeneratedFrom'
data PaymentMethodSepaDebitGeneratedFrom'Charge'Variants
instance Show PaymentMethodSepaDebitGeneratedFrom'Charge'Variants
instance Eq PaymentMethodSepaDebitGeneratedFrom'Charge'Variants
instance FromJSON PaymentMethodSepaDebitGeneratedFrom'Charge'Variants
instance ToJSON PaymentMethodSepaDebitGeneratedFrom'Charge'Variants
data PaymentMethodSepaDebitGeneratedFrom'SetupAttempt'Variants
instance Show PaymentMethodSepaDebitGeneratedFrom'SetupAttempt'Variants
instance Eq PaymentMethodSepaDebitGeneratedFrom'SetupAttempt'Variants
instance FromJSON PaymentMethodSepaDebitGeneratedFrom'SetupAttempt'Variants
instance ToJSON PaymentMethodSepaDebitGeneratedFrom'SetupAttempt'Variants
