module StripeAPI.Types.PaymentIntentNextActionAlipayHandleRedirect where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentIntentNextActionAlipayHandleRedirect
instance Show PaymentIntentNextActionAlipayHandleRedirect
instance Eq PaymentIntentNextActionAlipayHandleRedirect
instance FromJSON PaymentIntentNextActionAlipayHandleRedirect
instance ToJSON PaymentIntentNextActionAlipayHandleRedirect
