module StripeAPI.Types.PaymentIntentPaymentMethodOptionsUsBankAccount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsUsBankAccount
instance Show PaymentIntentPaymentMethodOptionsUsBankAccount
instance Eq PaymentIntentPaymentMethodOptionsUsBankAccount
instance FromJSON PaymentIntentPaymentMethodOptionsUsBankAccount
instance ToJSON PaymentIntentPaymentMethodOptionsUsBankAccount
data PaymentIntentPaymentMethodOptionsUsBankAccountPreferredSettlementSpeed'
instance Show PaymentIntentPaymentMethodOptionsUsBankAccountPreferredSettlementSpeed'
instance Eq PaymentIntentPaymentMethodOptionsUsBankAccountPreferredSettlementSpeed'
instance FromJSON PaymentIntentPaymentMethodOptionsUsBankAccountPreferredSettlementSpeed'
instance ToJSON PaymentIntentPaymentMethodOptionsUsBankAccountPreferredSettlementSpeed'
data PaymentIntentPaymentMethodOptionsUsBankAccountSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsUsBankAccountSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsUsBankAccountSetupFutureUsage'
instance FromJSON PaymentIntentPaymentMethodOptionsUsBankAccountSetupFutureUsage'
instance ToJSON PaymentIntentPaymentMethodOptionsUsBankAccountSetupFutureUsage'
data PaymentIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance Show PaymentIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance Eq PaymentIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance FromJSON PaymentIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance ToJSON PaymentIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
