module StripeAPI.Types.PaymentIntentPaymentMethodOptionsAcssDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentIntentPaymentMethodOptionsAcssDebit
instance Show PaymentIntentPaymentMethodOptionsAcssDebit
instance Eq PaymentIntentPaymentMethodOptionsAcssDebit
instance FromJSON PaymentIntentPaymentMethodOptionsAcssDebit
instance ToJSON PaymentIntentPaymentMethodOptionsAcssDebit
data PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Show PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Eq PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance FromJSON PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance ToJSON PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
