module StripeAPI.Types.PaymentMethodOptionsCardInstallments where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodOptionsCardInstallments 
instance Show PaymentMethodOptionsCardInstallments 
instance Eq PaymentMethodOptionsCardInstallments 
instance FromJSON PaymentMethodOptionsCardInstallments 
instance ToJSON PaymentMethodOptionsCardInstallments 
data PaymentMethodOptionsCardInstallmentsPlan' 
instance Show PaymentMethodOptionsCardInstallmentsPlan' 
instance Eq PaymentMethodOptionsCardInstallmentsPlan' 
instance FromJSON PaymentMethodOptionsCardInstallmentsPlan' 
instance ToJSON PaymentMethodOptionsCardInstallmentsPlan' 
data PaymentMethodOptionsCardInstallmentsPlan'Interval'
instance Show PaymentMethodOptionsCardInstallmentsPlan'Interval'
instance Eq PaymentMethodOptionsCardInstallmentsPlan'Interval'
instance FromJSON PaymentMethodOptionsCardInstallmentsPlan'Interval'
instance ToJSON PaymentMethodOptionsCardInstallmentsPlan'Interval'
data PaymentMethodOptionsCardInstallmentsPlan'Type'
instance Show PaymentMethodOptionsCardInstallmentsPlan'Type'
instance Eq PaymentMethodOptionsCardInstallmentsPlan'Type'
instance FromJSON PaymentMethodOptionsCardInstallmentsPlan'Type'
instance ToJSON PaymentMethodOptionsCardInstallmentsPlan'Type'
