module StripeAPI.Types.PaymentMethodDetailsCardInstallments where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsCardInstallments
instance Show PaymentMethodDetailsCardInstallments
instance Eq PaymentMethodDetailsCardInstallments
instance FromJSON PaymentMethodDetailsCardInstallments
instance ToJSON PaymentMethodDetailsCardInstallments
data PaymentMethodDetailsCardInstallmentsPlan'NonNullable
instance Show PaymentMethodDetailsCardInstallmentsPlan'NonNullable
instance Eq PaymentMethodDetailsCardInstallmentsPlan'NonNullable
instance FromJSON PaymentMethodDetailsCardInstallmentsPlan'NonNullable
instance ToJSON PaymentMethodDetailsCardInstallmentsPlan'NonNullable
data PaymentMethodDetailsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance Show PaymentMethodDetailsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance Eq PaymentMethodDetailsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance FromJSON PaymentMethodDetailsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance ToJSON PaymentMethodDetailsCardInstallmentsPlan'NonNullableInterval'NonNullable
data PaymentMethodDetailsCardInstallmentsPlan'NonNullableType'
instance Show PaymentMethodDetailsCardInstallmentsPlan'NonNullableType'
instance Eq PaymentMethodDetailsCardInstallmentsPlan'NonNullableType'
instance FromJSON PaymentMethodDetailsCardInstallmentsPlan'NonNullableType'
instance ToJSON PaymentMethodDetailsCardInstallmentsPlan'NonNullableType'
