module StripeAPI.Types.PaymentMethodOptionsCardMandateOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsCardMandateOptions
instance Show PaymentMethodOptionsCardMandateOptions
instance Eq PaymentMethodOptionsCardMandateOptions
instance FromJSON PaymentMethodOptionsCardMandateOptions
instance ToJSON PaymentMethodOptionsCardMandateOptions
data PaymentMethodOptionsCardMandateOptionsAmountType'
instance Show PaymentMethodOptionsCardMandateOptionsAmountType'
instance Eq PaymentMethodOptionsCardMandateOptionsAmountType'
instance FromJSON PaymentMethodOptionsCardMandateOptionsAmountType'
instance ToJSON PaymentMethodOptionsCardMandateOptionsAmountType'
data PaymentMethodOptionsCardMandateOptionsInterval'
instance Show PaymentMethodOptionsCardMandateOptionsInterval'
instance Eq PaymentMethodOptionsCardMandateOptionsInterval'
instance FromJSON PaymentMethodOptionsCardMandateOptionsInterval'
instance ToJSON PaymentMethodOptionsCardMandateOptionsInterval'
data PaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance Show PaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance Eq PaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance FromJSON PaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance ToJSON PaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
