module StripeAPI.Types.PaymentMethodCardWalletMasterpass where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodCardWalletMasterpass
instance Show PaymentMethodCardWalletMasterpass
instance Eq PaymentMethodCardWalletMasterpass
instance FromJSON PaymentMethodCardWalletMasterpass
instance ToJSON PaymentMethodCardWalletMasterpass
data PaymentMethodCardWalletMasterpassBillingAddress'NonNullable
instance Show PaymentMethodCardWalletMasterpassBillingAddress'NonNullable
instance Eq PaymentMethodCardWalletMasterpassBillingAddress'NonNullable
instance FromJSON PaymentMethodCardWalletMasterpassBillingAddress'NonNullable
instance ToJSON PaymentMethodCardWalletMasterpassBillingAddress'NonNullable
data PaymentMethodCardWalletMasterpassShippingAddress'NonNullable
instance Show PaymentMethodCardWalletMasterpassShippingAddress'NonNullable
instance Eq PaymentMethodCardWalletMasterpassShippingAddress'NonNullable
instance FromJSON PaymentMethodCardWalletMasterpassShippingAddress'NonNullable
instance ToJSON PaymentMethodCardWalletMasterpassShippingAddress'NonNullable
