module StripeAPI.Types.PaymentMethodSepaDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodSepaDebit
instance Show PaymentMethodSepaDebit
instance Eq PaymentMethodSepaDebit
instance FromJSON PaymentMethodSepaDebit
instance ToJSON PaymentMethodSepaDebit
data PaymentMethodSepaDebitGeneratedFrom'NonNullable
instance Show PaymentMethodSepaDebitGeneratedFrom'NonNullable
instance Eq PaymentMethodSepaDebitGeneratedFrom'NonNullable
instance FromJSON PaymentMethodSepaDebitGeneratedFrom'NonNullable
instance ToJSON PaymentMethodSepaDebitGeneratedFrom'NonNullable
data PaymentMethodSepaDebitGeneratedFrom'NonNullableCharge'NonNullableVariants
instance Show PaymentMethodSepaDebitGeneratedFrom'NonNullableCharge'NonNullableVariants
instance Eq PaymentMethodSepaDebitGeneratedFrom'NonNullableCharge'NonNullableVariants
instance FromJSON PaymentMethodSepaDebitGeneratedFrom'NonNullableCharge'NonNullableVariants
instance ToJSON PaymentMethodSepaDebitGeneratedFrom'NonNullableCharge'NonNullableVariants
data PaymentMethodSepaDebitGeneratedFrom'NonNullableSetupAttempt'NonNullableVariants
instance Show PaymentMethodSepaDebitGeneratedFrom'NonNullableSetupAttempt'NonNullableVariants
instance Eq PaymentMethodSepaDebitGeneratedFrom'NonNullableSetupAttempt'NonNullableVariants
instance FromJSON PaymentMethodSepaDebitGeneratedFrom'NonNullableSetupAttempt'NonNullableVariants
instance ToJSON PaymentMethodSepaDebitGeneratedFrom'NonNullableSetupAttempt'NonNullableVariants
