module StripeAPI.Types.PaymentIntentNextActionWechatPayRedirectToAndroidApp where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionWechatPayRedirectToAndroidApp
instance Show PaymentIntentNextActionWechatPayRedirectToAndroidApp
instance Eq PaymentIntentNextActionWechatPayRedirectToAndroidApp
instance FromJSON PaymentIntentNextActionWechatPayRedirectToAndroidApp
instance ToJSON PaymentIntentNextActionWechatPayRedirectToAndroidApp
