module StripeAPI.Types.PaymentIntentPaymentMethodOptionsCard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsCard
instance Show PaymentIntentPaymentMethodOptionsCard
instance Eq PaymentIntentPaymentMethodOptionsCard
instance FromJSON PaymentIntentPaymentMethodOptionsCard
instance ToJSON PaymentIntentPaymentMethodOptionsCard
data PaymentIntentPaymentMethodOptionsCardCaptureMethod'
instance Show PaymentIntentPaymentMethodOptionsCardCaptureMethod'
instance Eq PaymentIntentPaymentMethodOptionsCardCaptureMethod'
instance FromJSON PaymentIntentPaymentMethodOptionsCardCaptureMethod'
instance ToJSON PaymentIntentPaymentMethodOptionsCardCaptureMethod'
data PaymentIntentPaymentMethodOptionsCardInstallments'NonNullable
instance Show PaymentIntentPaymentMethodOptionsCardInstallments'NonNullable
instance Eq PaymentIntentPaymentMethodOptionsCardInstallments'NonNullable
instance FromJSON PaymentIntentPaymentMethodOptionsCardInstallments'NonNullable
instance ToJSON PaymentIntentPaymentMethodOptionsCardInstallments'NonNullable
data PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullable
instance Show PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullable
instance Eq PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullable
instance FromJSON PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullable
instance ToJSON PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullable
data PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullableInterval'NonNullable
instance Show PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullableInterval'NonNullable
instance Eq PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullableInterval'NonNullable
instance FromJSON PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullableInterval'NonNullable
instance ToJSON PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullableInterval'NonNullable
data PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullableType'
instance Show PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullableType'
instance Eq PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullableType'
instance FromJSON PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullableType'
instance ToJSON PaymentIntentPaymentMethodOptionsCardInstallments'NonNullablePlan'NonNullableType'
data PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullable
instance Show PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullable
instance Eq PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullable
instance FromJSON PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullable
instance ToJSON PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullable
data PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
instance Show PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
instance Eq PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
instance FromJSON PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
instance ToJSON PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
data PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
instance Show PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
instance Eq PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
instance FromJSON PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
instance ToJSON PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
data PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
instance Show PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
instance Eq PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
instance FromJSON PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
instance ToJSON PaymentIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
data PaymentIntentPaymentMethodOptionsCardNetwork'NonNullable
instance Show PaymentIntentPaymentMethodOptionsCardNetwork'NonNullable
instance Eq PaymentIntentPaymentMethodOptionsCardNetwork'NonNullable
instance FromJSON PaymentIntentPaymentMethodOptionsCardNetwork'NonNullable
instance ToJSON PaymentIntentPaymentMethodOptionsCardNetwork'NonNullable
data PaymentIntentPaymentMethodOptionsCardRequestExtendedAuthorization'
instance Show PaymentIntentPaymentMethodOptionsCardRequestExtendedAuthorization'
instance Eq PaymentIntentPaymentMethodOptionsCardRequestExtendedAuthorization'
instance FromJSON PaymentIntentPaymentMethodOptionsCardRequestExtendedAuthorization'
instance ToJSON PaymentIntentPaymentMethodOptionsCardRequestExtendedAuthorization'
data PaymentIntentPaymentMethodOptionsCardRequestIncrementalAuthorization'
instance Show PaymentIntentPaymentMethodOptionsCardRequestIncrementalAuthorization'
instance Eq PaymentIntentPaymentMethodOptionsCardRequestIncrementalAuthorization'
instance FromJSON PaymentIntentPaymentMethodOptionsCardRequestIncrementalAuthorization'
instance ToJSON PaymentIntentPaymentMethodOptionsCardRequestIncrementalAuthorization'
data PaymentIntentPaymentMethodOptionsCardRequestMulticapture'
instance Show PaymentIntentPaymentMethodOptionsCardRequestMulticapture'
instance Eq PaymentIntentPaymentMethodOptionsCardRequestMulticapture'
instance FromJSON PaymentIntentPaymentMethodOptionsCardRequestMulticapture'
instance ToJSON PaymentIntentPaymentMethodOptionsCardRequestMulticapture'
data PaymentIntentPaymentMethodOptionsCardRequestOvercapture'
instance Show PaymentIntentPaymentMethodOptionsCardRequestOvercapture'
instance Eq PaymentIntentPaymentMethodOptionsCardRequestOvercapture'
instance FromJSON PaymentIntentPaymentMethodOptionsCardRequestOvercapture'
instance ToJSON PaymentIntentPaymentMethodOptionsCardRequestOvercapture'
data PaymentIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Show PaymentIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Eq PaymentIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance FromJSON PaymentIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance ToJSON PaymentIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
data PaymentIntentPaymentMethodOptionsCardSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsCardSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsCardSetupFutureUsage'
instance FromJSON PaymentIntentPaymentMethodOptionsCardSetupFutureUsage'
instance ToJSON PaymentIntentPaymentMethodOptionsCardSetupFutureUsage'
