module StripeAPI.Types.PaymentMethodOptionsFpx where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsFpx
instance Show PaymentMethodOptionsFpx
instance Eq PaymentMethodOptionsFpx
instance FromJSON PaymentMethodOptionsFpx
instance ToJSON PaymentMethodOptionsFpx
data PaymentMethodOptionsFpxSetupFutureUsage'
instance Show PaymentMethodOptionsFpxSetupFutureUsage'
instance Eq PaymentMethodOptionsFpxSetupFutureUsage'
instance FromJSON PaymentMethodOptionsFpxSetupFutureUsage'
instance ToJSON PaymentMethodOptionsFpxSetupFutureUsage'
