module StripeAPI.Types.PaymentMethodCardGeneratedCard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodCardGeneratedCard
instance Show PaymentMethodCardGeneratedCard
instance Eq PaymentMethodCardGeneratedCard
instance FromJSON PaymentMethodCardGeneratedCard
instance ToJSON PaymentMethodCardGeneratedCard
data PaymentMethodCardGeneratedCardPaymentMethodDetails'NonNullable
instance Show PaymentMethodCardGeneratedCardPaymentMethodDetails'NonNullable
instance Eq PaymentMethodCardGeneratedCardPaymentMethodDetails'NonNullable
instance FromJSON PaymentMethodCardGeneratedCardPaymentMethodDetails'NonNullable
instance ToJSON PaymentMethodCardGeneratedCardPaymentMethodDetails'NonNullable
data PaymentMethodCardGeneratedCardSetupAttempt'NonNullableVariants
instance Show PaymentMethodCardGeneratedCardSetupAttempt'NonNullableVariants
instance Eq PaymentMethodCardGeneratedCardSetupAttempt'NonNullableVariants
instance FromJSON PaymentMethodCardGeneratedCardSetupAttempt'NonNullableVariants
instance ToJSON PaymentMethodCardGeneratedCardSetupAttempt'NonNullableVariants
