module StripeAPI.Types.PaymentIntentPaymentMethodOptionsSepaDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsSepaDebit
instance Show PaymentIntentPaymentMethodOptionsSepaDebit
instance Eq PaymentIntentPaymentMethodOptionsSepaDebit
instance FromJSON PaymentIntentPaymentMethodOptionsSepaDebit
instance ToJSON PaymentIntentPaymentMethodOptionsSepaDebit
data PaymentIntentPaymentMethodOptionsSepaDebitSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsSepaDebitSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsSepaDebitSetupFutureUsage'
instance FromJSON PaymentIntentPaymentMethodOptionsSepaDebitSetupFutureUsage'
instance ToJSON PaymentIntentPaymentMethodOptionsSepaDebitSetupFutureUsage'
