module StripeAPI.Types.PaymentIntentNextActionKonbiniSeicomart where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionKonbiniSeicomart
instance Show PaymentIntentNextActionKonbiniSeicomart
instance Eq PaymentIntentNextActionKonbiniSeicomart
instance FromJSON PaymentIntentNextActionKonbiniSeicomart
instance ToJSON PaymentIntentNextActionKonbiniSeicomart
