module StripeAPI.Types.PaymentMethodOptionsCustomerBalanceBankTransfer where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsCustomerBalanceBankTransfer
instance Show PaymentMethodOptionsCustomerBalanceBankTransfer
instance Eq PaymentMethodOptionsCustomerBalanceBankTransfer
instance FromJSON PaymentMethodOptionsCustomerBalanceBankTransfer
instance ToJSON PaymentMethodOptionsCustomerBalanceBankTransfer
data PaymentMethodOptionsCustomerBalanceBankTransferRequestedAddressTypes'
instance Show PaymentMethodOptionsCustomerBalanceBankTransferRequestedAddressTypes'
instance Eq PaymentMethodOptionsCustomerBalanceBankTransferRequestedAddressTypes'
instance FromJSON PaymentMethodOptionsCustomerBalanceBankTransferRequestedAddressTypes'
instance ToJSON PaymentMethodOptionsCustomerBalanceBankTransferRequestedAddressTypes'
data PaymentMethodOptionsCustomerBalanceBankTransferType'NonNullable
instance Show PaymentMethodOptionsCustomerBalanceBankTransferType'NonNullable
instance Eq PaymentMethodOptionsCustomerBalanceBankTransferType'NonNullable
instance FromJSON PaymentMethodOptionsCustomerBalanceBankTransferType'NonNullable
instance ToJSON PaymentMethodOptionsCustomerBalanceBankTransferType'NonNullable
