module StripeAPI.Types.PaymentLinksResourceCustomFieldsDropdown where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceCustomFieldsDropdown
instance Show PaymentLinksResourceCustomFieldsDropdown
instance Eq PaymentLinksResourceCustomFieldsDropdown
instance FromJSON PaymentLinksResourceCustomFieldsDropdown
instance ToJSON PaymentLinksResourceCustomFieldsDropdown
