module StripeAPI.Types.PaymentMethodCardPresentNetworks where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodCardPresentNetworks
instance Show PaymentMethodCardPresentNetworks
instance Eq PaymentMethodCardPresentNetworks
instance FromJSON PaymentMethodCardPresentNetworks
instance ToJSON PaymentMethodCardPresentNetworks
