module StripeAPI.Types.PaymentLinksResourceCustomText where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceCustomText
instance Show PaymentLinksResourceCustomText
instance Eq PaymentLinksResourceCustomText
instance FromJSON PaymentLinksResourceCustomText
instance ToJSON PaymentLinksResourceCustomText
data PaymentLinksResourceCustomTextAfterSubmit'NonNullable
instance Show PaymentLinksResourceCustomTextAfterSubmit'NonNullable
instance Eq PaymentLinksResourceCustomTextAfterSubmit'NonNullable
instance FromJSON PaymentLinksResourceCustomTextAfterSubmit'NonNullable
instance ToJSON PaymentLinksResourceCustomTextAfterSubmit'NonNullable
data PaymentLinksResourceCustomTextShippingAddress'NonNullable
instance Show PaymentLinksResourceCustomTextShippingAddress'NonNullable
instance Eq PaymentLinksResourceCustomTextShippingAddress'NonNullable
instance FromJSON PaymentLinksResourceCustomTextShippingAddress'NonNullable
instance ToJSON PaymentLinksResourceCustomTextShippingAddress'NonNullable
data PaymentLinksResourceCustomTextSubmit'NonNullable
instance Show PaymentLinksResourceCustomTextSubmit'NonNullable
instance Eq PaymentLinksResourceCustomTextSubmit'NonNullable
instance FromJSON PaymentLinksResourceCustomTextSubmit'NonNullable
instance ToJSON PaymentLinksResourceCustomTextSubmit'NonNullable
data PaymentLinksResourceCustomTextTermsOfServiceAcceptance'NonNullable
instance Show PaymentLinksResourceCustomTextTermsOfServiceAcceptance'NonNullable
instance Eq PaymentLinksResourceCustomTextTermsOfServiceAcceptance'NonNullable
instance FromJSON PaymentLinksResourceCustomTextTermsOfServiceAcceptance'NonNullable
instance ToJSON PaymentLinksResourceCustomTextTermsOfServiceAcceptance'NonNullable
