module StripeAPI.Types.PaymentMethodOptionsZip where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsZip
instance Show PaymentMethodOptionsZip
instance Eq PaymentMethodOptionsZip
instance FromJSON PaymentMethodOptionsZip
instance ToJSON PaymentMethodOptionsZip
data PaymentMethodOptionsZipSetupFutureUsage'
instance Show PaymentMethodOptionsZipSetupFutureUsage'
instance Eq PaymentMethodOptionsZipSetupFutureUsage'
instance FromJSON PaymentMethodOptionsZipSetupFutureUsage'
instance ToJSON PaymentMethodOptionsZipSetupFutureUsage'
