module StripeAPI.Types.PaymentLinksResourcePaymentMethodReuseAgreement where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourcePaymentMethodReuseAgreement
instance Show PaymentLinksResourcePaymentMethodReuseAgreement
instance Eq PaymentLinksResourcePaymentMethodReuseAgreement
instance FromJSON PaymentLinksResourcePaymentMethodReuseAgreement
instance ToJSON PaymentLinksResourcePaymentMethodReuseAgreement
data PaymentLinksResourcePaymentMethodReuseAgreementPosition'
instance Show PaymentLinksResourcePaymentMethodReuseAgreementPosition'
instance Eq PaymentLinksResourcePaymentMethodReuseAgreementPosition'
instance FromJSON PaymentLinksResourcePaymentMethodReuseAgreementPosition'
instance ToJSON PaymentLinksResourcePaymentMethodReuseAgreementPosition'
