module StripeAPI.Types.PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown
instance Show PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown
instance Eq PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown
instance FromJSON PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown
instance ToJSON PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown
