module StripeAPI.Types.PaymentMethodCardGeneratedCard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodCardGeneratedCard
instance Show PaymentMethodCardGeneratedCard
instance Eq PaymentMethodCardGeneratedCard
instance FromJSON PaymentMethodCardGeneratedCard
instance ToJSON PaymentMethodCardGeneratedCard
data PaymentMethodCardGeneratedCardPaymentMethodDetails'
instance Show PaymentMethodCardGeneratedCardPaymentMethodDetails'
instance Eq PaymentMethodCardGeneratedCardPaymentMethodDetails'
instance FromJSON PaymentMethodCardGeneratedCardPaymentMethodDetails'
instance ToJSON PaymentMethodCardGeneratedCardPaymentMethodDetails'
