module StripeAPI.Types.PaymentFlowsAmountDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentFlowsAmountDetails
instance Show PaymentFlowsAmountDetails
instance Eq PaymentFlowsAmountDetails
instance FromJSON PaymentFlowsAmountDetails
instance ToJSON PaymentFlowsAmountDetails
