module StripeAPI.Types.PaymentMethodOptionsUsBankAccountMandateOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsUsBankAccountMandateOptions
instance Show PaymentMethodOptionsUsBankAccountMandateOptions
instance Eq PaymentMethodOptionsUsBankAccountMandateOptions
instance FromJSON PaymentMethodOptionsUsBankAccountMandateOptions
instance ToJSON PaymentMethodOptionsUsBankAccountMandateOptions
data PaymentMethodOptionsUsBankAccountMandateOptionsCollectionMethod'
instance Show PaymentMethodOptionsUsBankAccountMandateOptionsCollectionMethod'
instance Eq PaymentMethodOptionsUsBankAccountMandateOptionsCollectionMethod'
instance FromJSON PaymentMethodOptionsUsBankAccountMandateOptionsCollectionMethod'
instance ToJSON PaymentMethodOptionsUsBankAccountMandateOptionsCollectionMethod'
