module StripeAPI.Types.PaymentMethodDetailsGiropay where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsGiropay
instance Show PaymentMethodDetailsGiropay
instance Eq PaymentMethodDetailsGiropay
instance FromJSON PaymentMethodDetailsGiropay
instance ToJSON PaymentMethodDetailsGiropay
