module StripeAPI.Types.PaymentMethodUsBankAccount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodUsBankAccount
instance Show PaymentMethodUsBankAccount
instance Eq PaymentMethodUsBankAccount
instance FromJSON PaymentMethodUsBankAccount
instance ToJSON PaymentMethodUsBankAccount
data PaymentMethodUsBankAccountAccountHolderType'NonNullable
instance Show PaymentMethodUsBankAccountAccountHolderType'NonNullable
instance Eq PaymentMethodUsBankAccountAccountHolderType'NonNullable
instance FromJSON PaymentMethodUsBankAccountAccountHolderType'NonNullable
instance ToJSON PaymentMethodUsBankAccountAccountHolderType'NonNullable
data PaymentMethodUsBankAccountAccountType'NonNullable
instance Show PaymentMethodUsBankAccountAccountType'NonNullable
instance Eq PaymentMethodUsBankAccountAccountType'NonNullable
instance FromJSON PaymentMethodUsBankAccountAccountType'NonNullable
instance ToJSON PaymentMethodUsBankAccountAccountType'NonNullable
data PaymentMethodUsBankAccountNetworks'NonNullable
instance Show PaymentMethodUsBankAccountNetworks'NonNullable
instance Eq PaymentMethodUsBankAccountNetworks'NonNullable
instance FromJSON PaymentMethodUsBankAccountNetworks'NonNullable
instance ToJSON PaymentMethodUsBankAccountNetworks'NonNullable
data PaymentMethodUsBankAccountNetworks'NonNullableSupported'
instance Show PaymentMethodUsBankAccountNetworks'NonNullableSupported'
instance Eq PaymentMethodUsBankAccountNetworks'NonNullableSupported'
instance FromJSON PaymentMethodUsBankAccountNetworks'NonNullableSupported'
instance ToJSON PaymentMethodUsBankAccountNetworks'NonNullableSupported'
data PaymentMethodUsBankAccountStatusDetails'NonNullable
instance Show PaymentMethodUsBankAccountStatusDetails'NonNullable
instance Eq PaymentMethodUsBankAccountStatusDetails'NonNullable
instance FromJSON PaymentMethodUsBankAccountStatusDetails'NonNullable
instance ToJSON PaymentMethodUsBankAccountStatusDetails'NonNullable
