module StripeAPI.Types.PaymentMethodCardWalletMasterpass where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodCardWalletMasterpass
instance Show PaymentMethodCardWalletMasterpass
instance Eq PaymentMethodCardWalletMasterpass
instance FromJSON PaymentMethodCardWalletMasterpass
instance ToJSON PaymentMethodCardWalletMasterpass
data PaymentMethodCardWalletMasterpassBillingAddress'
instance Show PaymentMethodCardWalletMasterpassBillingAddress'
instance Eq PaymentMethodCardWalletMasterpassBillingAddress'
instance FromJSON PaymentMethodCardWalletMasterpassBillingAddress'
instance ToJSON PaymentMethodCardWalletMasterpassBillingAddress'
data PaymentMethodCardWalletMasterpassShippingAddress'
instance Show PaymentMethodCardWalletMasterpassShippingAddress'
instance Eq PaymentMethodCardWalletMasterpassShippingAddress'
instance FromJSON PaymentMethodCardWalletMasterpassShippingAddress'
instance ToJSON PaymentMethodCardWalletMasterpassShippingAddress'
