module StripeAPI.Types.PaymentMethodOptionsSofort where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsSofort
instance Show PaymentMethodOptionsSofort
instance Eq PaymentMethodOptionsSofort
instance FromJSON PaymentMethodOptionsSofort
instance ToJSON PaymentMethodOptionsSofort
data PaymentMethodOptionsSofortPreferredLanguage'NonNullable
instance Show PaymentMethodOptionsSofortPreferredLanguage'NonNullable
instance Eq PaymentMethodOptionsSofortPreferredLanguage'NonNullable
instance FromJSON PaymentMethodOptionsSofortPreferredLanguage'NonNullable
instance ToJSON PaymentMethodOptionsSofortPreferredLanguage'NonNullable
data PaymentMethodOptionsSofortSetupFutureUsage'
instance Show PaymentMethodOptionsSofortSetupFutureUsage'
instance Eq PaymentMethodOptionsSofortSetupFutureUsage'
instance FromJSON PaymentMethodOptionsSofortSetupFutureUsage'
instance ToJSON PaymentMethodOptionsSofortSetupFutureUsage'
