module StripeAPI.Types.PaymentMethodDetailsPaypal where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsPaypal
instance Show PaymentMethodDetailsPaypal
instance Eq PaymentMethodDetailsPaypal
instance FromJSON PaymentMethodDetailsPaypal
instance ToJSON PaymentMethodDetailsPaypal
data PaymentMethodDetailsPaypalSellerProtection'NonNullable
instance Show PaymentMethodDetailsPaypalSellerProtection'NonNullable
instance Eq PaymentMethodDetailsPaypalSellerProtection'NonNullable
instance FromJSON PaymentMethodDetailsPaypalSellerProtection'NonNullable
instance ToJSON PaymentMethodDetailsPaypalSellerProtection'NonNullable
data PaymentMethodDetailsPaypalSellerProtection'NonNullableDisputeCategories'NonNullable
instance Show PaymentMethodDetailsPaypalSellerProtection'NonNullableDisputeCategories'NonNullable
instance Eq PaymentMethodDetailsPaypalSellerProtection'NonNullableDisputeCategories'NonNullable
instance FromJSON PaymentMethodDetailsPaypalSellerProtection'NonNullableDisputeCategories'NonNullable
instance ToJSON PaymentMethodDetailsPaypalSellerProtection'NonNullableDisputeCategories'NonNullable
data PaymentMethodDetailsPaypalSellerProtection'NonNullableStatus'
instance Show PaymentMethodDetailsPaypalSellerProtection'NonNullableStatus'
instance Eq PaymentMethodDetailsPaypalSellerProtection'NonNullableStatus'
instance FromJSON PaymentMethodDetailsPaypalSellerProtection'NonNullableStatus'
instance ToJSON PaymentMethodDetailsPaypalSellerProtection'NonNullableStatus'
