module StripeAPI.Types.PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Show PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Eq PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance FromJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance ToJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
data PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance Show PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance Eq PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance FromJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance ToJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
data PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance Show PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance Eq PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance FromJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance ToJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
