module StripeAPI.Types.PaymentLinksResourceConsentCollection where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceConsentCollection
instance Show PaymentLinksResourceConsentCollection
instance Eq PaymentLinksResourceConsentCollection
instance FromJSON PaymentLinksResourceConsentCollection
instance ToJSON PaymentLinksResourceConsentCollection
data PaymentLinksResourceConsentCollectionPromotions'NonNullable
instance Show PaymentLinksResourceConsentCollectionPromotions'NonNullable
instance Eq PaymentLinksResourceConsentCollectionPromotions'NonNullable
instance FromJSON PaymentLinksResourceConsentCollectionPromotions'NonNullable
instance ToJSON PaymentLinksResourceConsentCollectionPromotions'NonNullable
