module StripeAPI.Types.PaymentPagesCheckoutSessionShippingCost where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionShippingCost
instance Show PaymentPagesCheckoutSessionShippingCost
instance Eq PaymentPagesCheckoutSessionShippingCost
instance FromJSON PaymentPagesCheckoutSessionShippingCost
instance ToJSON PaymentPagesCheckoutSessionShippingCost
data PaymentPagesCheckoutSessionShippingCostShippingRate'NonNullableVariants
instance Show PaymentPagesCheckoutSessionShippingCostShippingRate'NonNullableVariants
instance Eq PaymentPagesCheckoutSessionShippingCostShippingRate'NonNullableVariants
instance FromJSON PaymentPagesCheckoutSessionShippingCostShippingRate'NonNullableVariants
instance ToJSON PaymentPagesCheckoutSessionShippingCostShippingRate'NonNullableVariants
