module StripeAPI.Types.PaymentIntentPaymentMethodOptionsLink where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsLink
instance Show PaymentIntentPaymentMethodOptionsLink
instance Eq PaymentIntentPaymentMethodOptionsLink
instance FromJSON PaymentIntentPaymentMethodOptionsLink
instance ToJSON PaymentIntentPaymentMethodOptionsLink
data PaymentIntentPaymentMethodOptionsLinkCaptureMethod'
instance Show PaymentIntentPaymentMethodOptionsLinkCaptureMethod'
instance Eq PaymentIntentPaymentMethodOptionsLinkCaptureMethod'
instance FromJSON PaymentIntentPaymentMethodOptionsLinkCaptureMethod'
instance ToJSON PaymentIntentPaymentMethodOptionsLinkCaptureMethod'
data PaymentIntentPaymentMethodOptionsLinkSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsLinkSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsLinkSetupFutureUsage'
instance FromJSON PaymentIntentPaymentMethodOptionsLinkSetupFutureUsage'
instance ToJSON PaymentIntentPaymentMethodOptionsLinkSetupFutureUsage'
