module StripeAPI.Types.PaymentFlowsAutomaticPaymentMethodsSetupIntent where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentFlowsAutomaticPaymentMethodsSetupIntent
instance Show PaymentFlowsAutomaticPaymentMethodsSetupIntent
instance Eq PaymentFlowsAutomaticPaymentMethodsSetupIntent
instance FromJSON PaymentFlowsAutomaticPaymentMethodsSetupIntent
instance ToJSON PaymentFlowsAutomaticPaymentMethodsSetupIntent
data PaymentFlowsAutomaticPaymentMethodsSetupIntentAllowRedirects'
instance Show PaymentFlowsAutomaticPaymentMethodsSetupIntentAllowRedirects'
instance Eq PaymentFlowsAutomaticPaymentMethodsSetupIntentAllowRedirects'
instance FromJSON PaymentFlowsAutomaticPaymentMethodsSetupIntentAllowRedirects'
instance ToJSON PaymentFlowsAutomaticPaymentMethodsSetupIntentAllowRedirects'
