module StripeAPI.Types.PaymentLinksResourceConsentCollection where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceConsentCollection
instance Show PaymentLinksResourceConsentCollection
instance Eq PaymentLinksResourceConsentCollection
instance FromJSON PaymentLinksResourceConsentCollection
instance ToJSON PaymentLinksResourceConsentCollection
data PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance Show PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance Eq PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance FromJSON PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance ToJSON PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullable
data PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance Show PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance Eq PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance FromJSON PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance ToJSON PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
data PaymentLinksResourceConsentCollectionPromotions'NonNullable
instance Show PaymentLinksResourceConsentCollectionPromotions'NonNullable
instance Eq PaymentLinksResourceConsentCollectionPromotions'NonNullable
instance FromJSON PaymentLinksResourceConsentCollectionPromotions'NonNullable
instance ToJSON PaymentLinksResourceConsentCollectionPromotions'NonNullable
data PaymentLinksResourceConsentCollectionTermsOfService'NonNullable
instance Show PaymentLinksResourceConsentCollectionTermsOfService'NonNullable
instance Eq PaymentLinksResourceConsentCollectionTermsOfService'NonNullable
instance FromJSON PaymentLinksResourceConsentCollectionTermsOfService'NonNullable
instance ToJSON PaymentLinksResourceConsentCollectionTermsOfService'NonNullable
