module StripeAPI.Types.PaymentMethodOptionsCardInstallments where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsCardInstallments
instance Show PaymentMethodOptionsCardInstallments
instance Eq PaymentMethodOptionsCardInstallments
instance FromJSON PaymentMethodOptionsCardInstallments
instance ToJSON PaymentMethodOptionsCardInstallments
data PaymentMethodOptionsCardInstallmentsPlan'NonNullable
instance Show PaymentMethodOptionsCardInstallmentsPlan'NonNullable
instance Eq PaymentMethodOptionsCardInstallmentsPlan'NonNullable
instance FromJSON PaymentMethodOptionsCardInstallmentsPlan'NonNullable
instance ToJSON PaymentMethodOptionsCardInstallmentsPlan'NonNullable
data PaymentMethodOptionsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance Show PaymentMethodOptionsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance Eq PaymentMethodOptionsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance FromJSON PaymentMethodOptionsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance ToJSON PaymentMethodOptionsCardInstallmentsPlan'NonNullableInterval'NonNullable
data PaymentMethodOptionsCardInstallmentsPlan'NonNullableType'
instance Show PaymentMethodOptionsCardInstallmentsPlan'NonNullableType'
instance Eq PaymentMethodOptionsCardInstallmentsPlan'NonNullableType'
instance FromJSON PaymentMethodOptionsCardInstallmentsPlan'NonNullableType'
instance ToJSON PaymentMethodOptionsCardInstallmentsPlan'NonNullableType'
