module StripeAPI.Types.PaymentFlowsAmountDetailsResourceTip where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentFlowsAmountDetailsResourceTip
instance Show PaymentFlowsAmountDetailsResourceTip
instance Eq PaymentFlowsAmountDetailsResourceTip
instance FromJSON PaymentFlowsAmountDetailsResourceTip
instance ToJSON PaymentFlowsAmountDetailsResourceTip
