module StripeAPI.Types.PaymentMethodDetailsUsBankAccount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsUsBankAccount
instance Show PaymentMethodDetailsUsBankAccount
instance Eq PaymentMethodDetailsUsBankAccount
instance FromJSON PaymentMethodDetailsUsBankAccount
instance ToJSON PaymentMethodDetailsUsBankAccount
data PaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Show PaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Eq PaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance FromJSON PaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance ToJSON PaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
data PaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Show PaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Eq PaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance FromJSON PaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance ToJSON PaymentMethodDetailsUsBankAccountAccountType'NonNullable
