module StripeAPI.Types.PaymentLinksResourceShippingAddressCollection where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceShippingAddressCollection
instance Show PaymentLinksResourceShippingAddressCollection
instance Eq PaymentLinksResourceShippingAddressCollection
instance FromJSON PaymentLinksResourceShippingAddressCollection
instance ToJSON PaymentLinksResourceShippingAddressCollection
data PaymentLinksResourceShippingAddressCollectionAllowedCountries'
instance Show PaymentLinksResourceShippingAddressCollectionAllowedCountries'
instance Eq PaymentLinksResourceShippingAddressCollectionAllowedCountries'
instance FromJSON PaymentLinksResourceShippingAddressCollectionAllowedCountries'
instance ToJSON PaymentLinksResourceShippingAddressCollectionAllowedCountries'
