module StripeAPI.Types.PaymentPagesCheckoutSessionConsentCollection where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionConsentCollection
instance Show PaymentPagesCheckoutSessionConsentCollection
instance Eq PaymentPagesCheckoutSessionConsentCollection
instance FromJSON PaymentPagesCheckoutSessionConsentCollection
instance ToJSON PaymentPagesCheckoutSessionConsentCollection
data PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance Show PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance Eq PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance FromJSON PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance ToJSON PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullable
data PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance Show PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance Eq PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance FromJSON PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance ToJSON PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
data PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
instance Show PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
instance Eq PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
instance FromJSON PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
instance ToJSON PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
data PaymentPagesCheckoutSessionConsentCollectionTermsOfService'NonNullable
instance Show PaymentPagesCheckoutSessionConsentCollectionTermsOfService'NonNullable
instance Eq PaymentPagesCheckoutSessionConsentCollectionTermsOfService'NonNullable
instance FromJSON PaymentPagesCheckoutSessionConsentCollectionTermsOfService'NonNullable
instance ToJSON PaymentPagesCheckoutSessionConsentCollectionTermsOfService'NonNullable
