module StripeAPI.Types.PaymentPagesCheckoutSessionInvoiceSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionInvoiceSettings
instance Show PaymentPagesCheckoutSessionInvoiceSettings
instance Eq PaymentPagesCheckoutSessionInvoiceSettings
instance FromJSON PaymentPagesCheckoutSessionInvoiceSettings
instance ToJSON PaymentPagesCheckoutSessionInvoiceSettings
data PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Show PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Eq PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance FromJSON PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance ToJSON PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
data PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
instance Show PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
instance Eq PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
instance FromJSON PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
instance ToJSON PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
