module StripeAPI.Types.PaymentMethodDetailsBancontact where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodDetailsBancontact
instance Show PaymentMethodDetailsBancontact
instance Eq PaymentMethodDetailsBancontact
instance FromJSON PaymentMethodDetailsBancontact
instance ToJSON PaymentMethodDetailsBancontact
data PaymentMethodDetailsBancontactGeneratedSepaDebit'Variants
instance Show PaymentMethodDetailsBancontactGeneratedSepaDebit'Variants
instance Eq PaymentMethodDetailsBancontactGeneratedSepaDebit'Variants
instance FromJSON PaymentMethodDetailsBancontactGeneratedSepaDebit'Variants
instance ToJSON PaymentMethodDetailsBancontactGeneratedSepaDebit'Variants
data PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'Variants
instance Show PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'Variants
instance Eq PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'Variants
instance FromJSON PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'Variants
instance ToJSON PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'Variants
data PaymentMethodDetailsBancontactPreferredLanguage'
instance Show PaymentMethodDetailsBancontactPreferredLanguage'
instance Eq PaymentMethodDetailsBancontactPreferredLanguage'
instance FromJSON PaymentMethodDetailsBancontactPreferredLanguage'
instance ToJSON PaymentMethodDetailsBancontactPreferredLanguage'
