module StripeAPI.Types.PaymentMethodDetailsAchDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodDetailsAchDebit
instance Show PaymentMethodDetailsAchDebit
instance Eq PaymentMethodDetailsAchDebit
instance FromJSON PaymentMethodDetailsAchDebit
instance ToJSON PaymentMethodDetailsAchDebit
data PaymentMethodDetailsAchDebitAccountHolderType'
instance Show PaymentMethodDetailsAchDebitAccountHolderType'
instance Eq PaymentMethodDetailsAchDebitAccountHolderType'
instance FromJSON PaymentMethodDetailsAchDebitAccountHolderType'
instance ToJSON PaymentMethodDetailsAchDebitAccountHolderType'
