module StripeAPI.Types.PaymentMethodOptionsKonbini where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsKonbini
instance Show PaymentMethodOptionsKonbini
instance Eq PaymentMethodOptionsKonbini
instance FromJSON PaymentMethodOptionsKonbini
instance ToJSON PaymentMethodOptionsKonbini
data PaymentMethodOptionsKonbiniSetupFutureUsage'
instance Show PaymentMethodOptionsKonbiniSetupFutureUsage'
instance Eq PaymentMethodOptionsKonbiniSetupFutureUsage'
instance FromJSON PaymentMethodOptionsKonbiniSetupFutureUsage'
instance ToJSON PaymentMethodOptionsKonbiniSetupFutureUsage'
