module StripeAPI.Types.PaymentIntentPaymentMethodOptionsAcssDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsAcssDebit
instance Show PaymentIntentPaymentMethodOptionsAcssDebit
instance Eq PaymentIntentPaymentMethodOptionsAcssDebit
instance FromJSON PaymentIntentPaymentMethodOptionsAcssDebit
instance ToJSON PaymentIntentPaymentMethodOptionsAcssDebit
data PaymentIntentPaymentMethodOptionsAcssDebitSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsAcssDebitSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsAcssDebitSetupFutureUsage'
instance FromJSON PaymentIntentPaymentMethodOptionsAcssDebitSetupFutureUsage'
instance ToJSON PaymentIntentPaymentMethodOptionsAcssDebitSetupFutureUsage'
data PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Show PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Eq PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance FromJSON PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance ToJSON PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
