module StripeAPI.Types.PaymentMethodOptionsCustomerBalanceEuBankAccount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsCustomerBalanceEuBankAccount
instance Show PaymentMethodOptionsCustomerBalanceEuBankAccount
instance Eq PaymentMethodOptionsCustomerBalanceEuBankAccount
instance FromJSON PaymentMethodOptionsCustomerBalanceEuBankAccount
instance ToJSON PaymentMethodOptionsCustomerBalanceEuBankAccount
data PaymentMethodOptionsCustomerBalanceEuBankAccountCountry'
instance Show PaymentMethodOptionsCustomerBalanceEuBankAccountCountry'
instance Eq PaymentMethodOptionsCustomerBalanceEuBankAccountCountry'
instance FromJSON PaymentMethodOptionsCustomerBalanceEuBankAccountCountry'
instance ToJSON PaymentMethodOptionsCustomerBalanceEuBankAccountCountry'
