module StripeAPI.Types.PaymentLinksResourceCustomFieldsNumeric where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceCustomFieldsNumeric
instance Show PaymentLinksResourceCustomFieldsNumeric
instance Eq PaymentLinksResourceCustomFieldsNumeric
instance FromJSON PaymentLinksResourceCustomFieldsNumeric
instance ToJSON PaymentLinksResourceCustomFieldsNumeric
