module StripeAPI.Types.PaymentMethodCardWalletVisaCheckout where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodCardWalletVisaCheckout 
instance Show PaymentMethodCardWalletVisaCheckout 
instance Eq PaymentMethodCardWalletVisaCheckout 
instance FromJSON PaymentMethodCardWalletVisaCheckout 
instance ToJSON PaymentMethodCardWalletVisaCheckout 
data PaymentMethodCardWalletVisaCheckoutBillingAddress' 
instance Show PaymentMethodCardWalletVisaCheckoutBillingAddress' 
instance Eq PaymentMethodCardWalletVisaCheckoutBillingAddress' 
instance FromJSON PaymentMethodCardWalletVisaCheckoutBillingAddress' 
instance ToJSON PaymentMethodCardWalletVisaCheckoutBillingAddress' 
data PaymentMethodCardWalletVisaCheckoutShippingAddress' 
instance Show PaymentMethodCardWalletVisaCheckoutShippingAddress' 
instance Eq PaymentMethodCardWalletVisaCheckoutShippingAddress' 
instance FromJSON PaymentMethodCardWalletVisaCheckoutShippingAddress' 
instance ToJSON PaymentMethodCardWalletVisaCheckoutShippingAddress' 
