module StripeAPI.Types.PaymentIntentNextActionPaynowDisplayQrCode where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionPaynowDisplayQrCode
instance Show PaymentIntentNextActionPaynowDisplayQrCode
instance Eq PaymentIntentNextActionPaynowDisplayQrCode
instance FromJSON PaymentIntentNextActionPaynowDisplayQrCode
instance ToJSON PaymentIntentNextActionPaynowDisplayQrCode
