module StripeAPI.Types.PaymentIntentNextActionKonbiniStores where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionKonbiniStores
instance Show PaymentIntentNextActionKonbiniStores
instance Eq PaymentIntentNextActionKonbiniStores
instance FromJSON PaymentIntentNextActionKonbiniStores
instance ToJSON PaymentIntentNextActionKonbiniStores
data PaymentIntentNextActionKonbiniStoresFamilymart'NonNullable
instance Show PaymentIntentNextActionKonbiniStoresFamilymart'NonNullable
instance Eq PaymentIntentNextActionKonbiniStoresFamilymart'NonNullable
instance FromJSON PaymentIntentNextActionKonbiniStoresFamilymart'NonNullable
instance ToJSON PaymentIntentNextActionKonbiniStoresFamilymart'NonNullable
data PaymentIntentNextActionKonbiniStoresLawson'NonNullable
instance Show PaymentIntentNextActionKonbiniStoresLawson'NonNullable
instance Eq PaymentIntentNextActionKonbiniStoresLawson'NonNullable
instance FromJSON PaymentIntentNextActionKonbiniStoresLawson'NonNullable
instance ToJSON PaymentIntentNextActionKonbiniStoresLawson'NonNullable
data PaymentIntentNextActionKonbiniStoresMinistop'NonNullable
instance Show PaymentIntentNextActionKonbiniStoresMinistop'NonNullable
instance Eq PaymentIntentNextActionKonbiniStoresMinistop'NonNullable
instance FromJSON PaymentIntentNextActionKonbiniStoresMinistop'NonNullable
instance ToJSON PaymentIntentNextActionKonbiniStoresMinistop'NonNullable
data PaymentIntentNextActionKonbiniStoresSeicomart'NonNullable
instance Show PaymentIntentNextActionKonbiniStoresSeicomart'NonNullable
instance Eq PaymentIntentNextActionKonbiniStoresSeicomart'NonNullable
instance FromJSON PaymentIntentNextActionKonbiniStoresSeicomart'NonNullable
instance ToJSON PaymentIntentNextActionKonbiniStoresSeicomart'NonNullable
