module StripeAPI.Types.PaymentIntentNextActionPromptpayDisplayQrCode where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionPromptpayDisplayQrCode
instance Show PaymentIntentNextActionPromptpayDisplayQrCode
instance Eq PaymentIntentNextActionPromptpayDisplayQrCode
instance FromJSON PaymentIntentNextActionPromptpayDisplayQrCode
instance ToJSON PaymentIntentNextActionPromptpayDisplayQrCode
