module StripeAPI.Types.PaymentIntentNextActionPixDisplayQrCode where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionPixDisplayQrCode
instance Show PaymentIntentNextActionPixDisplayQrCode
instance Eq PaymentIntentNextActionPixDisplayQrCode
instance FromJSON PaymentIntentNextActionPixDisplayQrCode
instance ToJSON PaymentIntentNextActionPixDisplayQrCode
