module StripeAPI.Types.PaymentPagesCheckoutSessionCustomerDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentPagesCheckoutSessionCustomerDetails
instance Show PaymentPagesCheckoutSessionCustomerDetails
instance Eq PaymentPagesCheckoutSessionCustomerDetails
instance FromJSON PaymentPagesCheckoutSessionCustomerDetails
instance ToJSON PaymentPagesCheckoutSessionCustomerDetails
data PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'
instance Show PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'
instance Eq PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'
instance FromJSON PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'
instance ToJSON PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'
