module StripeAPI.Types.PaymentIntentNextActionKonbiniMinistop where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionKonbiniMinistop
instance Show PaymentIntentNextActionKonbiniMinistop
instance Eq PaymentIntentNextActionKonbiniMinistop
instance FromJSON PaymentIntentNextActionKonbiniMinistop
instance ToJSON PaymentIntentNextActionKonbiniMinistop
