module StripeAPI.Types.PaymentPagesCheckoutSessionTaxIdCollection where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionTaxIdCollection
instance Show PaymentPagesCheckoutSessionTaxIdCollection
instance Eq PaymentPagesCheckoutSessionTaxIdCollection
instance FromJSON PaymentPagesCheckoutSessionTaxIdCollection
instance ToJSON PaymentPagesCheckoutSessionTaxIdCollection
