module StripeAPI.Types.PaymentPagesCheckoutSessionConsent where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionConsent
instance Show PaymentPagesCheckoutSessionConsent
instance Eq PaymentPagesCheckoutSessionConsent
instance FromJSON PaymentPagesCheckoutSessionConsent
instance ToJSON PaymentPagesCheckoutSessionConsent
data PaymentPagesCheckoutSessionConsentPromotions'NonNullable
instance Show PaymentPagesCheckoutSessionConsentPromotions'NonNullable
instance Eq PaymentPagesCheckoutSessionConsentPromotions'NonNullable
instance FromJSON PaymentPagesCheckoutSessionConsentPromotions'NonNullable
instance ToJSON PaymentPagesCheckoutSessionConsentPromotions'NonNullable
data PaymentPagesCheckoutSessionConsentTermsOfService'NonNullable
instance Show PaymentPagesCheckoutSessionConsentTermsOfService'NonNullable
instance Eq PaymentPagesCheckoutSessionConsentTermsOfService'NonNullable
instance FromJSON PaymentPagesCheckoutSessionConsentTermsOfService'NonNullable
instance ToJSON PaymentPagesCheckoutSessionConsentTermsOfService'NonNullable
