module StripeAPI.Types.PaymentPagesCheckoutSessionAutomaticTax where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionAutomaticTax
instance Show PaymentPagesCheckoutSessionAutomaticTax
instance Eq PaymentPagesCheckoutSessionAutomaticTax
instance FromJSON PaymentPagesCheckoutSessionAutomaticTax
instance ToJSON PaymentPagesCheckoutSessionAutomaticTax
data PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
instance Show PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
instance Eq PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
instance FromJSON PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
instance ToJSON PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
