module StripeAPI.Types.PaymentMethodConfigResourceDisplayPreference where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodConfigResourceDisplayPreference
instance Show PaymentMethodConfigResourceDisplayPreference
instance Eq PaymentMethodConfigResourceDisplayPreference
instance FromJSON PaymentMethodConfigResourceDisplayPreference
instance ToJSON PaymentMethodConfigResourceDisplayPreference
data PaymentMethodConfigResourceDisplayPreferencePreference'
instance Show PaymentMethodConfigResourceDisplayPreferencePreference'
instance Eq PaymentMethodConfigResourceDisplayPreferencePreference'
instance FromJSON PaymentMethodConfigResourceDisplayPreferencePreference'
instance ToJSON PaymentMethodConfigResourceDisplayPreferencePreference'
data PaymentMethodConfigResourceDisplayPreferenceValue'
instance Show PaymentMethodConfigResourceDisplayPreferenceValue'
instance Eq PaymentMethodConfigResourceDisplayPreferenceValue'
instance FromJSON PaymentMethodConfigResourceDisplayPreferenceValue'
instance ToJSON PaymentMethodConfigResourceDisplayPreferenceValue'
