module StripeAPI.Types.PaymentMethodDetailsGrabpay where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodDetailsGrabpay
instance Show PaymentMethodDetailsGrabpay
instance Eq PaymentMethodDetailsGrabpay
instance FromJSON PaymentMethodDetailsGrabpay
instance ToJSON PaymentMethodDetailsGrabpay
