module StripeAPI.Types.PaymentLinksResourceCustomTextPosition where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceCustomTextPosition
instance Show PaymentLinksResourceCustomTextPosition
instance Eq PaymentLinksResourceCustomTextPosition
instance FromJSON PaymentLinksResourceCustomTextPosition
instance ToJSON PaymentLinksResourceCustomTextPosition
