module StripeAPI.Types.PaymentMethodDetailsInteracPresentReceipt where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsInteracPresentReceipt
instance Show PaymentMethodDetailsInteracPresentReceipt
instance Eq PaymentMethodDetailsInteracPresentReceipt
instance FromJSON PaymentMethodDetailsInteracPresentReceipt
instance ToJSON PaymentMethodDetailsInteracPresentReceipt
data PaymentMethodDetailsInteracPresentReceiptAccountType'
instance Show PaymentMethodDetailsInteracPresentReceiptAccountType'
instance Eq PaymentMethodDetailsInteracPresentReceiptAccountType'
instance FromJSON PaymentMethodDetailsInteracPresentReceiptAccountType'
instance ToJSON PaymentMethodDetailsInteracPresentReceiptAccountType'
