module StripeAPI.Types.PaymentPagesCheckoutSessionAfterExpiration where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionAfterExpiration
instance Show PaymentPagesCheckoutSessionAfterExpiration
instance Eq PaymentPagesCheckoutSessionAfterExpiration
instance FromJSON PaymentPagesCheckoutSessionAfterExpiration
instance ToJSON PaymentPagesCheckoutSessionAfterExpiration
data PaymentPagesCheckoutSessionAfterExpirationRecovery'NonNullable
instance Show PaymentPagesCheckoutSessionAfterExpirationRecovery'NonNullable
instance Eq PaymentPagesCheckoutSessionAfterExpirationRecovery'NonNullable
instance FromJSON PaymentPagesCheckoutSessionAfterExpirationRecovery'NonNullable
instance ToJSON PaymentPagesCheckoutSessionAfterExpirationRecovery'NonNullable
