module StripeAPI.Types.PaymentMethodOptionsCustomerBalance where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodOptionsCustomerBalance
instance Show PaymentMethodOptionsCustomerBalance
instance Eq PaymentMethodOptionsCustomerBalance
instance FromJSON PaymentMethodOptionsCustomerBalance
instance ToJSON PaymentMethodOptionsCustomerBalance
data PaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance Show PaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance Eq PaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance FromJSON PaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance ToJSON PaymentMethodOptionsCustomerBalanceFundingType'NonNullable
data PaymentMethodOptionsCustomerBalanceSetupFutureUsage'
instance Show PaymentMethodOptionsCustomerBalanceSetupFutureUsage'
instance Eq PaymentMethodOptionsCustomerBalanceSetupFutureUsage'
instance FromJSON PaymentMethodOptionsCustomerBalanceSetupFutureUsage'
instance ToJSON PaymentMethodOptionsCustomerBalanceSetupFutureUsage'
