module StripeAPI.Types.PaymentPagesCheckoutSessionShippingOption where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionShippingOption
instance Show PaymentPagesCheckoutSessionShippingOption
instance Eq PaymentPagesCheckoutSessionShippingOption
instance FromJSON PaymentPagesCheckoutSessionShippingOption
instance ToJSON PaymentPagesCheckoutSessionShippingOption
data PaymentPagesCheckoutSessionShippingOptionShippingRate'Variants
instance Show PaymentPagesCheckoutSessionShippingOptionShippingRate'Variants
instance Eq PaymentPagesCheckoutSessionShippingOptionShippingRate'Variants
instance FromJSON PaymentPagesCheckoutSessionShippingOptionShippingRate'Variants
instance ToJSON PaymentPagesCheckoutSessionShippingOptionShippingRate'Variants
