module StripeAPI.Types.PaymentMethodDetailsCardNetworkToken where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsCardNetworkToken
instance Show PaymentMethodDetailsCardNetworkToken
instance Eq PaymentMethodDetailsCardNetworkToken
instance FromJSON PaymentMethodDetailsCardNetworkToken
instance ToJSON PaymentMethodDetailsCardNetworkToken
