module StripeAPI.Types.PaymentIntentTypeSpecificPaymentMethodOptionsClient where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentTypeSpecificPaymentMethodOptionsClient
instance Show PaymentIntentTypeSpecificPaymentMethodOptionsClient
instance Eq PaymentIntentTypeSpecificPaymentMethodOptionsClient
instance FromJSON PaymentIntentTypeSpecificPaymentMethodOptionsClient
instance ToJSON PaymentIntentTypeSpecificPaymentMethodOptionsClient
data PaymentIntentTypeSpecificPaymentMethodOptionsClientCaptureMethod'
instance Show PaymentIntentTypeSpecificPaymentMethodOptionsClientCaptureMethod'
instance Eq PaymentIntentTypeSpecificPaymentMethodOptionsClientCaptureMethod'
instance FromJSON PaymentIntentTypeSpecificPaymentMethodOptionsClientCaptureMethod'
instance ToJSON PaymentIntentTypeSpecificPaymentMethodOptionsClientCaptureMethod'
data PaymentIntentTypeSpecificPaymentMethodOptionsClientSetupFutureUsage'
instance Show PaymentIntentTypeSpecificPaymentMethodOptionsClientSetupFutureUsage'
instance Eq PaymentIntentTypeSpecificPaymentMethodOptionsClientSetupFutureUsage'
instance FromJSON PaymentIntentTypeSpecificPaymentMethodOptionsClientSetupFutureUsage'
instance ToJSON PaymentIntentTypeSpecificPaymentMethodOptionsClientSetupFutureUsage'
data PaymentIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance Show PaymentIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance Eq PaymentIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance FromJSON PaymentIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance ToJSON PaymentIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
