module StripeAPI.Types.PaymentLinksResourceInvoiceCreation where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceInvoiceCreation
instance Show PaymentLinksResourceInvoiceCreation
instance Eq PaymentLinksResourceInvoiceCreation
instance FromJSON PaymentLinksResourceInvoiceCreation
instance ToJSON PaymentLinksResourceInvoiceCreation
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
instance Show PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
instance Eq PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
instance FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
instance ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants
instance Show PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants
instance Eq PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants
instance FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants
instance ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
instance Show PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
instance Eq PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
instance FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
instance ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
