module StripeAPI.Types.PaymentMethodDetailsCard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsCard
instance Show PaymentMethodDetailsCard
instance Eq PaymentMethodDetailsCard
instance FromJSON PaymentMethodDetailsCard
instance ToJSON PaymentMethodDetailsCard
data PaymentMethodDetailsCardChecks'NonNullable
instance Show PaymentMethodDetailsCardChecks'NonNullable
instance Eq PaymentMethodDetailsCardChecks'NonNullable
instance FromJSON PaymentMethodDetailsCardChecks'NonNullable
instance ToJSON PaymentMethodDetailsCardChecks'NonNullable
data PaymentMethodDetailsCardInstallments'NonNullable
instance Show PaymentMethodDetailsCardInstallments'NonNullable
instance Eq PaymentMethodDetailsCardInstallments'NonNullable
instance FromJSON PaymentMethodDetailsCardInstallments'NonNullable
instance ToJSON PaymentMethodDetailsCardInstallments'NonNullable
data PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullable
instance Show PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullable
instance Eq PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullable
instance FromJSON PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullable
instance ToJSON PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullable
data PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullableInterval'NonNullable
instance Show PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullableInterval'NonNullable
instance Eq PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullableInterval'NonNullable
instance FromJSON PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullableInterval'NonNullable
instance ToJSON PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullableInterval'NonNullable
data PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullableType'
instance Show PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullableType'
instance Eq PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullableType'
instance FromJSON PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullableType'
instance ToJSON PaymentMethodDetailsCardInstallments'NonNullablePlan'NonNullableType'
data PaymentMethodDetailsCardNetworkToken'NonNullable
instance Show PaymentMethodDetailsCardNetworkToken'NonNullable
instance Eq PaymentMethodDetailsCardNetworkToken'NonNullable
instance FromJSON PaymentMethodDetailsCardNetworkToken'NonNullable
instance ToJSON PaymentMethodDetailsCardNetworkToken'NonNullable
data PaymentMethodDetailsCardThreeDSecure'NonNullable
instance Show PaymentMethodDetailsCardThreeDSecure'NonNullable
instance Eq PaymentMethodDetailsCardThreeDSecure'NonNullable
instance FromJSON PaymentMethodDetailsCardThreeDSecure'NonNullable
instance ToJSON PaymentMethodDetailsCardThreeDSecure'NonNullable
data PaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
instance Show PaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
instance Eq PaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
instance FromJSON PaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
instance ToJSON PaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
data PaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
instance Show PaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
instance Eq PaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
instance FromJSON PaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
instance ToJSON PaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
data PaymentMethodDetailsCardThreeDSecure'NonNullableExemptionIndicator'NonNullable
instance Show PaymentMethodDetailsCardThreeDSecure'NonNullableExemptionIndicator'NonNullable
instance Eq PaymentMethodDetailsCardThreeDSecure'NonNullableExemptionIndicator'NonNullable
instance FromJSON PaymentMethodDetailsCardThreeDSecure'NonNullableExemptionIndicator'NonNullable
instance ToJSON PaymentMethodDetailsCardThreeDSecure'NonNullableExemptionIndicator'NonNullable
data PaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
instance Show PaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
instance Eq PaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
instance FromJSON PaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
instance ToJSON PaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
data PaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
instance Show PaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
instance Eq PaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
instance FromJSON PaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
instance ToJSON PaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
data PaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
instance Show PaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
instance Eq PaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
instance FromJSON PaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
instance ToJSON PaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
data PaymentMethodDetailsCardWallet'NonNullable
instance Show PaymentMethodDetailsCardWallet'NonNullable
instance Eq PaymentMethodDetailsCardWallet'NonNullable
instance FromJSON PaymentMethodDetailsCardWallet'NonNullable
instance ToJSON PaymentMethodDetailsCardWallet'NonNullable
data PaymentMethodDetailsCardWallet'NonNullableType'
instance Show PaymentMethodDetailsCardWallet'NonNullableType'
instance Eq PaymentMethodDetailsCardWallet'NonNullableType'
instance FromJSON PaymentMethodDetailsCardWallet'NonNullableType'
instance ToJSON PaymentMethodDetailsCardWallet'NonNullableType'
