module StripeAPI.Types.PaymentPagesCheckoutSessionShippingAddressCollection where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionShippingAddressCollection
instance Show PaymentPagesCheckoutSessionShippingAddressCollection
instance Eq PaymentPagesCheckoutSessionShippingAddressCollection
instance FromJSON PaymentPagesCheckoutSessionShippingAddressCollection
instance ToJSON PaymentPagesCheckoutSessionShippingAddressCollection
data PaymentPagesCheckoutSessionShippingAddressCollectionAllowedCountries'
instance Show PaymentPagesCheckoutSessionShippingAddressCollectionAllowedCountries'
instance Eq PaymentPagesCheckoutSessionShippingAddressCollectionAllowedCountries'
instance FromJSON PaymentPagesCheckoutSessionShippingAddressCollectionAllowedCountries'
instance ToJSON PaymentPagesCheckoutSessionShippingAddressCollectionAllowedCountries'
