module StripeAPI.Types.PaymentIntentPaymentMethodOptionsSepaDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentIntentPaymentMethodOptionsSepaDebit
instance Show PaymentIntentPaymentMethodOptionsSepaDebit
instance Eq PaymentIntentPaymentMethodOptionsSepaDebit
instance FromJSON PaymentIntentPaymentMethodOptionsSepaDebit
instance ToJSON PaymentIntentPaymentMethodOptionsSepaDebit
