module StripeAPI.Types.PaymentMethodDetailsIdeal where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodDetailsIdeal
instance Show PaymentMethodDetailsIdeal
instance Eq PaymentMethodDetailsIdeal
instance FromJSON PaymentMethodDetailsIdeal
instance ToJSON PaymentMethodDetailsIdeal
data PaymentMethodDetailsIdealBank'
instance Show PaymentMethodDetailsIdealBank'
instance Eq PaymentMethodDetailsIdealBank'
instance FromJSON PaymentMethodDetailsIdealBank'
instance ToJSON PaymentMethodDetailsIdealBank'
data PaymentMethodDetailsIdealBic'
instance Show PaymentMethodDetailsIdealBic'
instance Eq PaymentMethodDetailsIdealBic'
instance FromJSON PaymentMethodDetailsIdealBic'
instance ToJSON PaymentMethodDetailsIdealBic'
data PaymentMethodDetailsIdealGeneratedSepaDebit'Variants
instance Show PaymentMethodDetailsIdealGeneratedSepaDebit'Variants
instance Eq PaymentMethodDetailsIdealGeneratedSepaDebit'Variants
instance FromJSON PaymentMethodDetailsIdealGeneratedSepaDebit'Variants
instance ToJSON PaymentMethodDetailsIdealGeneratedSepaDebit'Variants
data PaymentMethodDetailsIdealGeneratedSepaDebitMandate'Variants
instance Show PaymentMethodDetailsIdealGeneratedSepaDebitMandate'Variants
instance Eq PaymentMethodDetailsIdealGeneratedSepaDebitMandate'Variants
instance FromJSON PaymentMethodDetailsIdealGeneratedSepaDebitMandate'Variants
instance ToJSON PaymentMethodDetailsIdealGeneratedSepaDebitMandate'Variants
