module StripeAPI.Types.PaymentLinksResourceSubscriptionData where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceSubscriptionData
instance Show PaymentLinksResourceSubscriptionData
instance Eq PaymentLinksResourceSubscriptionData
instance FromJSON PaymentLinksResourceSubscriptionData
instance ToJSON PaymentLinksResourceSubscriptionData
