module StripeAPI.Types.PaymentMethodDetailsAuBecsDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodDetailsAuBecsDebit
instance Show PaymentMethodDetailsAuBecsDebit
instance Eq PaymentMethodDetailsAuBecsDebit
instance FromJSON PaymentMethodDetailsAuBecsDebit
instance ToJSON PaymentMethodDetailsAuBecsDebit
