module StripeAPI.Types.PaymentIntentCardProcessing where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentCardProcessing
instance Show PaymentIntentCardProcessing
instance Eq PaymentIntentCardProcessing
instance FromJSON PaymentIntentCardProcessing
instance ToJSON PaymentIntentCardProcessing
