module StripeAPI.Types.PaymentMethodDetailsCardWalletMasterpass where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodDetailsCardWalletMasterpass 
instance Show PaymentMethodDetailsCardWalletMasterpass 
instance Eq PaymentMethodDetailsCardWalletMasterpass 
instance FromJSON PaymentMethodDetailsCardWalletMasterpass 
instance ToJSON PaymentMethodDetailsCardWalletMasterpass 
data PaymentMethodDetailsCardWalletMasterpassBillingAddress' 
instance Show PaymentMethodDetailsCardWalletMasterpassBillingAddress' 
instance Eq PaymentMethodDetailsCardWalletMasterpassBillingAddress' 
instance FromJSON PaymentMethodDetailsCardWalletMasterpassBillingAddress' 
instance ToJSON PaymentMethodDetailsCardWalletMasterpassBillingAddress' 
data PaymentMethodDetailsCardWalletMasterpassShippingAddress' 
instance Show PaymentMethodDetailsCardWalletMasterpassShippingAddress' 
instance Eq PaymentMethodDetailsCardWalletMasterpassShippingAddress' 
instance FromJSON PaymentMethodDetailsCardWalletMasterpassShippingAddress' 
instance ToJSON PaymentMethodDetailsCardWalletMasterpassShippingAddress' 
