module StripeAPI.Types.PaymentLinksResourceCustomFieldsDropdownOption where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceCustomFieldsDropdownOption
instance Show PaymentLinksResourceCustomFieldsDropdownOption
instance Eq PaymentLinksResourceCustomFieldsDropdownOption
instance FromJSON PaymentLinksResourceCustomFieldsDropdownOption
instance ToJSON PaymentLinksResourceCustomFieldsDropdownOption
