module StripeAPI.Types.PaymentLinksResourceCustomFieldsText where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceCustomFieldsText
instance Show PaymentLinksResourceCustomFieldsText
instance Eq PaymentLinksResourceCustomFieldsText
instance FromJSON PaymentLinksResourceCustomFieldsText
instance ToJSON PaymentLinksResourceCustomFieldsText
