module StripeAPI.Types.PaymentFlowsPrivatePaymentMethodsAlipayDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentFlowsPrivatePaymentMethodsAlipayDetails
instance Show PaymentFlowsPrivatePaymentMethodsAlipayDetails
instance Eq PaymentFlowsPrivatePaymentMethodsAlipayDetails
instance FromJSON PaymentFlowsPrivatePaymentMethodsAlipayDetails
instance ToJSON PaymentFlowsPrivatePaymentMethodsAlipayDetails
