module StripeAPI.Types.PaymentMethodDetailsCardWalletVisaCheckout where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodDetailsCardWalletVisaCheckout 
instance Show PaymentMethodDetailsCardWalletVisaCheckout 
instance Eq PaymentMethodDetailsCardWalletVisaCheckout 
instance FromJSON PaymentMethodDetailsCardWalletVisaCheckout 
instance ToJSON PaymentMethodDetailsCardWalletVisaCheckout 
data PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress' 
instance Show PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress' 
instance Eq PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress' 
instance FromJSON PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress' 
instance ToJSON PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress' 
data PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress' 
instance Show PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress' 
instance Eq PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress' 
instance FromJSON PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress' 
instance ToJSON PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress' 
