module StripeAPI.Types.PaymentPagesCheckoutSessionCustomerDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionCustomerDetails
instance Show PaymentPagesCheckoutSessionCustomerDetails
instance Eq PaymentPagesCheckoutSessionCustomerDetails
instance FromJSON PaymentPagesCheckoutSessionCustomerDetails
instance ToJSON PaymentPagesCheckoutSessionCustomerDetails
data PaymentPagesCheckoutSessionCustomerDetailsAddress'NonNullable
instance Show PaymentPagesCheckoutSessionCustomerDetailsAddress'NonNullable
instance Eq PaymentPagesCheckoutSessionCustomerDetailsAddress'NonNullable
instance FromJSON PaymentPagesCheckoutSessionCustomerDetailsAddress'NonNullable
instance ToJSON PaymentPagesCheckoutSessionCustomerDetailsAddress'NonNullable
data PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'NonNullable
instance Show PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'NonNullable
instance Eq PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'NonNullable
instance FromJSON PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'NonNullable
instance ToJSON PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'NonNullable
