module StripeAPI.Types.PaymentPagesCheckoutSessionCustomFieldsLabel where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionCustomFieldsLabel
instance Show PaymentPagesCheckoutSessionCustomFieldsLabel
instance Eq PaymentPagesCheckoutSessionCustomFieldsLabel
instance FromJSON PaymentPagesCheckoutSessionCustomFieldsLabel
instance ToJSON PaymentPagesCheckoutSessionCustomFieldsLabel
