module StripeAPI.Types.PaymentMethodOptionsCardInstallments where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodOptionsCardInstallments
instance Show PaymentMethodOptionsCardInstallments
instance Eq PaymentMethodOptionsCardInstallments
instance FromJSON PaymentMethodOptionsCardInstallments
instance ToJSON PaymentMethodOptionsCardInstallments
data PaymentMethodOptionsCardInstallmentsPlan'
instance Show PaymentMethodOptionsCardInstallmentsPlan'
instance Eq PaymentMethodOptionsCardInstallmentsPlan'
instance FromJSON PaymentMethodOptionsCardInstallmentsPlan'
instance ToJSON PaymentMethodOptionsCardInstallmentsPlan'
