module StripeAPI.Types.PaymentMethodDomainResourcePaymentMethodStatus where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDomainResourcePaymentMethodStatus
instance Show PaymentMethodDomainResourcePaymentMethodStatus
instance Eq PaymentMethodDomainResourcePaymentMethodStatus
instance FromJSON PaymentMethodDomainResourcePaymentMethodStatus
instance ToJSON PaymentMethodDomainResourcePaymentMethodStatus
data PaymentMethodDomainResourcePaymentMethodStatusStatus'
instance Show PaymentMethodDomainResourcePaymentMethodStatusStatus'
instance Eq PaymentMethodDomainResourcePaymentMethodStatusStatus'
instance FromJSON PaymentMethodDomainResourcePaymentMethodStatusStatus'
instance ToJSON PaymentMethodDomainResourcePaymentMethodStatusStatus'
