module StripeAPI.Types.PaymentMethodDetailsCardPresent where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodDetailsCardPresent
instance Show PaymentMethodDetailsCardPresent
instance Eq PaymentMethodDetailsCardPresent
instance FromJSON PaymentMethodDetailsCardPresent
instance ToJSON PaymentMethodDetailsCardPresent
data PaymentMethodDetailsCardPresentReadMethod'
instance Show PaymentMethodDetailsCardPresentReadMethod'
instance Eq PaymentMethodDetailsCardPresentReadMethod'
instance FromJSON PaymentMethodDetailsCardPresentReadMethod'
instance ToJSON PaymentMethodDetailsCardPresentReadMethod'
data PaymentMethodDetailsCardPresentReceipt'
instance Show PaymentMethodDetailsCardPresentReceipt'
instance Eq PaymentMethodDetailsCardPresentReceipt'
instance FromJSON PaymentMethodDetailsCardPresentReceipt'
instance ToJSON PaymentMethodDetailsCardPresentReceipt'
data PaymentMethodDetailsCardPresentReceipt'AccountType'
instance Show PaymentMethodDetailsCardPresentReceipt'AccountType'
instance Eq PaymentMethodDetailsCardPresentReceipt'AccountType'
instance FromJSON PaymentMethodDetailsCardPresentReceipt'AccountType'
instance ToJSON PaymentMethodDetailsCardPresentReceipt'AccountType'
