module StripeAPI.Types.PaymentPagesCheckoutSessionPaymentMethodReuseAgreement where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionPaymentMethodReuseAgreement
instance Show PaymentPagesCheckoutSessionPaymentMethodReuseAgreement
instance Eq PaymentPagesCheckoutSessionPaymentMethodReuseAgreement
instance FromJSON PaymentPagesCheckoutSessionPaymentMethodReuseAgreement
instance ToJSON PaymentPagesCheckoutSessionPaymentMethodReuseAgreement
data PaymentPagesCheckoutSessionPaymentMethodReuseAgreementPosition'
instance Show PaymentPagesCheckoutSessionPaymentMethodReuseAgreementPosition'
instance Eq PaymentPagesCheckoutSessionPaymentMethodReuseAgreementPosition'
instance FromJSON PaymentPagesCheckoutSessionPaymentMethodReuseAgreementPosition'
instance ToJSON PaymentPagesCheckoutSessionPaymentMethodReuseAgreementPosition'
