module StripeAPI.Types.PaymentMethodDetailsSofort where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PaymentMethodDetailsSofort
instance Show PaymentMethodDetailsSofort
instance Eq PaymentMethodDetailsSofort
instance FromJSON PaymentMethodDetailsSofort
instance ToJSON PaymentMethodDetailsSofort
data PaymentMethodDetailsSofortGeneratedSepaDebit'Variants
instance Show PaymentMethodDetailsSofortGeneratedSepaDebit'Variants
instance Eq PaymentMethodDetailsSofortGeneratedSepaDebit'Variants
instance FromJSON PaymentMethodDetailsSofortGeneratedSepaDebit'Variants
instance ToJSON PaymentMethodDetailsSofortGeneratedSepaDebit'Variants
data PaymentMethodDetailsSofortGeneratedSepaDebitMandate'Variants
instance Show PaymentMethodDetailsSofortGeneratedSepaDebitMandate'Variants
instance Eq PaymentMethodDetailsSofortGeneratedSepaDebitMandate'Variants
instance FromJSON PaymentMethodDetailsSofortGeneratedSepaDebitMandate'Variants
instance ToJSON PaymentMethodDetailsSofortGeneratedSepaDebitMandate'Variants
data PaymentMethodDetailsSofortPreferredLanguage'
instance Show PaymentMethodDetailsSofortPreferredLanguage'
instance Eq PaymentMethodDetailsSofortPreferredLanguage'
instance FromJSON PaymentMethodDetailsSofortPreferredLanguage'
instance ToJSON PaymentMethodDetailsSofortPreferredLanguage'
