module StripeAPI.Types.PaymentPagesCheckoutSessionInvoiceCreation where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionInvoiceCreation
instance Show PaymentPagesCheckoutSessionInvoiceCreation
instance Eq PaymentPagesCheckoutSessionInvoiceCreation
instance FromJSON PaymentPagesCheckoutSessionInvoiceCreation
instance ToJSON PaymentPagesCheckoutSessionInvoiceCreation
