module StripeAPI.Types.PaymentMethodDetailsBancontact where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsBancontact
instance Show PaymentMethodDetailsBancontact
instance Eq PaymentMethodDetailsBancontact
instance FromJSON PaymentMethodDetailsBancontact
instance ToJSON PaymentMethodDetailsBancontact
data PaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance Show PaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance Eq PaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance FromJSON PaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance ToJSON PaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
data PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance Show PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance Eq PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance FromJSON PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance ToJSON PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
data PaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance Show PaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance Eq PaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance FromJSON PaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance ToJSON PaymentMethodDetailsBancontactPreferredLanguage'NonNullable
