module StripeAPI.Types.PaymentIntentNextActionRedirectToUrl where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentIntentNextActionRedirectToUrl
instance Show PaymentIntentNextActionRedirectToUrl
instance Eq PaymentIntentNextActionRedirectToUrl
instance FromJSON PaymentIntentNextActionRedirectToUrl
instance ToJSON PaymentIntentNextActionRedirectToUrl
