module StripeAPI.Types.PaymentMethodDetailsWechatPay where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsWechatPay
instance Show PaymentMethodDetailsWechatPay
instance Eq PaymentMethodDetailsWechatPay
instance FromJSON PaymentMethodDetailsWechatPay
instance ToJSON PaymentMethodDetailsWechatPay
