module StripeAPI.Types.PaymentMethodDetailsCardWalletVisaCheckout where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentMethodDetailsCardWalletVisaCheckout
instance Show PaymentMethodDetailsCardWalletVisaCheckout
instance Eq PaymentMethodDetailsCardWalletVisaCheckout
instance FromJSON PaymentMethodDetailsCardWalletVisaCheckout
instance ToJSON PaymentMethodDetailsCardWalletVisaCheckout
data PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress'NonNullable
instance Show PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress'NonNullable
instance Eq PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress'NonNullable
instance FromJSON PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress'NonNullable
instance ToJSON PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress'NonNullable
data PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress'NonNullable
instance Show PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress'NonNullable
instance Eq PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress'NonNullable
instance FromJSON PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress'NonNullable
instance ToJSON PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress'NonNullable
