module StripeAPI.Types.PaymentLinksResourceSubscriptionData where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourceSubscriptionData
instance Show PaymentLinksResourceSubscriptionData
instance Eq PaymentLinksResourceSubscriptionData
instance FromJSON PaymentLinksResourceSubscriptionData
instance ToJSON PaymentLinksResourceSubscriptionData
data PaymentLinksResourceSubscriptionDataTrialSettings'NonNullable
instance Show PaymentLinksResourceSubscriptionDataTrialSettings'NonNullable
instance Eq PaymentLinksResourceSubscriptionDataTrialSettings'NonNullable
instance FromJSON PaymentLinksResourceSubscriptionDataTrialSettings'NonNullable
instance ToJSON PaymentLinksResourceSubscriptionDataTrialSettings'NonNullable
