module StripeAPI.Types.PaymentLinksResourcePaymentIntentData where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PaymentLinksResourcePaymentIntentData
instance Show PaymentLinksResourcePaymentIntentData
instance Eq PaymentLinksResourcePaymentIntentData
instance FromJSON PaymentLinksResourcePaymentIntentData
instance ToJSON PaymentLinksResourcePaymentIntentData
data PaymentLinksResourcePaymentIntentDataCaptureMethod'NonNullable
instance Show PaymentLinksResourcePaymentIntentDataCaptureMethod'NonNullable
instance Eq PaymentLinksResourcePaymentIntentDataCaptureMethod'NonNullable
instance FromJSON PaymentLinksResourcePaymentIntentDataCaptureMethod'NonNullable
instance ToJSON PaymentLinksResourcePaymentIntentDataCaptureMethod'NonNullable
data PaymentLinksResourcePaymentIntentDataSetupFutureUsage'NonNullable
instance Show PaymentLinksResourcePaymentIntentDataSetupFutureUsage'NonNullable
instance Eq PaymentLinksResourcePaymentIntentDataSetupFutureUsage'NonNullable
instance FromJSON PaymentLinksResourcePaymentIntentDataSetupFutureUsage'NonNullable
instance ToJSON PaymentLinksResourcePaymentIntentDataSetupFutureUsage'NonNullable
