module StripeAPI.Types.PersonFutureRequirements where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PersonFutureRequirements
instance Show PersonFutureRequirements
instance Eq PersonFutureRequirements
instance FromJSON PersonFutureRequirements
instance ToJSON PersonFutureRequirements
