module StripeAPI.Types.PortalFlowsAfterCompletionHostedConfirmation where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PortalFlowsAfterCompletionHostedConfirmation
instance Show PortalFlowsAfterCompletionHostedConfirmation
instance Eq PortalFlowsAfterCompletionHostedConfirmation
instance FromJSON PortalFlowsAfterCompletionHostedConfirmation
instance ToJSON PortalFlowsAfterCompletionHostedConfirmation
