module StripeAPI.Types.PortalFlowsSubscriptionUpdateConfirmDiscount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PortalFlowsSubscriptionUpdateConfirmDiscount
instance Show PortalFlowsSubscriptionUpdateConfirmDiscount
instance Eq PortalFlowsSubscriptionUpdateConfirmDiscount
instance FromJSON PortalFlowsSubscriptionUpdateConfirmDiscount
instance ToJSON PortalFlowsSubscriptionUpdateConfirmDiscount
