module StripeAPI.Types.PortalPaymentMethodUpdate where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PortalPaymentMethodUpdate
instance Show PortalPaymentMethodUpdate
instance Eq PortalPaymentMethodUpdate
instance FromJSON PortalPaymentMethodUpdate
instance ToJSON PortalPaymentMethodUpdate
