module StripeAPI.Types.PortalSubscriptionCancellationReason where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PortalSubscriptionCancellationReason
instance Show PortalSubscriptionCancellationReason
instance Eq PortalSubscriptionCancellationReason
instance FromJSON PortalSubscriptionCancellationReason
instance ToJSON PortalSubscriptionCancellationReason
data PortalSubscriptionCancellationReasonOptions'
instance Show PortalSubscriptionCancellationReasonOptions'
instance Eq PortalSubscriptionCancellationReasonOptions'
instance FromJSON PortalSubscriptionCancellationReasonOptions'
instance ToJSON PortalSubscriptionCancellationReasonOptions'
