module StripeAPI.Types.PortalFlowsFlowSubscriptionCancel where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PortalFlowsFlowSubscriptionCancel
instance Show PortalFlowsFlowSubscriptionCancel
instance Eq PortalFlowsFlowSubscriptionCancel
instance FromJSON PortalFlowsFlowSubscriptionCancel
instance ToJSON PortalFlowsFlowSubscriptionCancel
data PortalFlowsFlowSubscriptionCancelRetention'NonNullable
instance Show PortalFlowsFlowSubscriptionCancelRetention'NonNullable
instance Eq PortalFlowsFlowSubscriptionCancelRetention'NonNullable
instance FromJSON PortalFlowsFlowSubscriptionCancelRetention'NonNullable
instance ToJSON PortalFlowsFlowSubscriptionCancelRetention'NonNullable
data PortalFlowsFlowSubscriptionCancelRetention'NonNullableCouponOffer'NonNullable
instance Show PortalFlowsFlowSubscriptionCancelRetention'NonNullableCouponOffer'NonNullable
instance Eq PortalFlowsFlowSubscriptionCancelRetention'NonNullableCouponOffer'NonNullable
instance FromJSON PortalFlowsFlowSubscriptionCancelRetention'NonNullableCouponOffer'NonNullable
instance ToJSON PortalFlowsFlowSubscriptionCancelRetention'NonNullableCouponOffer'NonNullable
data PortalFlowsFlowSubscriptionCancelRetention'NonNullableType'
instance Show PortalFlowsFlowSubscriptionCancelRetention'NonNullableType'
instance Eq PortalFlowsFlowSubscriptionCancelRetention'NonNullableType'
instance FromJSON PortalFlowsFlowSubscriptionCancelRetention'NonNullableType'
instance ToJSON PortalFlowsFlowSubscriptionCancelRetention'NonNullableType'
