module StripeAPI.Types.PortalFlowsFlow where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PortalFlowsFlow
instance Show PortalFlowsFlow
instance Eq PortalFlowsFlow
instance FromJSON PortalFlowsFlow
instance ToJSON PortalFlowsFlow
data PortalFlowsFlowSubscriptionCancel'NonNullable
instance Show PortalFlowsFlowSubscriptionCancel'NonNullable
instance Eq PortalFlowsFlowSubscriptionCancel'NonNullable
instance FromJSON PortalFlowsFlowSubscriptionCancel'NonNullable
instance ToJSON PortalFlowsFlowSubscriptionCancel'NonNullable
data PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullable
instance Show PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullable
instance Eq PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullable
instance FromJSON PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullable
instance ToJSON PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullable
data PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableCouponOffer'NonNullable
instance Show PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableCouponOffer'NonNullable
instance Eq PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableCouponOffer'NonNullable
instance FromJSON PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableCouponOffer'NonNullable
instance ToJSON PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableCouponOffer'NonNullable
data PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableType'
instance Show PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableType'
instance Eq PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableType'
instance FromJSON PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableType'
instance ToJSON PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableType'
data PortalFlowsFlowSubscriptionUpdate'NonNullable
instance Show PortalFlowsFlowSubscriptionUpdate'NonNullable
instance Eq PortalFlowsFlowSubscriptionUpdate'NonNullable
instance FromJSON PortalFlowsFlowSubscriptionUpdate'NonNullable
instance ToJSON PortalFlowsFlowSubscriptionUpdate'NonNullable
data PortalFlowsFlowSubscriptionUpdateConfirm'NonNullable
instance Show PortalFlowsFlowSubscriptionUpdateConfirm'NonNullable
instance Eq PortalFlowsFlowSubscriptionUpdateConfirm'NonNullable
instance FromJSON PortalFlowsFlowSubscriptionUpdateConfirm'NonNullable
instance ToJSON PortalFlowsFlowSubscriptionUpdateConfirm'NonNullable
data PortalFlowsFlowType'
instance Show PortalFlowsFlowType'
instance Eq PortalFlowsFlowType'
instance FromJSON PortalFlowsFlowType'
instance ToJSON PortalFlowsFlowType'
