module StripeAPI.Types.PortalSubscriptionPause where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PortalSubscriptionPause
instance Show PortalSubscriptionPause
instance Eq PortalSubscriptionPause
instance FromJSON PortalSubscriptionPause
instance ToJSON PortalSubscriptionPause
