module StripeAPI.Types.PortalFlowsFlowAfterCompletion where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data PortalFlowsFlowAfterCompletion
instance Show PortalFlowsFlowAfterCompletion
instance Eq PortalFlowsFlowAfterCompletion
instance FromJSON PortalFlowsFlowAfterCompletion
instance ToJSON PortalFlowsFlowAfterCompletion
data PortalFlowsFlowAfterCompletionHostedConfirmation'NonNullable
instance Show PortalFlowsFlowAfterCompletionHostedConfirmation'NonNullable
instance Eq PortalFlowsFlowAfterCompletionHostedConfirmation'NonNullable
instance FromJSON PortalFlowsFlowAfterCompletionHostedConfirmation'NonNullable
instance ToJSON PortalFlowsFlowAfterCompletionHostedConfirmation'NonNullable
data PortalFlowsFlowAfterCompletionRedirect'NonNullable
instance Show PortalFlowsFlowAfterCompletionRedirect'NonNullable
instance Eq PortalFlowsFlowAfterCompletionRedirect'NonNullable
instance FromJSON PortalFlowsFlowAfterCompletionRedirect'NonNullable
instance ToJSON PortalFlowsFlowAfterCompletionRedirect'NonNullable
data PortalFlowsFlowAfterCompletionType'
instance Show PortalFlowsFlowAfterCompletionType'
instance Eq PortalFlowsFlowAfterCompletionType'
instance FromJSON PortalFlowsFlowAfterCompletionType'
instance ToJSON PortalFlowsFlowAfterCompletionType'
