module StripeAPI.Types.PromotionCodesResourceRestrictions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data PromotionCodesResourceRestrictions
instance Show PromotionCodesResourceRestrictions
instance Eq PromotionCodesResourceRestrictions
instance FromJSON PromotionCodesResourceRestrictions
instance ToJSON PromotionCodesResourceRestrictions
