module StripeAPI.Types.QuotesResourceSubscriptionDataSubscriptionData where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data QuotesResourceSubscriptionDataSubscriptionData
instance Show QuotesResourceSubscriptionDataSubscriptionData
instance Eq QuotesResourceSubscriptionDataSubscriptionData
instance FromJSON QuotesResourceSubscriptionDataSubscriptionData
instance ToJSON QuotesResourceSubscriptionDataSubscriptionData
