module StripeAPI.Types.ReceivedCreditsResourceTreasurySourceFlowsDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data ReceivedCreditsResourceTreasurySourceFlowsDetails
instance Show ReceivedCreditsResourceTreasurySourceFlowsDetails
instance Eq ReceivedCreditsResourceTreasurySourceFlowsDetails
instance FromJSON ReceivedCreditsResourceTreasurySourceFlowsDetails
instance ToJSON ReceivedCreditsResourceTreasurySourceFlowsDetails
data ReceivedCreditsResourceTreasurySourceFlowsDetailsType'
instance Show ReceivedCreditsResourceTreasurySourceFlowsDetailsType'
instance Eq ReceivedCreditsResourceTreasurySourceFlowsDetailsType'
instance FromJSON ReceivedCreditsResourceTreasurySourceFlowsDetailsType'
instance ToJSON ReceivedCreditsResourceTreasurySourceFlowsDetailsType'
