module StripeAPI.Types.ReceivedCreditsResourceStatusTransitions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data ReceivedCreditsResourceStatusTransitions
instance Show ReceivedCreditsResourceStatusTransitions
instance Eq ReceivedCreditsResourceStatusTransitions
instance FromJSON ReceivedCreditsResourceStatusTransitions
instance ToJSON ReceivedCreditsResourceStatusTransitions
