module StripeAPI.Types.ReceivedCreditsResourceReversalDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data ReceivedCreditsResourceReversalDetails
instance Show ReceivedCreditsResourceReversalDetails
instance Eq ReceivedCreditsResourceReversalDetails
instance FromJSON ReceivedCreditsResourceReversalDetails
instance ToJSON ReceivedCreditsResourceReversalDetails
data ReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
instance Show ReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
instance Eq ReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
instance FromJSON ReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
instance ToJSON ReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
