module StripeAPI.Types.ReceivedCreditsResourceTreasuryLinkedFlows where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data ReceivedCreditsResourceTreasuryLinkedFlows
instance Show ReceivedCreditsResourceTreasuryLinkedFlows
instance Eq ReceivedCreditsResourceTreasuryLinkedFlows
instance FromJSON ReceivedCreditsResourceTreasuryLinkedFlows
instance ToJSON ReceivedCreditsResourceTreasuryLinkedFlows
data ReceivedCreditsResourceTreasuryLinkedFlowsSourceFlowDetails'NonNullable
instance Show ReceivedCreditsResourceTreasuryLinkedFlowsSourceFlowDetails'NonNullable
instance Eq ReceivedCreditsResourceTreasuryLinkedFlowsSourceFlowDetails'NonNullable
instance FromJSON ReceivedCreditsResourceTreasuryLinkedFlowsSourceFlowDetails'NonNullable
instance ToJSON ReceivedCreditsResourceTreasuryLinkedFlowsSourceFlowDetails'NonNullable
data ReceivedCreditsResourceTreasuryLinkedFlowsSourceFlowDetails'NonNullableType'
instance Show ReceivedCreditsResourceTreasuryLinkedFlowsSourceFlowDetails'NonNullableType'
instance Eq ReceivedCreditsResourceTreasuryLinkedFlowsSourceFlowDetails'NonNullableType'
instance FromJSON ReceivedCreditsResourceTreasuryLinkedFlowsSourceFlowDetails'NonNullableType'
instance ToJSON ReceivedCreditsResourceTreasuryLinkedFlowsSourceFlowDetails'NonNullableType'
