module StripeAPI.Types.RefundDestinationDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data RefundDestinationDetails
instance Show RefundDestinationDetails
instance Eq RefundDestinationDetails
instance FromJSON RefundDestinationDetails
instance ToJSON RefundDestinationDetails
