module StripeAPI.Types.SchedulesPhaseAutomaticTax where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SchedulesPhaseAutomaticTax
instance Show SchedulesPhaseAutomaticTax
instance Eq SchedulesPhaseAutomaticTax
instance FromJSON SchedulesPhaseAutomaticTax
instance ToJSON SchedulesPhaseAutomaticTax
