module StripeAPI.Types.SetupAttemptPaymentMethodDetailsCard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SetupAttemptPaymentMethodDetailsCard
instance Show SetupAttemptPaymentMethodDetailsCard
instance Eq SetupAttemptPaymentMethodDetailsCard
instance FromJSON SetupAttemptPaymentMethodDetailsCard
instance ToJSON SetupAttemptPaymentMethodDetailsCard
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'
instance FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'
instance ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'AuthenticationFlow'
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'AuthenticationFlow'
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'AuthenticationFlow'
instance FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'AuthenticationFlow'
instance ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'AuthenticationFlow'
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'Result'
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'Result'
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'Result'
instance FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'Result'
instance ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'Result'
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'ResultReason'
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'ResultReason'
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'ResultReason'
instance FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'ResultReason'
instance ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'ResultReason'
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'Version'
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'Version'
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'Version'
instance FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'Version'
instance ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'Version'
