module StripeAPI.Types.SetupAttemptPaymentMethodDetailsCard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupAttemptPaymentMethodDetailsCard
instance Show SetupAttemptPaymentMethodDetailsCard
instance Eq SetupAttemptPaymentMethodDetailsCard
instance FromJSON SetupAttemptPaymentMethodDetailsCard
instance ToJSON SetupAttemptPaymentMethodDetailsCard
data SetupAttemptPaymentMethodDetailsCardChecks'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardChecks'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardChecks'NonNullable
instance FromJSON SetupAttemptPaymentMethodDetailsCardChecks'NonNullable
instance ToJSON SetupAttemptPaymentMethodDetailsCardChecks'NonNullable
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullable
instance FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullable
instance ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullable
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
instance FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
instance ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
instance FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
instance ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
instance FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
instance ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
instance FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
instance ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
instance FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
instance ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
data SetupAttemptPaymentMethodDetailsCardWallet'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardWallet'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardWallet'NonNullable
instance FromJSON SetupAttemptPaymentMethodDetailsCardWallet'NonNullable
instance ToJSON SetupAttemptPaymentMethodDetailsCardWallet'NonNullable
data SetupAttemptPaymentMethodDetailsCardWallet'NonNullableType'
instance Show SetupAttemptPaymentMethodDetailsCardWallet'NonNullableType'
instance Eq SetupAttemptPaymentMethodDetailsCardWallet'NonNullableType'
instance FromJSON SetupAttemptPaymentMethodDetailsCardWallet'NonNullableType'
instance ToJSON SetupAttemptPaymentMethodDetailsCardWallet'NonNullableType'
