module StripeAPI.Types.SetupIntentPaymentMethodOptionsCard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SetupIntentPaymentMethodOptionsCard 
instance Show SetupIntentPaymentMethodOptionsCard 
instance Eq SetupIntentPaymentMethodOptionsCard 
instance FromJSON SetupIntentPaymentMethodOptionsCard 
instance ToJSON SetupIntentPaymentMethodOptionsCard 
data SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'
instance Show SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'
instance Eq SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'
instance FromJSON SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'
instance ToJSON SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'
