module StripeAPI.Types.SetupAttemptPaymentMethodDetailsSofort where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SetupAttemptPaymentMethodDetailsSofort
instance Show SetupAttemptPaymentMethodDetailsSofort
instance Eq SetupAttemptPaymentMethodDetailsSofort
instance FromJSON SetupAttemptPaymentMethodDetailsSofort
instance ToJSON SetupAttemptPaymentMethodDetailsSofort
data SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'Variants
instance Show SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'Variants
instance Eq SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'Variants
instance FromJSON SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'Variants
instance ToJSON SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'Variants
data SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'Variants
instance Show SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'Variants
instance Eq SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'Variants
instance FromJSON SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'Variants
instance ToJSON SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'Variants
data SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'
instance Show SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'
instance Eq SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'
instance FromJSON SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'
instance ToJSON SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'
