module StripeAPI.Types.SetupIntentPaymentMethodOptionsCardMandateOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptionsCardMandateOptions
instance Show SetupIntentPaymentMethodOptionsCardMandateOptions
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptions
instance FromJSON SetupIntentPaymentMethodOptionsCardMandateOptions
instance ToJSON SetupIntentPaymentMethodOptionsCardMandateOptions
data SetupIntentPaymentMethodOptionsCardMandateOptionsAmountType'
instance Show SetupIntentPaymentMethodOptionsCardMandateOptionsAmountType'
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptionsAmountType'
instance FromJSON SetupIntentPaymentMethodOptionsCardMandateOptionsAmountType'
instance ToJSON SetupIntentPaymentMethodOptionsCardMandateOptionsAmountType'
data SetupIntentPaymentMethodOptionsCardMandateOptionsInterval'
instance Show SetupIntentPaymentMethodOptionsCardMandateOptionsInterval'
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptionsInterval'
instance FromJSON SetupIntentPaymentMethodOptionsCardMandateOptionsInterval'
instance ToJSON SetupIntentPaymentMethodOptionsCardMandateOptionsInterval'
data SetupIntentPaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance Show SetupIntentPaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance FromJSON SetupIntentPaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance ToJSON SetupIntentPaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
