module StripeAPI.Types.SetupAttemptPaymentMethodDetailsIdeal where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupAttemptPaymentMethodDetailsIdeal
instance Show SetupAttemptPaymentMethodDetailsIdeal
instance Eq SetupAttemptPaymentMethodDetailsIdeal
instance FromJSON SetupAttemptPaymentMethodDetailsIdeal
instance ToJSON SetupAttemptPaymentMethodDetailsIdeal
data SetupAttemptPaymentMethodDetailsIdealBank'NonNullable
instance Show SetupAttemptPaymentMethodDetailsIdealBank'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsIdealBank'NonNullable
instance FromJSON SetupAttemptPaymentMethodDetailsIdealBank'NonNullable
instance ToJSON SetupAttemptPaymentMethodDetailsIdealBank'NonNullable
data SetupAttemptPaymentMethodDetailsIdealBic'NonNullable
instance Show SetupAttemptPaymentMethodDetailsIdealBic'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsIdealBic'NonNullable
instance FromJSON SetupAttemptPaymentMethodDetailsIdealBic'NonNullable
instance ToJSON SetupAttemptPaymentMethodDetailsIdealBic'NonNullable
data SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'NonNullableVariants
instance FromJSON SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'NonNullableVariants
instance ToJSON SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'NonNullableVariants
data SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'NonNullableVariants
instance FromJSON SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'NonNullableVariants
instance ToJSON SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'NonNullableVariants
