module StripeAPI.Types.SetupIntentPaymentMethodOptionsCard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptionsCard
instance Show SetupIntentPaymentMethodOptionsCard
instance Eq SetupIntentPaymentMethodOptionsCard
instance FromJSON SetupIntentPaymentMethodOptionsCard
instance ToJSON SetupIntentPaymentMethodOptionsCard
data SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullable
instance Show SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullable
instance FromJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullable
instance ToJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullable
data SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
instance Show SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
instance FromJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
instance ToJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
data SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
instance Show SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
instance FromJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
instance ToJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
data SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
instance Show SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
instance FromJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
instance ToJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
data SetupIntentPaymentMethodOptionsCardNetwork'NonNullable
instance Show SetupIntentPaymentMethodOptionsCardNetwork'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCardNetwork'NonNullable
instance FromJSON SetupIntentPaymentMethodOptionsCardNetwork'NonNullable
instance ToJSON SetupIntentPaymentMethodOptionsCardNetwork'NonNullable
data SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Show SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance FromJSON SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance ToJSON SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
