module StripeAPI.Types.SetupAttemptPaymentMethodDetailsIdeal where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SetupAttemptPaymentMethodDetailsIdeal
instance Show SetupAttemptPaymentMethodDetailsIdeal
instance Eq SetupAttemptPaymentMethodDetailsIdeal
instance FromJSON SetupAttemptPaymentMethodDetailsIdeal
instance ToJSON SetupAttemptPaymentMethodDetailsIdeal
data SetupAttemptPaymentMethodDetailsIdealBank'
instance Show SetupAttemptPaymentMethodDetailsIdealBank'
instance Eq SetupAttemptPaymentMethodDetailsIdealBank'
instance FromJSON SetupAttemptPaymentMethodDetailsIdealBank'
instance ToJSON SetupAttemptPaymentMethodDetailsIdealBank'
data SetupAttemptPaymentMethodDetailsIdealBic'
instance Show SetupAttemptPaymentMethodDetailsIdealBic'
instance Eq SetupAttemptPaymentMethodDetailsIdealBic'
instance FromJSON SetupAttemptPaymentMethodDetailsIdealBic'
instance ToJSON SetupAttemptPaymentMethodDetailsIdealBic'
data SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'Variants
instance Show SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'Variants
instance Eq SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'Variants
instance FromJSON SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'Variants
instance ToJSON SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'Variants
data SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'Variants
instance Show SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'Variants
instance Eq SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'Variants
instance FromJSON SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'Variants
instance ToJSON SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'Variants
