module StripeAPI.Types.SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Show SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance FromJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance ToJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
data SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
instance Show SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
instance FromJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
instance ToJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
data SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance Show SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance FromJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance ToJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
data SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance Show SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance FromJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance ToJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
