module StripeAPI.Types.SetupAttemptPaymentMethodDetailsBancontact where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupAttemptPaymentMethodDetailsBancontact
instance Show SetupAttemptPaymentMethodDetailsBancontact
instance Eq SetupAttemptPaymentMethodDetailsBancontact
instance FromJSON SetupAttemptPaymentMethodDetailsBancontact
instance ToJSON SetupAttemptPaymentMethodDetailsBancontact
data SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance FromJSON SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance ToJSON SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
data SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance FromJSON SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance ToJSON SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
data SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance Show SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance FromJSON SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance ToJSON SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'NonNullable
