module StripeAPI.Types.SetupIntentPaymentMethodOptionsAcssDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptionsAcssDebit
instance Show SetupIntentPaymentMethodOptionsAcssDebit
instance Eq SetupIntentPaymentMethodOptionsAcssDebit
instance FromJSON SetupIntentPaymentMethodOptionsAcssDebit
instance ToJSON SetupIntentPaymentMethodOptionsAcssDebit
data SetupIntentPaymentMethodOptionsAcssDebitCurrency'NonNullable
instance Show SetupIntentPaymentMethodOptionsAcssDebitCurrency'NonNullable
instance Eq SetupIntentPaymentMethodOptionsAcssDebitCurrency'NonNullable
instance FromJSON SetupIntentPaymentMethodOptionsAcssDebitCurrency'NonNullable
instance ToJSON SetupIntentPaymentMethodOptionsAcssDebitCurrency'NonNullable
data SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Show SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance FromJSON SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance ToJSON SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
