module StripeAPI.Types.SetupIntentPaymentMethodOptionsUsBankAccount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptionsUsBankAccount
instance Show SetupIntentPaymentMethodOptionsUsBankAccount
instance Eq SetupIntentPaymentMethodOptionsUsBankAccount
instance FromJSON SetupIntentPaymentMethodOptionsUsBankAccount
instance ToJSON SetupIntentPaymentMethodOptionsUsBankAccount
data SetupIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance Show SetupIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance FromJSON SetupIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance ToJSON SetupIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
