module StripeAPI.Types.SetupAttemptPaymentMethodDetailsBancontact where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SetupAttemptPaymentMethodDetailsBancontact
instance Show SetupAttemptPaymentMethodDetailsBancontact
instance Eq SetupAttemptPaymentMethodDetailsBancontact
instance FromJSON SetupAttemptPaymentMethodDetailsBancontact
instance ToJSON SetupAttemptPaymentMethodDetailsBancontact
data SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'Variants
instance Show SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'Variants
instance Eq SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'Variants
instance FromJSON SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'Variants
instance ToJSON SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'Variants
data SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'Variants
instance Show SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'Variants
instance Eq SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'Variants
instance FromJSON SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'Variants
instance ToJSON SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'Variants
data SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'
instance Show SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'
instance Eq SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'
instance FromJSON SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'
instance ToJSON SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'
