module StripeAPI.Types.SetupAttemptPaymentMethodDetailsCardPresent where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupAttemptPaymentMethodDetailsCardPresent
instance Show SetupAttemptPaymentMethodDetailsCardPresent
instance Eq SetupAttemptPaymentMethodDetailsCardPresent
instance FromJSON SetupAttemptPaymentMethodDetailsCardPresent
instance ToJSON SetupAttemptPaymentMethodDetailsCardPresent
data SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'NonNullableVariants
instance FromJSON SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'NonNullableVariants
instance ToJSON SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'NonNullableVariants
