module StripeAPI.Types.SetupAttemptPaymentMethodDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupAttemptPaymentMethodDetails
instance Show SetupAttemptPaymentMethodDetails
instance Eq SetupAttemptPaymentMethodDetails
instance FromJSON SetupAttemptPaymentMethodDetails
instance ToJSON SetupAttemptPaymentMethodDetails
