module StripeAPI.Types.SetupAttemptPaymentMethodDetailsCardPresent where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SetupAttemptPaymentMethodDetailsCardPresent
instance Show SetupAttemptPaymentMethodDetailsCardPresent
instance Eq SetupAttemptPaymentMethodDetailsCardPresent
instance FromJSON SetupAttemptPaymentMethodDetailsCardPresent
instance ToJSON SetupAttemptPaymentMethodDetailsCardPresent
data SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'Variants
instance Show SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'Variants
instance Eq SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'Variants
instance FromJSON SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'Variants
instance ToJSON SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'Variants
