module StripeAPI.Types.SetupIntentPaymentMethodOptionsAcssDebit where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SetupIntentPaymentMethodOptionsAcssDebit
instance Show SetupIntentPaymentMethodOptionsAcssDebit
instance Eq SetupIntentPaymentMethodOptionsAcssDebit
instance FromJSON SetupIntentPaymentMethodOptionsAcssDebit
instance ToJSON SetupIntentPaymentMethodOptionsAcssDebit
data SetupIntentPaymentMethodOptionsAcssDebitCurrency'
instance Show SetupIntentPaymentMethodOptionsAcssDebitCurrency'
instance Eq SetupIntentPaymentMethodOptionsAcssDebitCurrency'
instance FromJSON SetupIntentPaymentMethodOptionsAcssDebitCurrency'
instance ToJSON SetupIntentPaymentMethodOptionsAcssDebitCurrency'
data SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Show SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance FromJSON SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance ToJSON SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
