module StripeAPI.Types.SetupIntentNextActionVerifyWithMicrodeposits where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupIntentNextActionVerifyWithMicrodeposits
instance Show SetupIntentNextActionVerifyWithMicrodeposits
instance Eq SetupIntentNextActionVerifyWithMicrodeposits
instance FromJSON SetupIntentNextActionVerifyWithMicrodeposits
instance ToJSON SetupIntentNextActionVerifyWithMicrodeposits
data SetupIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance Show SetupIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance Eq SetupIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance FromJSON SetupIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance ToJSON SetupIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
