module StripeAPI.Types.SetupAttemptPaymentMethodDetailsSofort where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupAttemptPaymentMethodDetailsSofort
instance Show SetupAttemptPaymentMethodDetailsSofort
instance Eq SetupAttemptPaymentMethodDetailsSofort
instance FromJSON SetupAttemptPaymentMethodDetailsSofort
instance ToJSON SetupAttemptPaymentMethodDetailsSofort
data SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance FromJSON SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance ToJSON SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
data SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance FromJSON SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance ToJSON SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
data SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance Show SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance FromJSON SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance ToJSON SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'NonNullable
