module StripeAPI.Types.SetupIntentPaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptions
instance Show SetupIntentPaymentMethodOptions
instance Eq SetupIntentPaymentMethodOptions
instance FromJSON SetupIntentPaymentMethodOptions
instance ToJSON SetupIntentPaymentMethodOptions
data SetupIntentPaymentMethodOptionsAcssDebit'
instance Show SetupIntentPaymentMethodOptionsAcssDebit'
instance Eq SetupIntentPaymentMethodOptionsAcssDebit'
instance FromJSON SetupIntentPaymentMethodOptionsAcssDebit'
instance ToJSON SetupIntentPaymentMethodOptionsAcssDebit'
data SetupIntentPaymentMethodOptionsAcssDebit'Currency'NonNullable
instance Show SetupIntentPaymentMethodOptionsAcssDebit'Currency'NonNullable
instance Eq SetupIntentPaymentMethodOptionsAcssDebit'Currency'NonNullable
instance FromJSON SetupIntentPaymentMethodOptionsAcssDebit'Currency'NonNullable
instance ToJSON SetupIntentPaymentMethodOptionsAcssDebit'Currency'NonNullable
data SetupIntentPaymentMethodOptionsAcssDebit'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsAcssDebit'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsAcssDebit'VerificationMethod'
instance FromJSON SetupIntentPaymentMethodOptionsAcssDebit'VerificationMethod'
instance ToJSON SetupIntentPaymentMethodOptionsAcssDebit'VerificationMethod'
data SetupIntentPaymentMethodOptionsLink'
instance Show SetupIntentPaymentMethodOptionsLink'
instance Eq SetupIntentPaymentMethodOptionsLink'
instance FromJSON SetupIntentPaymentMethodOptionsLink'
instance ToJSON SetupIntentPaymentMethodOptionsLink'
data SetupIntentPaymentMethodOptionsLink'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsLink'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsLink'VerificationMethod'
instance FromJSON SetupIntentPaymentMethodOptionsLink'VerificationMethod'
instance ToJSON SetupIntentPaymentMethodOptionsLink'VerificationMethod'
data SetupIntentPaymentMethodOptionsPaypal'
instance Show SetupIntentPaymentMethodOptionsPaypal'
instance Eq SetupIntentPaymentMethodOptionsPaypal'
instance FromJSON SetupIntentPaymentMethodOptionsPaypal'
instance ToJSON SetupIntentPaymentMethodOptionsPaypal'
data SetupIntentPaymentMethodOptionsPaypal'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsPaypal'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsPaypal'VerificationMethod'
instance FromJSON SetupIntentPaymentMethodOptionsPaypal'VerificationMethod'
instance ToJSON SetupIntentPaymentMethodOptionsPaypal'VerificationMethod'
data SetupIntentPaymentMethodOptionsSepaDebit'
instance Show SetupIntentPaymentMethodOptionsSepaDebit'
instance Eq SetupIntentPaymentMethodOptionsSepaDebit'
instance FromJSON SetupIntentPaymentMethodOptionsSepaDebit'
instance ToJSON SetupIntentPaymentMethodOptionsSepaDebit'
data SetupIntentPaymentMethodOptionsSepaDebit'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsSepaDebit'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsSepaDebit'VerificationMethod'
instance FromJSON SetupIntentPaymentMethodOptionsSepaDebit'VerificationMethod'
instance ToJSON SetupIntentPaymentMethodOptionsSepaDebit'VerificationMethod'
data SetupIntentPaymentMethodOptionsUsBankAccount'
instance Show SetupIntentPaymentMethodOptionsUsBankAccount'
instance Eq SetupIntentPaymentMethodOptionsUsBankAccount'
instance FromJSON SetupIntentPaymentMethodOptionsUsBankAccount'
instance ToJSON SetupIntentPaymentMethodOptionsUsBankAccount'
data SetupIntentPaymentMethodOptionsUsBankAccount'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsUsBankAccount'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsUsBankAccount'VerificationMethod'
instance FromJSON SetupIntentPaymentMethodOptionsUsBankAccount'VerificationMethod'
instance ToJSON SetupIntentPaymentMethodOptionsUsBankAccount'VerificationMethod'
