module StripeAPI.Types.SetupIntentTypeSpecificPaymentMethodOptionsClient where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SetupIntentTypeSpecificPaymentMethodOptionsClient
instance Show SetupIntentTypeSpecificPaymentMethodOptionsClient
instance Eq SetupIntentTypeSpecificPaymentMethodOptionsClient
instance FromJSON SetupIntentTypeSpecificPaymentMethodOptionsClient
instance ToJSON SetupIntentTypeSpecificPaymentMethodOptionsClient
data SetupIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance Show SetupIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance Eq SetupIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance FromJSON SetupIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance ToJSON SetupIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
