module StripeAPI.Types.ShippingRateDeliveryEstimate where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data ShippingRateDeliveryEstimate
instance Show ShippingRateDeliveryEstimate
instance Eq ShippingRateDeliveryEstimate
instance FromJSON ShippingRateDeliveryEstimate
instance ToJSON ShippingRateDeliveryEstimate
data ShippingRateDeliveryEstimateMaximum'NonNullable
instance Show ShippingRateDeliveryEstimateMaximum'NonNullable
instance Eq ShippingRateDeliveryEstimateMaximum'NonNullable
instance FromJSON ShippingRateDeliveryEstimateMaximum'NonNullable
instance ToJSON ShippingRateDeliveryEstimateMaximum'NonNullable
data ShippingRateDeliveryEstimateMaximum'NonNullableUnit'
instance Show ShippingRateDeliveryEstimateMaximum'NonNullableUnit'
instance Eq ShippingRateDeliveryEstimateMaximum'NonNullableUnit'
instance FromJSON ShippingRateDeliveryEstimateMaximum'NonNullableUnit'
instance ToJSON ShippingRateDeliveryEstimateMaximum'NonNullableUnit'
data ShippingRateDeliveryEstimateMinimum'NonNullable
instance Show ShippingRateDeliveryEstimateMinimum'NonNullable
instance Eq ShippingRateDeliveryEstimateMinimum'NonNullable
instance FromJSON ShippingRateDeliveryEstimateMinimum'NonNullable
instance ToJSON ShippingRateDeliveryEstimateMinimum'NonNullable
data ShippingRateDeliveryEstimateMinimum'NonNullableUnit'
instance Show ShippingRateDeliveryEstimateMinimum'NonNullableUnit'
instance Eq ShippingRateDeliveryEstimateMinimum'NonNullableUnit'
instance FromJSON ShippingRateDeliveryEstimateMinimum'NonNullableUnit'
instance ToJSON ShippingRateDeliveryEstimateMinimum'NonNullableUnit'
