module StripeAPI.Types.SourceTransactionAchCreditTransferData where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SourceTransactionAchCreditTransferData
instance Show SourceTransactionAchCreditTransferData
instance Eq SourceTransactionAchCreditTransferData
instance FromJSON SourceTransactionAchCreditTransferData
instance ToJSON SourceTransactionAchCreditTransferData
