module StripeAPI.Types.SourceTransactionSepaCreditTransferData where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SourceTransactionSepaCreditTransferData
instance Show SourceTransactionSepaCreditTransferData
instance Eq SourceTransactionSepaCreditTransferData
instance FromJSON SourceTransactionSepaCreditTransferData
instance ToJSON SourceTransactionSepaCreditTransferData
