module StripeAPI.Types.SourceTypeAchCreditTransfer where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SourceTypeAchCreditTransfer
instance Show SourceTypeAchCreditTransfer
instance Eq SourceTypeAchCreditTransfer
instance FromJSON SourceTypeAchCreditTransfer
instance ToJSON SourceTypeAchCreditTransfer
