module StripeAPI.Types.SourceMandateNotificationBacsDebitData where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SourceMandateNotificationBacsDebitData
instance Show SourceMandateNotificationBacsDebitData
instance Eq SourceMandateNotificationBacsDebitData
instance FromJSON SourceMandateNotificationBacsDebitData
instance ToJSON SourceMandateNotificationBacsDebitData
