module StripeAPI.Types.SubscriptionScheduleConfigurationItem where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SubscriptionScheduleConfigurationItem
instance Show SubscriptionScheduleConfigurationItem
instance Eq SubscriptionScheduleConfigurationItem
instance FromJSON SubscriptionScheduleConfigurationItem
instance ToJSON SubscriptionScheduleConfigurationItem
data SubscriptionScheduleConfigurationItemBillingThresholds'
instance Show SubscriptionScheduleConfigurationItemBillingThresholds'
instance Eq SubscriptionScheduleConfigurationItemBillingThresholds'
instance FromJSON SubscriptionScheduleConfigurationItemBillingThresholds'
instance ToJSON SubscriptionScheduleConfigurationItemBillingThresholds'
data SubscriptionScheduleConfigurationItemPrice'Variants
instance Show SubscriptionScheduleConfigurationItemPrice'Variants
instance Eq SubscriptionScheduleConfigurationItemPrice'Variants
instance FromJSON SubscriptionScheduleConfigurationItemPrice'Variants
instance ToJSON SubscriptionScheduleConfigurationItemPrice'Variants
