module StripeAPI.Types.SubscriptionPaymentMethodOptionsCard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SubscriptionPaymentMethodOptionsCard
instance Show SubscriptionPaymentMethodOptionsCard
instance Eq SubscriptionPaymentMethodOptionsCard
instance FromJSON SubscriptionPaymentMethodOptionsCard
instance ToJSON SubscriptionPaymentMethodOptionsCard
data SubscriptionPaymentMethodOptionsCardNetwork'NonNullable
instance Show SubscriptionPaymentMethodOptionsCardNetwork'NonNullable
instance Eq SubscriptionPaymentMethodOptionsCardNetwork'NonNullable
instance FromJSON SubscriptionPaymentMethodOptionsCardNetwork'NonNullable
instance ToJSON SubscriptionPaymentMethodOptionsCardNetwork'NonNullable
data SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Show SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Eq SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance FromJSON SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance ToJSON SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
