module StripeAPI.Types.SubscriptionsTrialsResourceEndBehavior where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SubscriptionsTrialsResourceEndBehavior
instance Show SubscriptionsTrialsResourceEndBehavior
instance Eq SubscriptionsTrialsResourceEndBehavior
instance FromJSON SubscriptionsTrialsResourceEndBehavior
instance ToJSON SubscriptionsTrialsResourceEndBehavior
data SubscriptionsTrialsResourceEndBehaviorMissingPaymentMethod'
instance Show SubscriptionsTrialsResourceEndBehaviorMissingPaymentMethod'
instance Eq SubscriptionsTrialsResourceEndBehaviorMissingPaymentMethod'
instance FromJSON SubscriptionsTrialsResourceEndBehaviorMissingPaymentMethod'
instance ToJSON SubscriptionsTrialsResourceEndBehaviorMissingPaymentMethod'
