module StripeAPI.Types.SubscriptionSchedulePhaseConfiguration where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SubscriptionSchedulePhaseConfiguration
instance Show SubscriptionSchedulePhaseConfiguration
instance Eq SubscriptionSchedulePhaseConfiguration
instance FromJSON SubscriptionSchedulePhaseConfiguration
instance ToJSON SubscriptionSchedulePhaseConfiguration
data SubscriptionSchedulePhaseConfigurationBillingCycleAnchor'NonNullable
instance Show SubscriptionSchedulePhaseConfigurationBillingCycleAnchor'NonNullable
instance Eq SubscriptionSchedulePhaseConfigurationBillingCycleAnchor'NonNullable
instance FromJSON SubscriptionSchedulePhaseConfigurationBillingCycleAnchor'NonNullable
instance ToJSON SubscriptionSchedulePhaseConfigurationBillingCycleAnchor'NonNullable
data SubscriptionSchedulePhaseConfigurationBillingThresholds'NonNullable
instance Show SubscriptionSchedulePhaseConfigurationBillingThresholds'NonNullable
instance Eq SubscriptionSchedulePhaseConfigurationBillingThresholds'NonNullable
instance FromJSON SubscriptionSchedulePhaseConfigurationBillingThresholds'NonNullable
instance ToJSON SubscriptionSchedulePhaseConfigurationBillingThresholds'NonNullable
data SubscriptionSchedulePhaseConfigurationCollectionMethod'NonNullable
instance Show SubscriptionSchedulePhaseConfigurationCollectionMethod'NonNullable
instance Eq SubscriptionSchedulePhaseConfigurationCollectionMethod'NonNullable
instance FromJSON SubscriptionSchedulePhaseConfigurationCollectionMethod'NonNullable
instance ToJSON SubscriptionSchedulePhaseConfigurationCollectionMethod'NonNullable
data SubscriptionSchedulePhaseConfigurationCoupon'NonNullableVariants
instance Show SubscriptionSchedulePhaseConfigurationCoupon'NonNullableVariants
instance Eq SubscriptionSchedulePhaseConfigurationCoupon'NonNullableVariants
instance FromJSON SubscriptionSchedulePhaseConfigurationCoupon'NonNullableVariants
instance ToJSON SubscriptionSchedulePhaseConfigurationCoupon'NonNullableVariants
data SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'NonNullableVariants
instance Show SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'NonNullableVariants
instance Eq SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'NonNullableVariants
instance FromJSON SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'NonNullableVariants
instance ToJSON SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'NonNullableVariants
data SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullable
instance Show SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullable
instance Eq SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullable
instance FromJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullable
instance ToJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullable
data SubscriptionSchedulePhaseConfigurationProrationBehavior'
instance Show SubscriptionSchedulePhaseConfigurationProrationBehavior'
instance Eq SubscriptionSchedulePhaseConfigurationProrationBehavior'
instance FromJSON SubscriptionSchedulePhaseConfigurationProrationBehavior'
instance ToJSON SubscriptionSchedulePhaseConfigurationProrationBehavior'
data SubscriptionSchedulePhaseConfigurationTransferData'NonNullable
instance Show SubscriptionSchedulePhaseConfigurationTransferData'NonNullable
instance Eq SubscriptionSchedulePhaseConfigurationTransferData'NonNullable
instance FromJSON SubscriptionSchedulePhaseConfigurationTransferData'NonNullable
instance ToJSON SubscriptionSchedulePhaseConfigurationTransferData'NonNullable
data SubscriptionSchedulePhaseConfigurationTransferData'NonNullableDestination'Variants
instance Show SubscriptionSchedulePhaseConfigurationTransferData'NonNullableDestination'Variants
instance Eq SubscriptionSchedulePhaseConfigurationTransferData'NonNullableDestination'Variants
instance FromJSON SubscriptionSchedulePhaseConfigurationTransferData'NonNullableDestination'Variants
instance ToJSON SubscriptionSchedulePhaseConfigurationTransferData'NonNullableDestination'Variants
