module StripeAPI.Types.SubscriptionsResourcePaymentMethodOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SubscriptionsResourcePaymentMethodOptions
instance Show SubscriptionsResourcePaymentMethodOptions
instance Eq SubscriptionsResourcePaymentMethodOptions
instance FromJSON SubscriptionsResourcePaymentMethodOptions
instance ToJSON SubscriptionsResourcePaymentMethodOptions
data SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullable
instance FromJSON SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullable
instance ToJSON SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullable
data SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance Show SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance Eq SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance FromJSON SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance ToJSON SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
data SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullable
instance FromJSON SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullable
instance ToJSON SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullable
data SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance Show SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance Eq SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance FromJSON SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance ToJSON SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
data SubscriptionsResourcePaymentMethodOptionsCard'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsCard'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsCard'NonNullable
instance FromJSON SubscriptionsResourcePaymentMethodOptionsCard'NonNullable
instance ToJSON SubscriptionsResourcePaymentMethodOptionsCard'NonNullable
data SubscriptionsResourcePaymentMethodOptionsCard'NonNullableNetwork'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsCard'NonNullableNetwork'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsCard'NonNullableNetwork'NonNullable
instance FromJSON SubscriptionsResourcePaymentMethodOptionsCard'NonNullableNetwork'NonNullable
instance ToJSON SubscriptionsResourcePaymentMethodOptionsCard'NonNullableNetwork'NonNullable
data SubscriptionsResourcePaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance FromJSON SubscriptionsResourcePaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance ToJSON SubscriptionsResourcePaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
data SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullable
instance FromJSON SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullable
instance ToJSON SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullable
data SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance FromJSON SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance ToJSON SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
data SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullable
instance FromJSON SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullable
instance ToJSON SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullable
data SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance Show SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance Eq SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance FromJSON SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance ToJSON SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
