module StripeAPI.Types.SubscriptionsResourcePaymentSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SubscriptionsResourcePaymentSettings
instance Show SubscriptionsResourcePaymentSettings
instance Eq SubscriptionsResourcePaymentSettings
instance FromJSON SubscriptionsResourcePaymentSettings
instance ToJSON SubscriptionsResourcePaymentSettings
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullable
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullable
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableNetwork'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableNetwork'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableNetwork'NonNullable
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableNetwork'NonNullable
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableNetwork'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
data SubscriptionsResourcePaymentSettingsPaymentMethodTypes'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodTypes'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodTypes'NonNullable
instance FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodTypes'NonNullable
instance ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodTypes'NonNullable
data SubscriptionsResourcePaymentSettingsSaveDefaultPaymentMethod'NonNullable
instance Show SubscriptionsResourcePaymentSettingsSaveDefaultPaymentMethod'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsSaveDefaultPaymentMethod'NonNullable
instance FromJSON SubscriptionsResourcePaymentSettingsSaveDefaultPaymentMethod'NonNullable
instance ToJSON SubscriptionsResourcePaymentSettingsSaveDefaultPaymentMethod'NonNullable
