module StripeAPI.Types.SubscriptionAutomaticTax where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SubscriptionAutomaticTax
instance Show SubscriptionAutomaticTax
instance Eq SubscriptionAutomaticTax
instance FromJSON SubscriptionAutomaticTax
instance ToJSON SubscriptionAutomaticTax
