module StripeAPI.Types.SubscriptionSchedulesResourceDefaultSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SubscriptionSchedulesResourceDefaultSettings
instance Show SubscriptionSchedulesResourceDefaultSettings
instance Eq SubscriptionSchedulesResourceDefaultSettings
instance FromJSON SubscriptionSchedulesResourceDefaultSettings
instance ToJSON SubscriptionSchedulesResourceDefaultSettings
data SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
instance Show SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
instance Eq SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
data SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'NonNullable
instance Show SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'NonNullable
instance Eq SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'NonNullable
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'NonNullable
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'NonNullable
data SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'NonNullable
instance Show SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'NonNullable
instance Eq SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'NonNullable
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'NonNullable
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'NonNullable
data SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'NonNullableVariants
instance Show SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'NonNullableVariants
instance Eq SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'NonNullableVariants
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'NonNullableVariants
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'NonNullableVariants
data SubscriptionSchedulesResourceDefaultSettingsInvoiceSettings'NonNullable
instance Show SubscriptionSchedulesResourceDefaultSettingsInvoiceSettings'NonNullable
instance Eq SubscriptionSchedulesResourceDefaultSettingsInvoiceSettings'NonNullable
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsInvoiceSettings'NonNullable
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsInvoiceSettings'NonNullable
data SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullable
instance Show SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullable
instance Eq SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullable
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullable
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullable
data SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullableDestination'Variants
instance Show SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullableDestination'Variants
instance Eq SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullableDestination'Variants
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullableDestination'Variants
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullableDestination'Variants
