module StripeAPI.Types.SubscriptionSchedulesResourceDefaultSettingsAutomaticTax where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
instance Show SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
instance Eq SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
