module StripeAPI.Types.SubscriptionScheduleConfigurationItem where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SubscriptionScheduleConfigurationItem 
instance Show SubscriptionScheduleConfigurationItem 
instance Eq SubscriptionScheduleConfigurationItem 
instance FromJSON SubscriptionScheduleConfigurationItem 
instance ToJSON SubscriptionScheduleConfigurationItem 
data SubscriptionScheduleConfigurationItemBillingThresholds' 
instance Show SubscriptionScheduleConfigurationItemBillingThresholds' 
instance Eq SubscriptionScheduleConfigurationItemBillingThresholds' 
instance FromJSON SubscriptionScheduleConfigurationItemBillingThresholds' 
instance ToJSON SubscriptionScheduleConfigurationItemBillingThresholds' 
data SubscriptionScheduleConfigurationItemPlan'Variants
instance Show SubscriptionScheduleConfigurationItemPlan'Variants
instance Eq SubscriptionScheduleConfigurationItemPlan'Variants
instance FromJSON SubscriptionScheduleConfigurationItemPlan'Variants
instance ToJSON SubscriptionScheduleConfigurationItemPlan'Variants
