module StripeAPI.Types.SubscriptionSchedulePhaseConfiguration where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SubscriptionSchedulePhaseConfiguration
instance Show SubscriptionSchedulePhaseConfiguration
instance Eq SubscriptionSchedulePhaseConfiguration
instance FromJSON SubscriptionSchedulePhaseConfiguration
instance ToJSON SubscriptionSchedulePhaseConfiguration
data SubscriptionSchedulePhaseConfigurationBillingThresholds'
instance Show SubscriptionSchedulePhaseConfigurationBillingThresholds'
instance Eq SubscriptionSchedulePhaseConfigurationBillingThresholds'
instance FromJSON SubscriptionSchedulePhaseConfigurationBillingThresholds'
instance ToJSON SubscriptionSchedulePhaseConfigurationBillingThresholds'
data SubscriptionSchedulePhaseConfigurationCollectionMethod'
instance Show SubscriptionSchedulePhaseConfigurationCollectionMethod'
instance Eq SubscriptionSchedulePhaseConfigurationCollectionMethod'
instance FromJSON SubscriptionSchedulePhaseConfigurationCollectionMethod'
instance ToJSON SubscriptionSchedulePhaseConfigurationCollectionMethod'
data SubscriptionSchedulePhaseConfigurationCoupon'Variants
instance Show SubscriptionSchedulePhaseConfigurationCoupon'Variants
instance Eq SubscriptionSchedulePhaseConfigurationCoupon'Variants
instance FromJSON SubscriptionSchedulePhaseConfigurationCoupon'Variants
instance ToJSON SubscriptionSchedulePhaseConfigurationCoupon'Variants
data SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'Variants
instance Show SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'Variants
instance Eq SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'Variants
instance FromJSON SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'Variants
instance ToJSON SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'Variants
data SubscriptionSchedulePhaseConfigurationInvoiceSettings'
instance Show SubscriptionSchedulePhaseConfigurationInvoiceSettings'
instance Eq SubscriptionSchedulePhaseConfigurationInvoiceSettings'
instance FromJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'
instance ToJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'
data SubscriptionSchedulePhaseConfigurationProrationBehavior'
instance Show SubscriptionSchedulePhaseConfigurationProrationBehavior'
instance Eq SubscriptionSchedulePhaseConfigurationProrationBehavior'
instance FromJSON SubscriptionSchedulePhaseConfigurationProrationBehavior'
instance ToJSON SubscriptionSchedulePhaseConfigurationProrationBehavior'
