module StripeAPI.Types.SubscriptionBillingThresholds where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SubscriptionBillingThresholds
instance Show SubscriptionBillingThresholds
instance Eq SubscriptionBillingThresholds
instance FromJSON SubscriptionBillingThresholds
instance ToJSON SubscriptionBillingThresholds
