module StripeAPI.Types.SubscriptionScheduleConfigurationItem where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data SubscriptionScheduleConfigurationItem
instance Show SubscriptionScheduleConfigurationItem
instance Eq SubscriptionScheduleConfigurationItem
instance FromJSON SubscriptionScheduleConfigurationItem
instance ToJSON SubscriptionScheduleConfigurationItem
data SubscriptionScheduleConfigurationItemBillingThresholds'NonNullable
instance Show SubscriptionScheduleConfigurationItemBillingThresholds'NonNullable
instance Eq SubscriptionScheduleConfigurationItemBillingThresholds'NonNullable
instance FromJSON SubscriptionScheduleConfigurationItemBillingThresholds'NonNullable
instance ToJSON SubscriptionScheduleConfigurationItemBillingThresholds'NonNullable
data SubscriptionScheduleConfigurationItemPrice'Variants
instance Show SubscriptionScheduleConfigurationItemPrice'Variants
instance Eq SubscriptionScheduleConfigurationItemPrice'Variants
instance FromJSON SubscriptionScheduleConfigurationItemPrice'Variants
instance ToJSON SubscriptionScheduleConfigurationItemPrice'Variants
