module StripeAPI.Types.SubscriptionSchedulesResourceDefaultSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SubscriptionSchedulesResourceDefaultSettings
instance Show SubscriptionSchedulesResourceDefaultSettings
instance Eq SubscriptionSchedulesResourceDefaultSettings
instance FromJSON SubscriptionSchedulesResourceDefaultSettings
instance ToJSON SubscriptionSchedulesResourceDefaultSettings
data SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
instance Show SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
instance Eq SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
data SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'
instance Show SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'
instance Eq SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'
data SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'
instance Show SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'
instance Eq SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'
data SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'Variants
instance Show SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'Variants
instance Eq SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'Variants
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'Variants
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'Variants
data SubscriptionSchedulesResourceDefaultSettingsInvoiceSettings'
instance Show SubscriptionSchedulesResourceDefaultSettingsInvoiceSettings'
instance Eq SubscriptionSchedulesResourceDefaultSettingsInvoiceSettings'
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsInvoiceSettings'
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsInvoiceSettings'
data SubscriptionSchedulesResourceDefaultSettingsTransferData'
instance Show SubscriptionSchedulesResourceDefaultSettingsTransferData'
instance Eq SubscriptionSchedulesResourceDefaultSettingsTransferData'
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsTransferData'
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsTransferData'
data SubscriptionSchedulesResourceDefaultSettingsTransferData'Destination'Variants
instance Show SubscriptionSchedulesResourceDefaultSettingsTransferData'Destination'Variants
instance Eq SubscriptionSchedulesResourceDefaultSettingsTransferData'Destination'Variants
instance FromJSON SubscriptionSchedulesResourceDefaultSettingsTransferData'Destination'Variants
instance ToJSON SubscriptionSchedulesResourceDefaultSettingsTransferData'Destination'Variants
