module StripeAPI.Types.SubscriptionsResourcePendingUpdate where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data SubscriptionsResourcePendingUpdate
instance Show SubscriptionsResourcePendingUpdate
instance Eq SubscriptionsResourcePendingUpdate
instance FromJSON SubscriptionsResourcePendingUpdate
instance ToJSON SubscriptionsResourcePendingUpdate
