module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsSimplified where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsSimplified
instance Show TaxProductRegistrationsResourceCountryOptionsSimplified
instance Eq TaxProductRegistrationsResourceCountryOptionsSimplified
instance FromJSON TaxProductRegistrationsResourceCountryOptionsSimplified
instance ToJSON TaxProductRegistrationsResourceCountryOptionsSimplified
