module StripeAPI.Types.TaxProductResourceCustomerDetailsResourceTaxId where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductResourceCustomerDetailsResourceTaxId
instance Show TaxProductResourceCustomerDetailsResourceTaxId
instance Eq TaxProductResourceCustomerDetailsResourceTaxId
instance FromJSON TaxProductResourceCustomerDetailsResourceTaxId
instance ToJSON TaxProductResourceCustomerDetailsResourceTaxId
data TaxProductResourceCustomerDetailsResourceTaxIdType'
instance Show TaxProductResourceCustomerDetailsResourceTaxIdType'
instance Eq TaxProductResourceCustomerDetailsResourceTaxIdType'
instance FromJSON TaxProductResourceCustomerDetailsResourceTaxIdType'
instance ToJSON TaxProductResourceCustomerDetailsResourceTaxIdType'
