module StripeAPI.Types.TaxProductResourceTaxCalculationShippingCost where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductResourceTaxCalculationShippingCost
instance Show TaxProductResourceTaxCalculationShippingCost
instance Eq TaxProductResourceTaxCalculationShippingCost
instance FromJSON TaxProductResourceTaxCalculationShippingCost
instance ToJSON TaxProductResourceTaxCalculationShippingCost
data TaxProductResourceTaxCalculationShippingCostTaxBehavior'
instance Show TaxProductResourceTaxCalculationShippingCostTaxBehavior'
instance Eq TaxProductResourceTaxCalculationShippingCostTaxBehavior'
instance FromJSON TaxProductResourceTaxCalculationShippingCostTaxBehavior'
instance ToJSON TaxProductResourceTaxCalculationShippingCostTaxBehavior'
