module StripeAPI.Types.TaxProductResourceTaxTransactionResourceReversal where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductResourceTaxTransactionResourceReversal
instance Show TaxProductResourceTaxTransactionResourceReversal
instance Eq TaxProductResourceTaxTransactionResourceReversal
instance FromJSON TaxProductResourceTaxTransactionResourceReversal
instance ToJSON TaxProductResourceTaxTransactionResourceReversal
