module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsCanada where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsCanada
instance Show TaxProductRegistrationsResourceCountryOptionsCanada
instance Eq TaxProductRegistrationsResourceCountryOptionsCanada
instance FromJSON TaxProductRegistrationsResourceCountryOptionsCanada
instance ToJSON TaxProductRegistrationsResourceCountryOptionsCanada
data TaxProductRegistrationsResourceCountryOptionsCanadaType'
instance Show TaxProductRegistrationsResourceCountryOptionsCanadaType'
instance Eq TaxProductRegistrationsResourceCountryOptionsCanadaType'
instance FromJSON TaxProductRegistrationsResourceCountryOptionsCanadaType'
instance ToJSON TaxProductRegistrationsResourceCountryOptionsCanadaType'
