module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsEuStandard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsEuStandard
instance Show TaxProductRegistrationsResourceCountryOptionsEuStandard
instance Eq TaxProductRegistrationsResourceCountryOptionsEuStandard
instance FromJSON TaxProductRegistrationsResourceCountryOptionsEuStandard
instance ToJSON TaxProductRegistrationsResourceCountryOptionsEuStandard
data TaxProductRegistrationsResourceCountryOptionsEuStandardPlaceOfSupplyScheme'
instance Show TaxProductRegistrationsResourceCountryOptionsEuStandardPlaceOfSupplyScheme'
instance Eq TaxProductRegistrationsResourceCountryOptionsEuStandardPlaceOfSupplyScheme'
instance FromJSON TaxProductRegistrationsResourceCountryOptionsEuStandardPlaceOfSupplyScheme'
instance ToJSON TaxProductRegistrationsResourceCountryOptionsEuStandardPlaceOfSupplyScheme'
