module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsDefault where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsDefault
instance Show TaxProductRegistrationsResourceCountryOptionsDefault
instance Eq TaxProductRegistrationsResourceCountryOptionsDefault
instance FromJSON TaxProductRegistrationsResourceCountryOptionsDefault
instance ToJSON TaxProductRegistrationsResourceCountryOptionsDefault
