module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsCaProvinceStandard where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsCaProvinceStandard
instance Show TaxProductRegistrationsResourceCountryOptionsCaProvinceStandard
instance Eq TaxProductRegistrationsResourceCountryOptionsCaProvinceStandard
instance FromJSON TaxProductRegistrationsResourceCountryOptionsCaProvinceStandard
instance ToJSON TaxProductRegistrationsResourceCountryOptionsCaProvinceStandard
