module StripeAPI.Types.TaxProductResourceTaxSettingsHeadOffice where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductResourceTaxSettingsHeadOffice
instance Show TaxProductResourceTaxSettingsHeadOffice
instance Eq TaxProductResourceTaxSettingsHeadOffice
instance FromJSON TaxProductResourceTaxSettingsHeadOffice
instance ToJSON TaxProductResourceTaxSettingsHeadOffice
