module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptions
instance Show TaxProductRegistrationsResourceCountryOptions
instance Eq TaxProductRegistrationsResourceCountryOptions
instance FromJSON TaxProductRegistrationsResourceCountryOptions
instance ToJSON TaxProductRegistrationsResourceCountryOptions
