module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsUnitedStates where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsUnitedStates
instance Show TaxProductRegistrationsResourceCountryOptionsUnitedStates
instance Eq TaxProductRegistrationsResourceCountryOptionsUnitedStates
instance FromJSON TaxProductRegistrationsResourceCountryOptionsUnitedStates
instance ToJSON TaxProductRegistrationsResourceCountryOptionsUnitedStates
data TaxProductRegistrationsResourceCountryOptionsUnitedStatesType'
instance Show TaxProductRegistrationsResourceCountryOptionsUnitedStatesType'
instance Eq TaxProductRegistrationsResourceCountryOptionsUnitedStatesType'
instance FromJSON TaxProductRegistrationsResourceCountryOptionsUnitedStatesType'
instance ToJSON TaxProductRegistrationsResourceCountryOptionsUnitedStatesType'
