module StripeAPI.Types.TaxProductResourceLineItemTaxBreakdown where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductResourceLineItemTaxBreakdown
instance Show TaxProductResourceLineItemTaxBreakdown
instance Eq TaxProductResourceLineItemTaxBreakdown
instance FromJSON TaxProductResourceLineItemTaxBreakdown
instance ToJSON TaxProductResourceLineItemTaxBreakdown
data TaxProductResourceLineItemTaxBreakdownSourcing'
instance Show TaxProductResourceLineItemTaxBreakdownSourcing'
instance Eq TaxProductResourceLineItemTaxBreakdownSourcing'
instance FromJSON TaxProductResourceLineItemTaxBreakdownSourcing'
instance ToJSON TaxProductResourceLineItemTaxBreakdownSourcing'
data TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullable
instance Show TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullable
instance Eq TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullable
instance FromJSON TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullable
instance ToJSON TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullable
data TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullableTaxType'
instance Show TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullableTaxType'
instance Eq TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullableTaxType'
instance FromJSON TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullableTaxType'
instance ToJSON TaxProductResourceLineItemTaxBreakdownTaxRateDetails'NonNullableTaxType'
data TaxProductResourceLineItemTaxBreakdownTaxabilityReason'
instance Show TaxProductResourceLineItemTaxBreakdownTaxabilityReason'
instance Eq TaxProductResourceLineItemTaxBreakdownTaxabilityReason'
instance FromJSON TaxProductResourceLineItemTaxBreakdownTaxabilityReason'
instance ToJSON TaxProductResourceLineItemTaxBreakdownTaxabilityReason'
