module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsUsLocalLeaseTax where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsUsLocalLeaseTax
instance Show TaxProductRegistrationsResourceCountryOptionsUsLocalLeaseTax
instance Eq TaxProductRegistrationsResourceCountryOptionsUsLocalLeaseTax
instance FromJSON TaxProductRegistrationsResourceCountryOptionsUsLocalLeaseTax
instance ToJSON TaxProductRegistrationsResourceCountryOptionsUsLocalLeaseTax
