module StripeAPI.Types.TaxProductResourceTaxSettingsDefaults where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductResourceTaxSettingsDefaults
instance Show TaxProductResourceTaxSettingsDefaults
instance Eq TaxProductResourceTaxSettingsDefaults
instance FromJSON TaxProductResourceTaxSettingsDefaults
instance ToJSON TaxProductResourceTaxSettingsDefaults
data TaxProductResourceTaxSettingsDefaultsTaxBehavior'NonNullable
instance Show TaxProductResourceTaxSettingsDefaultsTaxBehavior'NonNullable
instance Eq TaxProductResourceTaxSettingsDefaultsTaxBehavior'NonNullable
instance FromJSON TaxProductResourceTaxSettingsDefaultsTaxBehavior'NonNullable
instance ToJSON TaxProductResourceTaxSettingsDefaultsTaxBehavior'NonNullable
