module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsUsLocalAmusementTax where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsUsLocalAmusementTax
instance Show TaxProductRegistrationsResourceCountryOptionsUsLocalAmusementTax
instance Eq TaxProductRegistrationsResourceCountryOptionsUsLocalAmusementTax
instance FromJSON TaxProductRegistrationsResourceCountryOptionsUsLocalAmusementTax
instance ToJSON TaxProductRegistrationsResourceCountryOptionsUsLocalAmusementTax
