module StripeAPI.Types.TaxProductResourceTaxSettingsStatusDetailsResourcePending where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductResourceTaxSettingsStatusDetailsResourcePending
instance Show TaxProductResourceTaxSettingsStatusDetailsResourcePending
instance Eq TaxProductResourceTaxSettingsStatusDetailsResourcePending
instance FromJSON TaxProductResourceTaxSettingsStatusDetailsResourcePending
instance ToJSON TaxProductResourceTaxSettingsStatusDetailsResourcePending
