module StripeAPI.Types.TaxProductResourceTaxTransactionLineItemResourceReversal where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductResourceTaxTransactionLineItemResourceReversal
instance Show TaxProductResourceTaxTransactionLineItemResourceReversal
instance Eq TaxProductResourceTaxTransactionLineItemResourceReversal
instance FromJSON TaxProductResourceTaxTransactionLineItemResourceReversal
instance ToJSON TaxProductResourceTaxTransactionLineItemResourceReversal
