module StripeAPI.Types.TaxProductResourceCustomerDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductResourceCustomerDetails
instance Show TaxProductResourceCustomerDetails
instance Eq TaxProductResourceCustomerDetails
instance FromJSON TaxProductResourceCustomerDetails
instance ToJSON TaxProductResourceCustomerDetails
data TaxProductResourceCustomerDetailsAddress'NonNullable
instance Show TaxProductResourceCustomerDetailsAddress'NonNullable
instance Eq TaxProductResourceCustomerDetailsAddress'NonNullable
instance FromJSON TaxProductResourceCustomerDetailsAddress'NonNullable
instance ToJSON TaxProductResourceCustomerDetailsAddress'NonNullable
data TaxProductResourceCustomerDetailsAddressSource'NonNullable
instance Show TaxProductResourceCustomerDetailsAddressSource'NonNullable
instance Eq TaxProductResourceCustomerDetailsAddressSource'NonNullable
instance FromJSON TaxProductResourceCustomerDetailsAddressSource'NonNullable
instance ToJSON TaxProductResourceCustomerDetailsAddressSource'NonNullable
data TaxProductResourceCustomerDetailsTaxabilityOverride'
instance Show TaxProductResourceCustomerDetailsTaxabilityOverride'
instance Eq TaxProductResourceCustomerDetailsTaxabilityOverride'
instance FromJSON TaxProductResourceCustomerDetailsTaxabilityOverride'
instance ToJSON TaxProductResourceCustomerDetailsTaxabilityOverride'
