module StripeAPI.Types.TaxProductResourceTaxTransactionShippingCost where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductResourceTaxTransactionShippingCost
instance Show TaxProductResourceTaxTransactionShippingCost
instance Eq TaxProductResourceTaxTransactionShippingCost
instance FromJSON TaxProductResourceTaxTransactionShippingCost
instance ToJSON TaxProductResourceTaxTransactionShippingCost
data TaxProductResourceTaxTransactionShippingCostTaxBehavior'
instance Show TaxProductResourceTaxTransactionShippingCostTaxBehavior'
instance Eq TaxProductResourceTaxTransactionShippingCostTaxBehavior'
instance FromJSON TaxProductResourceTaxTransactionShippingCostTaxBehavior'
instance ToJSON TaxProductResourceTaxTransactionShippingCostTaxBehavior'
