module StripeAPI.Types.TaxProductRegistrationsResourceCountryOptionsEurope where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TaxProductRegistrationsResourceCountryOptionsEurope
instance Show TaxProductRegistrationsResourceCountryOptionsEurope
instance Eq TaxProductRegistrationsResourceCountryOptionsEurope
instance FromJSON TaxProductRegistrationsResourceCountryOptionsEurope
instance ToJSON TaxProductRegistrationsResourceCountryOptionsEurope
data TaxProductRegistrationsResourceCountryOptionsEuropeType'
instance Show TaxProductRegistrationsResourceCountryOptionsEuropeType'
instance Eq TaxProductRegistrationsResourceCountryOptionsEuropeType'
instance FromJSON TaxProductRegistrationsResourceCountryOptionsEuropeType'
instance ToJSON TaxProductRegistrationsResourceCountryOptionsEuropeType'
