module StripeAPI.Types.TerminalConfigurationConfigurationResourceCurrencySpecificConfig where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TerminalConfigurationConfigurationResourceCurrencySpecificConfig
instance Show TerminalConfigurationConfigurationResourceCurrencySpecificConfig
instance Eq TerminalConfigurationConfigurationResourceCurrencySpecificConfig
instance FromJSON TerminalConfigurationConfigurationResourceCurrencySpecificConfig
instance ToJSON TerminalConfigurationConfigurationResourceCurrencySpecificConfig
