module StripeAPI.Types.TerminalReaderReaderResourceRefundPaymentAction where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TerminalReaderReaderResourceRefundPaymentAction
instance Show TerminalReaderReaderResourceRefundPaymentAction
instance Eq TerminalReaderReaderResourceRefundPaymentAction
instance FromJSON TerminalReaderReaderResourceRefundPaymentAction
instance ToJSON TerminalReaderReaderResourceRefundPaymentAction
data TerminalReaderReaderResourceRefundPaymentActionCharge'Variants
instance Show TerminalReaderReaderResourceRefundPaymentActionCharge'Variants
instance Eq TerminalReaderReaderResourceRefundPaymentActionCharge'Variants
instance FromJSON TerminalReaderReaderResourceRefundPaymentActionCharge'Variants
instance ToJSON TerminalReaderReaderResourceRefundPaymentActionCharge'Variants
data TerminalReaderReaderResourceRefundPaymentActionPaymentIntent'Variants
instance Show TerminalReaderReaderResourceRefundPaymentActionPaymentIntent'Variants
instance Eq TerminalReaderReaderResourceRefundPaymentActionPaymentIntent'Variants
instance FromJSON TerminalReaderReaderResourceRefundPaymentActionPaymentIntent'Variants
instance ToJSON TerminalReaderReaderResourceRefundPaymentActionPaymentIntent'Variants
data TerminalReaderReaderResourceRefundPaymentActionReason'
instance Show TerminalReaderReaderResourceRefundPaymentActionReason'
instance Eq TerminalReaderReaderResourceRefundPaymentActionReason'
instance FromJSON TerminalReaderReaderResourceRefundPaymentActionReason'
instance ToJSON TerminalReaderReaderResourceRefundPaymentActionReason'
data TerminalReaderReaderResourceRefundPaymentActionRefund'Variants
instance Show TerminalReaderReaderResourceRefundPaymentActionRefund'Variants
instance Eq TerminalReaderReaderResourceRefundPaymentActionRefund'Variants
instance FromJSON TerminalReaderReaderResourceRefundPaymentActionRefund'Variants
instance ToJSON TerminalReaderReaderResourceRefundPaymentActionRefund'Variants
