module StripeAPI.Types.TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig
instance Show TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig
instance Eq TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig
instance FromJSON TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig
instance ToJSON TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfig
data TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfigSplashscreen'Variants
instance Show TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfigSplashscreen'Variants
instance Eq TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfigSplashscreen'Variants
instance FromJSON TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfigSplashscreen'Variants
instance ToJSON TerminalConfigurationConfigurationResourceDeviceTypeSpecificConfigSplashscreen'Variants
