module StripeAPI.Types.TerminalReaderReaderResourceSetReaderDisplayAction where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TerminalReaderReaderResourceSetReaderDisplayAction
instance Show TerminalReaderReaderResourceSetReaderDisplayAction
instance Eq TerminalReaderReaderResourceSetReaderDisplayAction
instance FromJSON TerminalReaderReaderResourceSetReaderDisplayAction
instance ToJSON TerminalReaderReaderResourceSetReaderDisplayAction
data TerminalReaderReaderResourceSetReaderDisplayActionCart'NonNullable
instance Show TerminalReaderReaderResourceSetReaderDisplayActionCart'NonNullable
instance Eq TerminalReaderReaderResourceSetReaderDisplayActionCart'NonNullable
instance FromJSON TerminalReaderReaderResourceSetReaderDisplayActionCart'NonNullable
instance ToJSON TerminalReaderReaderResourceSetReaderDisplayActionCart'NonNullable
