module StripeAPI.Types.TerminalConfigurationConfigurationResourceOfflineConfig where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TerminalConfigurationConfigurationResourceOfflineConfig
instance Show TerminalConfigurationConfigurationResourceOfflineConfig
instance Eq TerminalConfigurationConfigurationResourceOfflineConfig
instance FromJSON TerminalConfigurationConfigurationResourceOfflineConfig
instance ToJSON TerminalConfigurationConfigurationResourceOfflineConfig
