module StripeAPI.Types.TerminalReaderReaderResourceProcessPaymentIntentAction where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TerminalReaderReaderResourceProcessPaymentIntentAction
instance Show TerminalReaderReaderResourceProcessPaymentIntentAction
instance Eq TerminalReaderReaderResourceProcessPaymentIntentAction
instance FromJSON TerminalReaderReaderResourceProcessPaymentIntentAction
instance ToJSON TerminalReaderReaderResourceProcessPaymentIntentAction
data TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent'Variants
instance Show TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent'Variants
instance Eq TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent'Variants
instance FromJSON TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent'Variants
instance ToJSON TerminalReaderReaderResourceProcessPaymentIntentActionPaymentIntent'Variants
