module StripeAPI.Types.TerminalReaderReaderResourceProcessSetupIntentAction where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TerminalReaderReaderResourceProcessSetupIntentAction
instance Show TerminalReaderReaderResourceProcessSetupIntentAction
instance Eq TerminalReaderReaderResourceProcessSetupIntentAction
instance FromJSON TerminalReaderReaderResourceProcessSetupIntentAction
instance ToJSON TerminalReaderReaderResourceProcessSetupIntentAction
data TerminalReaderReaderResourceProcessSetupIntentActionSetupIntent'Variants
instance Show TerminalReaderReaderResourceProcessSetupIntentActionSetupIntent'Variants
instance Eq TerminalReaderReaderResourceProcessSetupIntentActionSetupIntent'Variants
instance FromJSON TerminalReaderReaderResourceProcessSetupIntentActionSetupIntent'Variants
instance ToJSON TerminalReaderReaderResourceProcessSetupIntentActionSetupIntent'Variants
