module StripeAPI.Types.TerminalReaderReaderResourceReaderAction where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TerminalReaderReaderResourceReaderAction
instance Show TerminalReaderReaderResourceReaderAction
instance Eq TerminalReaderReaderResourceReaderAction
instance FromJSON TerminalReaderReaderResourceReaderAction
instance ToJSON TerminalReaderReaderResourceReaderAction
data TerminalReaderReaderResourceReaderActionStatus'
instance Show TerminalReaderReaderResourceReaderActionStatus'
instance Eq TerminalReaderReaderResourceReaderActionStatus'
instance FromJSON TerminalReaderReaderResourceReaderActionStatus'
instance ToJSON TerminalReaderReaderResourceReaderActionStatus'
data TerminalReaderReaderResourceReaderActionType'
instance Show TerminalReaderReaderResourceReaderActionType'
instance Eq TerminalReaderReaderResourceReaderActionType'
instance FromJSON TerminalReaderReaderResourceReaderActionType'
instance ToJSON TerminalReaderReaderResourceReaderActionType'
