module StripeAPI.Types.ThreeDSecureDetailsCharge where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data ThreeDSecureDetailsCharge
instance Show ThreeDSecureDetailsCharge
instance Eq ThreeDSecureDetailsCharge
instance FromJSON ThreeDSecureDetailsCharge
instance ToJSON ThreeDSecureDetailsCharge
data ThreeDSecureDetailsChargeAuthenticationFlow'NonNullable
instance Show ThreeDSecureDetailsChargeAuthenticationFlow'NonNullable
instance Eq ThreeDSecureDetailsChargeAuthenticationFlow'NonNullable
instance FromJSON ThreeDSecureDetailsChargeAuthenticationFlow'NonNullable
instance ToJSON ThreeDSecureDetailsChargeAuthenticationFlow'NonNullable
data ThreeDSecureDetailsChargeElectronicCommerceIndicator'NonNullable
instance Show ThreeDSecureDetailsChargeElectronicCommerceIndicator'NonNullable
instance Eq ThreeDSecureDetailsChargeElectronicCommerceIndicator'NonNullable
instance FromJSON ThreeDSecureDetailsChargeElectronicCommerceIndicator'NonNullable
instance ToJSON ThreeDSecureDetailsChargeElectronicCommerceIndicator'NonNullable
data ThreeDSecureDetailsChargeExemptionIndicator'NonNullable
instance Show ThreeDSecureDetailsChargeExemptionIndicator'NonNullable
instance Eq ThreeDSecureDetailsChargeExemptionIndicator'NonNullable
instance FromJSON ThreeDSecureDetailsChargeExemptionIndicator'NonNullable
instance ToJSON ThreeDSecureDetailsChargeExemptionIndicator'NonNullable
data ThreeDSecureDetailsChargeResult'NonNullable
instance Show ThreeDSecureDetailsChargeResult'NonNullable
instance Eq ThreeDSecureDetailsChargeResult'NonNullable
instance FromJSON ThreeDSecureDetailsChargeResult'NonNullable
instance ToJSON ThreeDSecureDetailsChargeResult'NonNullable
data ThreeDSecureDetailsChargeResultReason'NonNullable
instance Show ThreeDSecureDetailsChargeResultReason'NonNullable
instance Eq ThreeDSecureDetailsChargeResultReason'NonNullable
instance FromJSON ThreeDSecureDetailsChargeResultReason'NonNullable
instance ToJSON ThreeDSecureDetailsChargeResultReason'NonNullable
data ThreeDSecureDetailsChargeVersion'NonNullable
instance Show ThreeDSecureDetailsChargeVersion'NonNullable
instance Eq ThreeDSecureDetailsChargeVersion'NonNullable
instance FromJSON ThreeDSecureDetailsChargeVersion'NonNullable
instance ToJSON ThreeDSecureDetailsChargeVersion'NonNullable
