module StripeAPI.Types.TreasuryTransactionsResourceAbstractTransactionResourceStatusTransitions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryTransactionsResourceAbstractTransactionResourceStatusTransitions
instance Show TreasuryTransactionsResourceAbstractTransactionResourceStatusTransitions
instance Eq TreasuryTransactionsResourceAbstractTransactionResourceStatusTransitions
instance FromJSON TreasuryTransactionsResourceAbstractTransactionResourceStatusTransitions
instance ToJSON TreasuryTransactionsResourceAbstractTransactionResourceStatusTransitions
