module StripeAPI.Types.TreasuryInboundTransfersResourceFailureDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryInboundTransfersResourceFailureDetails
instance Show TreasuryInboundTransfersResourceFailureDetails
instance Eq TreasuryInboundTransfersResourceFailureDetails
instance FromJSON TreasuryInboundTransfersResourceFailureDetails
instance ToJSON TreasuryInboundTransfersResourceFailureDetails
data TreasuryInboundTransfersResourceFailureDetailsCode'
instance Show TreasuryInboundTransfersResourceFailureDetailsCode'
instance Eq TreasuryInboundTransfersResourceFailureDetailsCode'
instance FromJSON TreasuryInboundTransfersResourceFailureDetailsCode'
instance ToJSON TreasuryInboundTransfersResourceFailureDetailsCode'
