module StripeAPI.Types.TreasuryFinancialAccountsResourceFinancialAddress where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceFinancialAddress
instance Show TreasuryFinancialAccountsResourceFinancialAddress
instance Eq TreasuryFinancialAccountsResourceFinancialAddress
instance FromJSON TreasuryFinancialAccountsResourceFinancialAddress
instance ToJSON TreasuryFinancialAccountsResourceFinancialAddress
data TreasuryFinancialAccountsResourceFinancialAddressSupportedNetworks'
instance Show TreasuryFinancialAccountsResourceFinancialAddressSupportedNetworks'
instance Eq TreasuryFinancialAccountsResourceFinancialAddressSupportedNetworks'
instance FromJSON TreasuryFinancialAccountsResourceFinancialAddressSupportedNetworks'
instance ToJSON TreasuryFinancialAccountsResourceFinancialAddressSupportedNetworks'
