module StripeAPI.Types.TreasuryReceivedCreditsResourceLinkedFlows where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryReceivedCreditsResourceLinkedFlows
instance Show TreasuryReceivedCreditsResourceLinkedFlows
instance Eq TreasuryReceivedCreditsResourceLinkedFlows
instance FromJSON TreasuryReceivedCreditsResourceLinkedFlows
instance ToJSON TreasuryReceivedCreditsResourceLinkedFlows
data TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullable
instance Show TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullable
instance Eq TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullable
instance FromJSON TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullable
instance ToJSON TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullable
data TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullableType'
instance Show TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullableType'
instance Eq TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullableType'
instance FromJSON TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullableType'
instance ToJSON TreasuryReceivedCreditsResourceLinkedFlowsSourceFlowDetails'NonNullableType'
