module StripeAPI.Types.TreasuryFinancialAccountsResourceOutboundTransfers where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceOutboundTransfers
instance Show TreasuryFinancialAccountsResourceOutboundTransfers
instance Eq TreasuryFinancialAccountsResourceOutboundTransfers
instance FromJSON TreasuryFinancialAccountsResourceOutboundTransfers
instance ToJSON TreasuryFinancialAccountsResourceOutboundTransfers
