module StripeAPI.Types.TreasuryReceivedCreditsResourceSourceFlowsDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryReceivedCreditsResourceSourceFlowsDetails
instance Show TreasuryReceivedCreditsResourceSourceFlowsDetails
instance Eq TreasuryReceivedCreditsResourceSourceFlowsDetails
instance FromJSON TreasuryReceivedCreditsResourceSourceFlowsDetails
instance ToJSON TreasuryReceivedCreditsResourceSourceFlowsDetails
data TreasuryReceivedCreditsResourceSourceFlowsDetailsType'
instance Show TreasuryReceivedCreditsResourceSourceFlowsDetailsType'
instance Eq TreasuryReceivedCreditsResourceSourceFlowsDetailsType'
instance FromJSON TreasuryReceivedCreditsResourceSourceFlowsDetailsType'
instance ToJSON TreasuryReceivedCreditsResourceSourceFlowsDetailsType'
