module StripeAPI.Types.TreasuryReceivedCreditsResourceReversalDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryReceivedCreditsResourceReversalDetails
instance Show TreasuryReceivedCreditsResourceReversalDetails
instance Eq TreasuryReceivedCreditsResourceReversalDetails
instance FromJSON TreasuryReceivedCreditsResourceReversalDetails
instance ToJSON TreasuryReceivedCreditsResourceReversalDetails
data TreasuryReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
instance Show TreasuryReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
instance Eq TreasuryReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
instance FromJSON TreasuryReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
instance ToJSON TreasuryReceivedCreditsResourceReversalDetailsRestrictedReason'NonNullable
