module StripeAPI.Types.TreasuryFinancialAccountsResourceToggleSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceToggleSettings
instance Show TreasuryFinancialAccountsResourceToggleSettings
instance Eq TreasuryFinancialAccountsResourceToggleSettings
instance FromJSON TreasuryFinancialAccountsResourceToggleSettings
instance ToJSON TreasuryFinancialAccountsResourceToggleSettings
data TreasuryFinancialAccountsResourceToggleSettingsStatus'
instance Show TreasuryFinancialAccountsResourceToggleSettingsStatus'
instance Eq TreasuryFinancialAccountsResourceToggleSettingsStatus'
instance FromJSON TreasuryFinancialAccountsResourceToggleSettingsStatus'
instance ToJSON TreasuryFinancialAccountsResourceToggleSettingsStatus'
