module StripeAPI.Types.TreasuryFinancialAccountsResourceAchToggleSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceAchToggleSettings
instance Show TreasuryFinancialAccountsResourceAchToggleSettings
instance Eq TreasuryFinancialAccountsResourceAchToggleSettings
instance FromJSON TreasuryFinancialAccountsResourceAchToggleSettings
instance ToJSON TreasuryFinancialAccountsResourceAchToggleSettings
data TreasuryFinancialAccountsResourceAchToggleSettingsStatus'
instance Show TreasuryFinancialAccountsResourceAchToggleSettingsStatus'
instance Eq TreasuryFinancialAccountsResourceAchToggleSettingsStatus'
instance FromJSON TreasuryFinancialAccountsResourceAchToggleSettingsStatus'
instance ToJSON TreasuryFinancialAccountsResourceAchToggleSettingsStatus'
