module StripeAPI.Types.TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions
instance Show TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions
instance Eq TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions
instance FromJSON TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions
instance ToJSON TreasuryOutboundPaymentsResourceOutboundPaymentResourceStatusTransitions
