module StripeAPI.Types.TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows
instance Show TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows
instance Eq TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows
instance FromJSON TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows
instance ToJSON TreasuryInboundTransfersResourceInboundTransferResourceLinkedFlows
