module StripeAPI.Types.TreasuryFinancialAccountsResourceAbaToggleSettings where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceAbaToggleSettings
instance Show TreasuryFinancialAccountsResourceAbaToggleSettings
instance Eq TreasuryFinancialAccountsResourceAbaToggleSettings
instance FromJSON TreasuryFinancialAccountsResourceAbaToggleSettings
instance ToJSON TreasuryFinancialAccountsResourceAbaToggleSettings
data TreasuryFinancialAccountsResourceAbaToggleSettingsStatus'
instance Show TreasuryFinancialAccountsResourceAbaToggleSettingsStatus'
instance Eq TreasuryFinancialAccountsResourceAbaToggleSettingsStatus'
instance FromJSON TreasuryFinancialAccountsResourceAbaToggleSettingsStatus'
instance ToJSON TreasuryFinancialAccountsResourceAbaToggleSettingsStatus'
