module StripeAPI.Types.TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails
instance Show TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails
instance Eq TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails
instance FromJSON TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails
instance ToJSON TreasuryOutboundPaymentsResourceOutboundPaymentResourceEndUserDetails
