module StripeAPI.Types.TreasuryFinancialAccountsResourceFinancialAddressesFeatures where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceFinancialAddressesFeatures
instance Show TreasuryFinancialAccountsResourceFinancialAddressesFeatures
instance Eq TreasuryFinancialAccountsResourceFinancialAddressesFeatures
instance FromJSON TreasuryFinancialAccountsResourceFinancialAddressesFeatures
instance ToJSON TreasuryFinancialAccountsResourceFinancialAddressesFeatures
