module StripeAPI.Types.TreasuryInboundTransfersResourceInboundTransferResourceStatusTransitions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryInboundTransfersResourceInboundTransferResourceStatusTransitions
instance Show TreasuryInboundTransfersResourceInboundTransferResourceStatusTransitions
instance Eq TreasuryInboundTransfersResourceInboundTransferResourceStatusTransitions
instance FromJSON TreasuryInboundTransfersResourceInboundTransferResourceStatusTransitions
instance ToJSON TreasuryInboundTransfersResourceInboundTransferResourceStatusTransitions
