module StripeAPI.Types.Treasury_FinancialAccountFeatures where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data Treasury'financialAccountFeatures
instance Show Treasury'financialAccountFeatures
instance Eq Treasury'financialAccountFeatures
instance FromJSON Treasury'financialAccountFeatures
instance ToJSON Treasury'financialAccountFeatures
