module StripeAPI.Types.TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetails
instance Show TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetails
instance Eq TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetails
instance FromJSON TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetails
instance ToJSON TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetails
data TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsBalance'
instance Show TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsBalance'
instance Eq TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsBalance'
instance FromJSON TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsBalance'
instance ToJSON TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsBalance'
data TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsType'
instance Show TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsType'
instance Eq TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsType'
instance FromJSON TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsType'
instance ToJSON TreasurySharedResourceInitiatingPaymentMethodDetailsInitiatingPaymentMethodDetailsType'
