module StripeAPI.Types.TreasuryFinancialAccountsResourceInboundTransfers where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceInboundTransfers
instance Show TreasuryFinancialAccountsResourceInboundTransfers
instance Eq TreasuryFinancialAccountsResourceInboundTransfers
instance FromJSON TreasuryFinancialAccountsResourceInboundTransfers
instance ToJSON TreasuryFinancialAccountsResourceInboundTransfers
