module StripeAPI.Types.TreasuryReceivedDebitsResourceLinkedFlows where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryReceivedDebitsResourceLinkedFlows
instance Show TreasuryReceivedDebitsResourceLinkedFlows
instance Eq TreasuryReceivedDebitsResourceLinkedFlows
instance FromJSON TreasuryReceivedDebitsResourceLinkedFlows
instance ToJSON TreasuryReceivedDebitsResourceLinkedFlows
