module StripeAPI.Types.TreasuryOutboundPaymentsResourceReturnedStatus where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryOutboundPaymentsResourceReturnedStatus
instance Show TreasuryOutboundPaymentsResourceReturnedStatus
instance Eq TreasuryOutboundPaymentsResourceReturnedStatus
instance FromJSON TreasuryOutboundPaymentsResourceReturnedStatus
instance ToJSON TreasuryOutboundPaymentsResourceReturnedStatus
data TreasuryOutboundPaymentsResourceReturnedStatusCode'
instance Show TreasuryOutboundPaymentsResourceReturnedStatusCode'
instance Eq TreasuryOutboundPaymentsResourceReturnedStatusCode'
instance FromJSON TreasuryOutboundPaymentsResourceReturnedStatusCode'
instance ToJSON TreasuryOutboundPaymentsResourceReturnedStatusCode'
data TreasuryOutboundPaymentsResourceReturnedStatusTransaction'Variants
instance Show TreasuryOutboundPaymentsResourceReturnedStatusTransaction'Variants
instance Eq TreasuryOutboundPaymentsResourceReturnedStatusTransaction'Variants
instance FromJSON TreasuryOutboundPaymentsResourceReturnedStatusTransaction'Variants
instance ToJSON TreasuryOutboundPaymentsResourceReturnedStatusTransaction'Variants
