module StripeAPI.Types.TreasuryOutboundTransfersResourceReturnedDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryOutboundTransfersResourceReturnedDetails
instance Show TreasuryOutboundTransfersResourceReturnedDetails
instance Eq TreasuryOutboundTransfersResourceReturnedDetails
instance FromJSON TreasuryOutboundTransfersResourceReturnedDetails
instance ToJSON TreasuryOutboundTransfersResourceReturnedDetails
data TreasuryOutboundTransfersResourceReturnedDetailsCode'
instance Show TreasuryOutboundTransfersResourceReturnedDetailsCode'
instance Eq TreasuryOutboundTransfersResourceReturnedDetailsCode'
instance FromJSON TreasuryOutboundTransfersResourceReturnedDetailsCode'
instance ToJSON TreasuryOutboundTransfersResourceReturnedDetailsCode'
data TreasuryOutboundTransfersResourceReturnedDetailsTransaction'Variants
instance Show TreasuryOutboundTransfersResourceReturnedDetailsTransaction'Variants
instance Eq TreasuryOutboundTransfersResourceReturnedDetailsTransaction'Variants
instance FromJSON TreasuryOutboundTransfersResourceReturnedDetailsTransaction'Variants
instance ToJSON TreasuryOutboundTransfersResourceReturnedDetailsTransaction'Variants
