module StripeAPI.Types.TreasuryFinancialAccountsResourceOutboundPayments where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceOutboundPayments
instance Show TreasuryFinancialAccountsResourceOutboundPayments
instance Eq TreasuryFinancialAccountsResourceOutboundPayments
instance FromJSON TreasuryFinancialAccountsResourceOutboundPayments
instance ToJSON TreasuryFinancialAccountsResourceOutboundPayments
