module StripeAPI.Types.TreasuryFinancialAccountsResourceStatusDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceStatusDetails
instance Show TreasuryFinancialAccountsResourceStatusDetails
instance Eq TreasuryFinancialAccountsResourceStatusDetails
instance FromJSON TreasuryFinancialAccountsResourceStatusDetails
instance ToJSON TreasuryFinancialAccountsResourceStatusDetails
data TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullable
instance Show TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullable
instance Eq TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullable
instance FromJSON TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullable
instance ToJSON TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullable
data TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullableReasons'
instance Show TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullableReasons'
instance Eq TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullableReasons'
instance FromJSON TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullableReasons'
instance ToJSON TreasuryFinancialAccountsResourceStatusDetailsClosed'NonNullableReasons'
