module StripeAPI.Types.TreasuryFinancialAccountsResourceClosedStatusDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceClosedStatusDetails
instance Show TreasuryFinancialAccountsResourceClosedStatusDetails
instance Eq TreasuryFinancialAccountsResourceClosedStatusDetails
instance FromJSON TreasuryFinancialAccountsResourceClosedStatusDetails
instance ToJSON TreasuryFinancialAccountsResourceClosedStatusDetails
data TreasuryFinancialAccountsResourceClosedStatusDetailsReasons'
instance Show TreasuryFinancialAccountsResourceClosedStatusDetailsReasons'
instance Eq TreasuryFinancialAccountsResourceClosedStatusDetailsReasons'
instance FromJSON TreasuryFinancialAccountsResourceClosedStatusDetailsReasons'
instance ToJSON TreasuryFinancialAccountsResourceClosedStatusDetailsReasons'
