module StripeAPI.Types.TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount
instance Show TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount
instance Eq TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount
instance FromJSON TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount
instance ToJSON TreasurySharedResourceInitiatingPaymentMethodDetailsUsBankAccount
