module StripeAPI.Types.TreasuryFinancialAccountsResourcePlatformRestrictions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourcePlatformRestrictions
instance Show TreasuryFinancialAccountsResourcePlatformRestrictions
instance Eq TreasuryFinancialAccountsResourcePlatformRestrictions
instance FromJSON TreasuryFinancialAccountsResourcePlatformRestrictions
instance ToJSON TreasuryFinancialAccountsResourcePlatformRestrictions
data TreasuryFinancialAccountsResourcePlatformRestrictionsInboundFlows'NonNullable
instance Show TreasuryFinancialAccountsResourcePlatformRestrictionsInboundFlows'NonNullable
instance Eq TreasuryFinancialAccountsResourcePlatformRestrictionsInboundFlows'NonNullable
instance FromJSON TreasuryFinancialAccountsResourcePlatformRestrictionsInboundFlows'NonNullable
instance ToJSON TreasuryFinancialAccountsResourcePlatformRestrictionsInboundFlows'NonNullable
data TreasuryFinancialAccountsResourcePlatformRestrictionsOutboundFlows'NonNullable
instance Show TreasuryFinancialAccountsResourcePlatformRestrictionsOutboundFlows'NonNullable
instance Eq TreasuryFinancialAccountsResourcePlatformRestrictionsOutboundFlows'NonNullable
instance FromJSON TreasuryFinancialAccountsResourcePlatformRestrictionsOutboundFlows'NonNullable
instance ToJSON TreasuryFinancialAccountsResourcePlatformRestrictionsOutboundFlows'NonNullable
