module StripeAPI.Types.TreasuryOutboundTransfersResourceStatusTransitions where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryOutboundTransfersResourceStatusTransitions
instance Show TreasuryOutboundTransfersResourceStatusTransitions
instance Eq TreasuryOutboundTransfersResourceStatusTransitions
instance FromJSON TreasuryOutboundTransfersResourceStatusTransitions
instance ToJSON TreasuryOutboundTransfersResourceStatusTransitions
