module StripeAPI.Types.TreasuryReceivedDebitsResourceReversalDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryReceivedDebitsResourceReversalDetails
instance Show TreasuryReceivedDebitsResourceReversalDetails
instance Eq TreasuryReceivedDebitsResourceReversalDetails
instance FromJSON TreasuryReceivedDebitsResourceReversalDetails
instance ToJSON TreasuryReceivedDebitsResourceReversalDetails
data TreasuryReceivedDebitsResourceReversalDetailsRestrictedReason'NonNullable
instance Show TreasuryReceivedDebitsResourceReversalDetailsRestrictedReason'NonNullable
instance Eq TreasuryReceivedDebitsResourceReversalDetailsRestrictedReason'NonNullable
instance FromJSON TreasuryReceivedDebitsResourceReversalDetailsRestrictedReason'NonNullable
instance ToJSON TreasuryReceivedDebitsResourceReversalDetailsRestrictedReason'NonNullable
