module StripeAPI.Types.TreasuryFinancialAccountsResourceTogglesSettingStatusDetails where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified StripeAPI.Common
data TreasuryFinancialAccountsResourceTogglesSettingStatusDetails
instance Show TreasuryFinancialAccountsResourceTogglesSettingStatusDetails
instance Eq TreasuryFinancialAccountsResourceTogglesSettingStatusDetails
instance FromJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetails
instance ToJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetails
data TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsCode'
instance Show TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsCode'
instance Eq TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsCode'
instance FromJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsCode'
instance ToJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsCode'
data TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsResolution'NonNullable
instance Show TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsResolution'NonNullable
instance Eq TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsResolution'NonNullable
instance FromJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsResolution'NonNullable
instance ToJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsResolution'NonNullable
data TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsRestriction'
instance Show TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsRestriction'
instance Eq TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsRestriction'
instance FromJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsRestriction'
instance ToJSON TreasuryFinancialAccountsResourceTogglesSettingStatusDetailsRestriction'
