version: 2

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "stripeapi.cabal" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Build example
          command: |
            cd example
            stack --no-terminal build --fast
      - save_cache:
          name: Cache Dependencies
          key: haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "stripeapi.cabal" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

workflows:
  version: 2
  all:
    jobs:
      - build
