{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE MultiWayIf #-}
{-# LANGUAGE DeriveGeneric #-}

-- | Contains the different functions to run the operation getReviews
module StripeAPI.Operations.GetReviews where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Trans.Reader
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Either
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified Data.Vector
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Generics
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified Network.HTTP.Client
import qualified Network.HTTP.Client as Network.HTTP.Client.Request
import qualified Network.HTTP.Client as Network.HTTP.Client.Types
import qualified Network.HTTP.Simple
import qualified Network.HTTP.Types
import qualified Network.HTTP.Types as Network.HTTP.Types.Status
import qualified Network.HTTP.Types as Network.HTTP.Types.URI
import qualified StripeAPI.Common
import StripeAPI.Types

-- | > GET /v1/reviews
-- 
-- \<p>Returns a list of \<code>Review\<\/code> objects that have \<code>open\<\/code> set to \<code>true\<\/code>. The objects are sorted in descending order by creation date, with the most recently created object appearing first.\<\/p>
getReviews :: forall m s . (StripeAPI.Common.MonadHTTP m, StripeAPI.Common.SecurityScheme s) => StripeAPI.Common.Configuration s  -- ^ The configuration to use in the request
  -> GHC.Maybe.Maybe Data.Text.Internal.Text                                                                                -- ^ created
  -> GHC.Maybe.Maybe Data.Text.Internal.Text                                                                                -- ^ ending_before: A cursor for use in pagination. \`ending_before\` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with \`obj_bar\`, your subsequent call can include \`ending_before=obj_bar\` in order to fetch the previous page of the list. | Constraints: Maximum length of 5000
  -> GHC.Maybe.Maybe Data.Text.Internal.Text                                                                                -- ^ expand: Specifies which fields in the response should be expanded.
  -> GHC.Maybe.Maybe GHC.Integer.Type.Integer                                                                               -- ^ limit: A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.
  -> GHC.Maybe.Maybe Data.Text.Internal.Text                                                                                -- ^ starting_after: A cursor for use in pagination. \`starting_after\` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with \`obj_foo\`, your subsequent call can include \`starting_after=obj_foo\` in order to fetch the next page of the list. | Constraints: Maximum length of 5000
  -> GHC.Maybe.Maybe GetReviewsRequestBody                                                                                  -- ^ The request body to send
  -> m (Data.Either.Either Network.HTTP.Client.Types.HttpException (Network.HTTP.Client.Types.Response GetReviewsResponse)) -- ^ Monad containing the result of the operation
getReviews config
           created
           endingBefore
           expand
           limit
           startingAfter
           body = GHC.Base.fmap (GHC.Base.fmap (\response_0 -> GHC.Base.fmap (Data.Either.either GetReviewsResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_1 -> Network.HTTP.Types.Status.statusCode status_1 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> GetReviewsResponse200 Data.Functor.<$> (Data.Aeson.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                GetReviewsResponseBody200)
                                                                                                                                                                      | GHC.Base.const GHC.Types.True (Network.HTTP.Client.Types.responseStatus response) -> GetReviewsResponseDefault Data.Functor.<$> (Data.Aeson.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                  Error)
                                                                                                                                                                      | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_0) response_0)) (StripeAPI.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "GET") (Data.Text.pack "/v1/reviews") ((Data.Text.pack ['c',
                                                                                                                                                                                                                                                                                                                                                                                                                                 'r',
                                                                                                                                                                                                                                                                                                                                                                                                                                 'e',
                                                                                                                                                                                                                                                                                                                                                                                                                                 'a',
                                                                                                                                                                                                                                                                                                                                                                                                                                 't',
                                                                                                                                                                                                                                                                                                                                                                                                                                 'e',
                                                                                                                                                                                                                                                                                                                                                                                                                                 'd'],
                                                                                                                                                                                                                                                                                                                                                                                                                 StripeAPI.Common.stringifyModel Data.Functor.<$> created) : ((Data.Text.pack ['e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'd',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'i',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'g',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             '_',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'b',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'f',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'o',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'r',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'e'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             StripeAPI.Common.stringifyModel Data.Functor.<$> endingBefore) : ((Data.Text.pack ['e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'x',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'p',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'a',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'd'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              StripeAPI.Common.stringifyModel Data.Functor.<$> expand) : ((Data.Text.pack ['l',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'i',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'm',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'i',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         't'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         StripeAPI.Common.stringifyModel Data.Functor.<$> limit) : ((Data.Text.pack ['s',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   't',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'a',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'r',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   't',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'i',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'g',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   '_',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'a',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'f',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   't',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'r'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   StripeAPI.Common.stringifyModel Data.Functor.<$> startingAfter) : []))))) body StripeAPI.Common.RequestBodyEncodingFormData)
-- | > GET /v1/reviews
-- 
-- The same as 'getReviews' but returns the raw 'Data.ByteString.Char8.ByteString'
getReviewsRaw :: forall m s . (StripeAPI.Common.MonadHTTP m,
                               StripeAPI.Common.SecurityScheme s) =>
                 StripeAPI.Common.Configuration s ->
                 GHC.Maybe.Maybe Data.Text.Internal.Text ->
                 GHC.Maybe.Maybe Data.Text.Internal.Text ->
                 GHC.Maybe.Maybe Data.Text.Internal.Text ->
                 GHC.Maybe.Maybe GHC.Integer.Type.Integer ->
                 GHC.Maybe.Maybe Data.Text.Internal.Text ->
                 GHC.Maybe.Maybe GetReviewsRequestBody ->
                 m (Data.Either.Either Network.HTTP.Client.Types.HttpException
                                       (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString))
getReviewsRaw config
              created
              endingBefore
              expand
              limit
              startingAfter
              body = GHC.Base.id (StripeAPI.Common.doBodyCallWithConfiguration config (Data.Text.toUpper GHC.Base.$ Data.Text.pack "GET") (Data.Text.pack "/v1/reviews") ((Data.Text.pack ['c',
                                                                                                                                                                                         'r',
                                                                                                                                                                                         'e',
                                                                                                                                                                                         'a',
                                                                                                                                                                                         't',
                                                                                                                                                                                         'e',
                                                                                                                                                                                         'd'],
                                                                                                                                                                         StripeAPI.Common.stringifyModel Data.Functor.<$> created) : ((Data.Text.pack ['e',
                                                                                                                                                                                                                                                     'n',
                                                                                                                                                                                                                                                     'd',
                                                                                                                                                                                                                                                     'i',
                                                                                                                                                                                                                                                     'n',
                                                                                                                                                                                                                                                     'g',
                                                                                                                                                                                                                                                     '_',
                                                                                                                                                                                                                                                     'b',
                                                                                                                                                                                                                                                     'e',
                                                                                                                                                                                                                                                     'f',
                                                                                                                                                                                                                                                     'o',
                                                                                                                                                                                                                                                     'r',
                                                                                                                                                                                                                                                     'e'],
                                                                                                                                                                                                                                     StripeAPI.Common.stringifyModel Data.Functor.<$> endingBefore) : ((Data.Text.pack ['e',
                                                                                                                                                                                                                                                                                                                      'x',
                                                                                                                                                                                                                                                                                                                      'p',
                                                                                                                                                                                                                                                                                                                      'a',
                                                                                                                                                                                                                                                                                                                      'n',
                                                                                                                                                                                                                                                                                                                      'd'],
                                                                                                                                                                                                                                                                                                      StripeAPI.Common.stringifyModel Data.Functor.<$> expand) : ((Data.Text.pack ['l',
                                                                                                                                                                                                                                                                                                                                                                                 'i',
                                                                                                                                                                                                                                                                                                                                                                                 'm',
                                                                                                                                                                                                                                                                                                                                                                                 'i',
                                                                                                                                                                                                                                                                                                                                                                                 't'],
                                                                                                                                                                                                                                                                                                                                                                 StripeAPI.Common.stringifyModel Data.Functor.<$> limit) : ((Data.Text.pack ['s',
                                                                                                                                                                                                                                                                                                                                                                                                                                           't',
                                                                                                                                                                                                                                                                                                                                                                                                                                           'a',
                                                                                                                                                                                                                                                                                                                                                                                                                                           'r',
                                                                                                                                                                                                                                                                                                                                                                                                                                           't',
                                                                                                                                                                                                                                                                                                                                                                                                                                           'i',
                                                                                                                                                                                                                                                                                                                                                                                                                                           'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                           'g',
                                                                                                                                                                                                                                                                                                                                                                                                                                           '_',
                                                                                                                                                                                                                                                                                                                                                                                                                                           'a',
                                                                                                                                                                                                                                                                                                                                                                                                                                           'f',
                                                                                                                                                                                                                                                                                                                                                                                                                                           't',
                                                                                                                                                                                                                                                                                                                                                                                                                                           'e',
                                                                                                                                                                                                                                                                                                                                                                                                                                           'r'],
                                                                                                                                                                                                                                                                                                                                                                                                                           StripeAPI.Common.stringifyModel Data.Functor.<$> startingAfter) : []))))) body StripeAPI.Common.RequestBodyEncodingFormData)
-- | > GET /v1/reviews
-- 
-- Monadic version of 'getReviews' (use with 'StripeAPI.Common.runWithConfiguration')
getReviewsM :: forall m s . (StripeAPI.Common.MonadHTTP m,
                             StripeAPI.Common.SecurityScheme s) =>
               GHC.Maybe.Maybe Data.Text.Internal.Text ->
               GHC.Maybe.Maybe Data.Text.Internal.Text ->
               GHC.Maybe.Maybe Data.Text.Internal.Text ->
               GHC.Maybe.Maybe GHC.Integer.Type.Integer ->
               GHC.Maybe.Maybe Data.Text.Internal.Text ->
               GHC.Maybe.Maybe GetReviewsRequestBody ->
               Control.Monad.Trans.Reader.ReaderT (StripeAPI.Common.Configuration s)
                                                  m
                                                  (Data.Either.Either Network.HTTP.Client.Types.HttpException
                                                                      (Network.HTTP.Client.Types.Response GetReviewsResponse))
getReviewsM created
            endingBefore
            expand
            limit
            startingAfter
            body = GHC.Base.fmap (GHC.Base.fmap (\response_2 -> GHC.Base.fmap (Data.Either.either GetReviewsResponseError GHC.Base.id GHC.Base.. (\response body -> if | (\status_3 -> Network.HTTP.Types.Status.statusCode status_3 GHC.Classes.== 200) (Network.HTTP.Client.Types.responseStatus response) -> GetReviewsResponse200 Data.Functor.<$> (Data.Aeson.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                                                                 GetReviewsResponseBody200)
                                                                                                                                                                       | GHC.Base.const GHC.Types.True (Network.HTTP.Client.Types.responseStatus response) -> GetReviewsResponseDefault Data.Functor.<$> (Data.Aeson.eitherDecodeStrict body :: Data.Either.Either GHC.Base.String
                                                                                                                                                                                                                                                                                                                                                                   Error)
                                                                                                                                                                       | GHC.Base.otherwise -> Data.Either.Left "Missing default response type") response_2) response_2)) (StripeAPI.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "GET") (Data.Text.pack "/v1/reviews") ((Data.Text.pack ['c',
                                                                                                                                                                                                                                                                                                                                                                                                                            'r',
                                                                                                                                                                                                                                                                                                                                                                                                                            'e',
                                                                                                                                                                                                                                                                                                                                                                                                                            'a',
                                                                                                                                                                                                                                                                                                                                                                                                                            't',
                                                                                                                                                                                                                                                                                                                                                                                                                            'e',
                                                                                                                                                                                                                                                                                                                                                                                                                            'd'],
                                                                                                                                                                                                                                                                                                                                                                                                            StripeAPI.Common.stringifyModel Data.Functor.<$> created) : ((Data.Text.pack ['e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'd',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'i',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'g',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '_',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'b',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'f',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'o',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'r',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'e'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        StripeAPI.Common.stringifyModel Data.Functor.<$> endingBefore) : ((Data.Text.pack ['e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'x',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'p',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'a',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'd'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         StripeAPI.Common.stringifyModel Data.Functor.<$> expand) : ((Data.Text.pack ['l',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'i',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'm',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'i',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    't'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    StripeAPI.Common.stringifyModel Data.Functor.<$> limit) : ((Data.Text.pack ['s',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              't',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'a',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'r',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              't',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'i',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'g',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              '_',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'a',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'f',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              't',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'e',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'r'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              StripeAPI.Common.stringifyModel Data.Functor.<$> startingAfter) : []))))) body StripeAPI.Common.RequestBodyEncodingFormData)
-- | > GET /v1/reviews
-- 
-- Monadic version of 'getReviewsRaw' (use with 'StripeAPI.Common.runWithConfiguration')
getReviewsRawM :: forall m s . (StripeAPI.Common.MonadHTTP m,
                                StripeAPI.Common.SecurityScheme s) =>
                  GHC.Maybe.Maybe Data.Text.Internal.Text ->
                  GHC.Maybe.Maybe Data.Text.Internal.Text ->
                  GHC.Maybe.Maybe Data.Text.Internal.Text ->
                  GHC.Maybe.Maybe GHC.Integer.Type.Integer ->
                  GHC.Maybe.Maybe Data.Text.Internal.Text ->
                  GHC.Maybe.Maybe GetReviewsRequestBody ->
                  Control.Monad.Trans.Reader.ReaderT (StripeAPI.Common.Configuration s)
                                                     m
                                                     (Data.Either.Either Network.HTTP.Client.Types.HttpException
                                                                         (Network.HTTP.Client.Types.Response Data.ByteString.Internal.ByteString))
getReviewsRawM created
               endingBefore
               expand
               limit
               startingAfter
               body = GHC.Base.id (StripeAPI.Common.doBodyCallWithConfigurationM (Data.Text.toUpper GHC.Base.$ Data.Text.pack "GET") (Data.Text.pack "/v1/reviews") ((Data.Text.pack ['c',
                                                                                                                                                                                    'r',
                                                                                                                                                                                    'e',
                                                                                                                                                                                    'a',
                                                                                                                                                                                    't',
                                                                                                                                                                                    'e',
                                                                                                                                                                                    'd'],
                                                                                                                                                                    StripeAPI.Common.stringifyModel Data.Functor.<$> created) : ((Data.Text.pack ['e',
                                                                                                                                                                                                                                                'n',
                                                                                                                                                                                                                                                'd',
                                                                                                                                                                                                                                                'i',
                                                                                                                                                                                                                                                'n',
                                                                                                                                                                                                                                                'g',
                                                                                                                                                                                                                                                '_',
                                                                                                                                                                                                                                                'b',
                                                                                                                                                                                                                                                'e',
                                                                                                                                                                                                                                                'f',
                                                                                                                                                                                                                                                'o',
                                                                                                                                                                                                                                                'r',
                                                                                                                                                                                                                                                'e'],
                                                                                                                                                                                                                                StripeAPI.Common.stringifyModel Data.Functor.<$> endingBefore) : ((Data.Text.pack ['e',
                                                                                                                                                                                                                                                                                                                 'x',
                                                                                                                                                                                                                                                                                                                 'p',
                                                                                                                                                                                                                                                                                                                 'a',
                                                                                                                                                                                                                                                                                                                 'n',
                                                                                                                                                                                                                                                                                                                 'd'],
                                                                                                                                                                                                                                                                                                 StripeAPI.Common.stringifyModel Data.Functor.<$> expand) : ((Data.Text.pack ['l',
                                                                                                                                                                                                                                                                                                                                                                            'i',
                                                                                                                                                                                                                                                                                                                                                                            'm',
                                                                                                                                                                                                                                                                                                                                                                            'i',
                                                                                                                                                                                                                                                                                                                                                                            't'],
                                                                                                                                                                                                                                                                                                                                                            StripeAPI.Common.stringifyModel Data.Functor.<$> limit) : ((Data.Text.pack ['s',
                                                                                                                                                                                                                                                                                                                                                                                                                                      't',
                                                                                                                                                                                                                                                                                                                                                                                                                                      'a',
                                                                                                                                                                                                                                                                                                                                                                                                                                      'r',
                                                                                                                                                                                                                                                                                                                                                                                                                                      't',
                                                                                                                                                                                                                                                                                                                                                                                                                                      'i',
                                                                                                                                                                                                                                                                                                                                                                                                                                      'n',
                                                                                                                                                                                                                                                                                                                                                                                                                                      'g',
                                                                                                                                                                                                                                                                                                                                                                                                                                      '_',
                                                                                                                                                                                                                                                                                                                                                                                                                                      'a',
                                                                                                                                                                                                                                                                                                                                                                                                                                      'f',
                                                                                                                                                                                                                                                                                                                                                                                                                                      't',
                                                                                                                                                                                                                                                                                                                                                                                                                                      'e',
                                                                                                                                                                                                                                                                                                                                                                                                                                      'r'],
                                                                                                                                                                                                                                                                                                                                                                                                                      StripeAPI.Common.stringifyModel Data.Functor.<$> startingAfter) : []))))) body StripeAPI.Common.RequestBodyEncodingFormData)
-- | Defines the data type for the schema getReviewsRequestBody
-- 
-- 
data GetReviewsRequestBody = GetReviewsRequestBody {
  
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.ToJSON GetReviewsRequestBody
    where toJSON obj = Data.Aeson.object []
          toEncoding obj = Data.Aeson.pairs ((Data.Aeson..=) "string" ("string" :: GHC.Base.String))
instance Data.Aeson.Types.FromJSON.FromJSON GetReviewsRequestBody
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "GetReviewsRequestBody" (\obj -> GHC.Base.pure GetReviewsRequestBody)
-- | Represents a response of the operation 'getReviews'.
-- 
-- The response constructor is chosen by the status code of the response. If no case matches (no specific case for the response code, no range case, no default case), 'GetReviewsResponseError' is used.
data GetReviewsResponse =                            
   GetReviewsResponseError GHC.Base.String           -- ^ Means either no matching case available or a parse error
  | GetReviewsResponse200 GetReviewsResponseBody200  -- ^ Successful response.
  | GetReviewsResponseDefault Error                  -- ^ Error response.
  deriving (GHC.Show.Show, GHC.Classes.Eq)
-- | Defines the data type for the schema GetReviewsResponseBody200
-- 
-- 
data GetReviewsResponseBody200 = GetReviewsResponseBody200 {
  -- | data
  getReviewsResponseBody200Data :: ([] Review)
  -- | has_more: True if this list has another page of items after this one that can be fetched.
  , getReviewsResponseBody200HasMore :: GHC.Types.Bool
  -- | object: String representing the object\'s type. Objects of the same type share the same value. Always has the value \`list\`.
  , getReviewsResponseBody200Object :: GetReviewsResponseBody200Object'
  -- | url: The URL where this list can be accessed.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  -- * Must match pattern \'^\/v1\/reviews\'
  , getReviewsResponseBody200Url :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.ToJSON GetReviewsResponseBody200
    where toJSON obj = Data.Aeson.object ((Data.Aeson..=) "data" (getReviewsResponseBody200Data obj) : (Data.Aeson..=) "has_more" (getReviewsResponseBody200HasMore obj) : (Data.Aeson..=) "object" (getReviewsResponseBody200Object obj) : (Data.Aeson..=) "url" (getReviewsResponseBody200Url obj) : [])
          toEncoding obj = Data.Aeson.pairs ((Data.Aeson..=) "data" (getReviewsResponseBody200Data obj) GHC.Base.<> ((Data.Aeson..=) "has_more" (getReviewsResponseBody200HasMore obj) GHC.Base.<> ((Data.Aeson..=) "object" (getReviewsResponseBody200Object obj) GHC.Base.<> (Data.Aeson..=) "url" (getReviewsResponseBody200Url obj))))
instance Data.Aeson.Types.FromJSON.FromJSON GetReviewsResponseBody200
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "GetReviewsResponseBody200" (\obj -> (((GHC.Base.pure GetReviewsResponseBody200 GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "data")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "has_more")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "object")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "url"))
-- | Defines the enum schema GetReviewsResponseBody200Object\'
-- 
-- String representing the object\'s type. Objects of the same type share the same value. Always has the value \`list\`.
data GetReviewsResponseBody200Object'
    = GetReviewsResponseBody200Object'EnumOther Data.Aeson.Types.Internal.Value
    | GetReviewsResponseBody200Object'EnumTyped Data.Text.Internal.Text
    | GetReviewsResponseBody200Object'EnumStringList
    deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.ToJSON GetReviewsResponseBody200Object'
    where toJSON (GetReviewsResponseBody200Object'EnumOther patternName) = Data.Aeson.Types.ToJSON.toJSON patternName
          toJSON (GetReviewsResponseBody200Object'EnumTyped patternName) = Data.Aeson.Types.ToJSON.toJSON patternName
          toJSON (GetReviewsResponseBody200Object'EnumStringList) = Data.Aeson.Types.Internal.String GHC.Base.$ Data.Text.pack "list"
instance Data.Aeson.FromJSON GetReviewsResponseBody200Object'
    where parseJSON val = GHC.Base.pure (if val GHC.Classes.== (Data.Aeson.Types.Internal.String GHC.Base.$ Data.Text.pack "list")
                                          then GetReviewsResponseBody200Object'EnumStringList
                                          else GetReviewsResponseBody200Object'EnumOther val)
